/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_Feature__XN19al371OTpj0brEFc9bFog;
typedef NU8 tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA;
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* t_p0, NimStringV2 key_p1, NimStringV2 val_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4479)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, del__pureZstrtabs_u624)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, defineSymbol__condsyms_u4)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* symbols_p0, NimStringV2 symbol_p1, NimStringV2 value_p2);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___options_u262)(tyEnum_Feature__XN19al371OTpj0brEFc9bFog e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2629)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___lineinfos_u131)(tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA e_p0);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_2 = { 10 | NIM_STRLIT_FLAG, "nimhygiene" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_3 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_4 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_5 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_6 = { 14 | NIM_STRLIT_FLAG, "niminheritable" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_7 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_6};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_8 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_9 = { 8 | NIM_STRLIT_FLAG, "nimmixin" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_10 = {8, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_9};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_11 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_12 = { 10 | NIM_STRLIT_FLAG, "nimeffects" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_13 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_12};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_14 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_15 = { 8 | NIM_STRLIT_FLAG, "nimbabel" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_16 = {8, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_15};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_17 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_18 = { 15 | NIM_STRLIT_FLAG, "nimcomputedgoto" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_19 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_18};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_20 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_21 = { 8 | NIM_STRLIT_FLAG, "nimunion" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_22 = {8, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_21};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_23 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_24 = { 12 | NIM_STRLIT_FLAG, "nimnewshared" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_25 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_24};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_26 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_27 = { 14 | NIM_STRLIT_FLAG, "nimNewTypedesc" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_28 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_27};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_29 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_30 = { 19 | NIM_STRLIT_FLAG, "nimrequiresnimframe" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_31 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_30};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_32 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_33 = { 25 | NIM_STRLIT_FLAG, "nimparsebiggestfloatmagic" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_34 = {25, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_33};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_35 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_36 = { 8 | NIM_STRLIT_FLAG, "nimlocks" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_37 = {8, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_36};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_38 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_39 = { 7 | NIM_STRLIT_FLAG, "nimnode" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_40 = {7, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_39};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_41 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_42 = { 15 | NIM_STRLIT_FLAG, "nimvarargstyped" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_43 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_42};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_44 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_45 = { 16 | NIM_STRLIT_FLAG, "nimtypedescfixed" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_46 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_45};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_47 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_48 = { 13 | NIM_STRLIT_FLAG, "nimKnowsNimvm" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_49 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_48};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_50 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_51 = { 9 | NIM_STRLIT_FLAG, "nimArrIdx" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_52 = {9, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_51};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_53 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_54 = { 13 | NIM_STRLIT_FLAG, "nimHasalignOf" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_55 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_54};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_56 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_57 = { 10 | NIM_STRLIT_FLAG, "nimDistros" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_58 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_57};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_59 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_60 = { 15 | NIM_STRLIT_FLAG, "nimHasCppDefine" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_61 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_60};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_62 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_63 = { 20 | NIM_STRLIT_FLAG, "nimGenericInOutFlags" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_64 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_63};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_65 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_66 = { 29 | NIM_STRLIT_FLAG, "nimNoArrayToCstringConversion" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_67 = {29, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_66};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_68 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_69 = { 22 | NIM_STRLIT_FLAG, "nimHasRunnableExamples" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_70 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_69};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_71 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_72 = { 9 | NIM_STRLIT_FLAG, "nimNewDot" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_73 = {9, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_72};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_74 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_75 = { 15 | NIM_STRLIT_FLAG, "nimHasNilChecks" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_76 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_75};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_77 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_78 = { 10 | NIM_STRLIT_FLAG, "nimSymKind" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_79 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_78};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_80 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_81 = { 12 | NIM_STRLIT_FLAG, "nimVmEqIdent" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_82 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_81};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_83 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_84 = { 8 | NIM_STRLIT_FLAG, "nimNoNil" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_85 = {8, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_84};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_86 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_87 = { 19 | NIM_STRLIT_FLAG, "nimNoZeroTerminator" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_88 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_87};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_89 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_90 = { 9 | NIM_STRLIT_FLAG, "nimNotNil" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_91 = {9, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_90};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_92 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_93 = { 16 | NIM_STRLIT_FLAG, "nimVmExportFixed" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_94 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_93};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_95 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_96 = { 21 | NIM_STRLIT_FLAG, "nimHasSymOwnerInMacro" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_97 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_96};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_98 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_99 = { 13 | NIM_STRLIT_FLAG, "nimNewRuntime" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_100 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_99};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_101 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_102 = { 12 | NIM_STRLIT_FLAG, "nimIncrSeqV3" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_103 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_102};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_104 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_105 = { 7 | NIM_STRLIT_FLAG, "nimAshr" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_106 = {7, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_105};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_107 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_108 = { 12 | NIM_STRLIT_FLAG, "nimNoNilSeqs" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_109 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_108};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_110 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_111 = { 13 | NIM_STRLIT_FLAG, "nimNoNilSeqs2" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_112 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_111};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_113 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_114 = { 16 | NIM_STRLIT_FLAG, "nimHasUserErrors" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_115 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_114};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_116 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_117 = { 20 | NIM_STRLIT_FLAG, "nimUncheckedArrayTyp" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_118 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_117};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_119 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_120 = { 12 | NIM_STRLIT_FLAG, "nimHasTypeof" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_121 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_120};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_122 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_123 = { 23 | NIM_STRLIT_FLAG, "nimErrorProcCanHaveBody" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_124 = {23, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_123};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_125 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_126 = { 28 | NIM_STRLIT_FLAG, "nimHasInstantiationOfInMacro" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_127 = {28, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_126};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_128 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_129 = { 22 | NIM_STRLIT_FLAG, "nimHasHotCodeReloading" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_130 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_129};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_131 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_132 = { 13 | NIM_STRLIT_FLAG, "nimHasNilSeqs" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_133 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_132};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_134 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_135 = { 26 | NIM_STRLIT_FLAG, "nimHasSignatureHashInMacro" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_136 = {26, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_135};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_137 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_138 = { 13 | NIM_STRLIT_FLAG, "nimHasDefault" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_139 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_138};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_140 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_141 = { 20 | NIM_STRLIT_FLAG, "nimMacrosSizealignof" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_142 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_141};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_143 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_144 = { 20 | NIM_STRLIT_FLAG, "nimNoZeroExtendMagic" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_145 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_144};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_146 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_147 = { 18 | NIM_STRLIT_FLAG, "nimMacrosGetNodeId" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_148 = {18, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_147};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_149 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_150 = { 22 | NIM_STRLIT_FLAG, "nimFixedForwardGeneric" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_151 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_150};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_152 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_153 = { 21 | NIM_STRLIT_FLAG, "nimToOpenArrayCString" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_154 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_153};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_155 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_156 = { 10 | NIM_STRLIT_FLAG, "nimHasUsed" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_157 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_156};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_158 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_159 = { 12 | NIM_STRLIT_FLAG, "nimnomagic64" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_160 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_159};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_161 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_162 = { 14 | NIM_STRLIT_FLAG, "nimNewShiftOps" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_163 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_162};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_164 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_165 = { 12 | NIM_STRLIT_FLAG, "nimHasCursor" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_166 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_165};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_167 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_168 = { 14 | NIM_STRLIT_FLAG, "nimAlignPragma" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_169 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_168};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_170 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_171 = { 21 | NIM_STRLIT_FLAG, "nimHasExceptionsQuery" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_172 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_171};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_173 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_174 = { 18 | NIM_STRLIT_FLAG, "nimHasIsNamedTuple" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_175 = {18, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_174};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_176 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_177 = { 19 | NIM_STRLIT_FLAG, "nimHashOrdinalFixed" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_178 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_177};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_179 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_180 = { 19 | NIM_STRLIT_FLAG, "nimHasSinkInference" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_181 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_180};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_182 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_183 = { 16 | NIM_STRLIT_FLAG, "nimNewIntegerOps" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_184 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_183};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_185 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_186 = { 15 | NIM_STRLIT_FLAG, "nimHasInvariant" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_187 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_186};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_188 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_189 = { 6 | NIM_STRLIT_FLAG, "nimHas" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_190 = {6, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_189};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_192 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_194 = { 13 | NIM_STRLIT_FLAG, "nimHasWarning" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_195 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_194};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_196 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_198 = { 10 | NIM_STRLIT_FLAG, "nimHasHint" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_199 = {10, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_198};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_200 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_202 = { 13 | NIM_STRLIT_FLAG, "nimFixedOwned" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_203 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_202};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_204 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_205 = { 17 | NIM_STRLIT_FLAG, "nimHasStyleChecks" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_206 = {17, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_205};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_207 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_208 = { 20 | NIM_STRLIT_FLAG, "nimHasStacktraceMsgs" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_209 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_208};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_210 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_211 = { 21 | NIM_STRLIT_FLAG, "nimDoesntTrackDefects" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_212 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_211};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_213 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_214 = { 19 | NIM_STRLIT_FLAG, "nimHasLentIterators" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_215 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_214};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_216 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_217 = { 19 | NIM_STRLIT_FLAG, "nimHasDeclaredMagic" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_218 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_217};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_219 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_220 = { 23 | NIM_STRLIT_FLAG, "nimHasStacktracesModule" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_221 = {23, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_220};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_222 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_223 = { 24 | NIM_STRLIT_FLAG, "nimHasEffectTraitsModule" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_224 = {24, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_223};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_225 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_226 = { 22 | NIM_STRLIT_FLAG, "nimHasCastPragmaBlocks" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_227 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_226};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_228 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_229 = { 18 | NIM_STRLIT_FLAG, "nimHasDeclaredLocs" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_230 = {18, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_229};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_231 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_232 = { 21 | NIM_STRLIT_FLAG, "nimHasJsBigIntBackend" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_233 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_232};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_234 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_235 = { 20 | NIM_STRLIT_FLAG, "nimHasWarningAsError" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_236 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_235};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_237 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_238 = { 17 | NIM_STRLIT_FLAG, "nimHasHintAsError" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_239 = {17, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_238};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_240 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_241 = { 18 | NIM_STRLIT_FLAG, "nimHasSpellSuggest" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_242 = {18, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_241};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_243 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_244 = { 20 | NIM_STRLIT_FLAG, "nimHasCustomLiterals" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_245 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_244};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_246 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_247 = { 18 | NIM_STRLIT_FLAG, "nimHasUnifiedTuple" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_248 = {18, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_247};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_249 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_250 = { 14 | NIM_STRLIT_FLAG, "nimHasIterable" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_251 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_250};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_252 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_253 = { 16 | NIM_STRLIT_FLAG, "nimHasTypeofVoid" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_254 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_253};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_255 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_256 = { 15 | NIM_STRLIT_FLAG, "nimHasDragonBox" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_257 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_256};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_258 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_259 = { 13 | NIM_STRLIT_FLAG, "nimHasHintAll" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_260 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_259};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_261 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_262 = { 11 | NIM_STRLIT_FLAG, "nimHasTrace" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_263 = {11, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_262};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_264 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_265 = { 15 | NIM_STRLIT_FLAG, "nimHasEffectsOf" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_266 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_265};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_267 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_268 = { 21 | NIM_STRLIT_FLAG, "nimHasEnforceNoRaises" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_269 = {21, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_268};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_270 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_271 = { 22 | NIM_STRLIT_FLAG, "nimHasTopDownInference" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_272 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_271};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_273 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_274 = { 32 | NIM_STRLIT_FLAG, "nimHasTemplateRedefinitionPragma" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_275 = {32, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_274};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_276 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_277 = { 17 | NIM_STRLIT_FLAG, "nimHasCstringCase" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_278 = {17, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_277};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_279 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_280 = { 20 | NIM_STRLIT_FLAG, "nimHasCallsitePragma" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_281 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_280};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_282 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_283 = { 19 | NIM_STRLIT_FLAG, "nimHasWarnCastSizes" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_284 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_283};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_285 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_286 = { 15 | NIM_STRLIT_FLAG, "nimHasOutParams" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_287 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_286};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_288 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_289 = { 24 | NIM_STRLIT_FLAG, "nimHasSystemRaisesDefect" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_290 = {24, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_289};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_291 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_292 = { 22 | NIM_STRLIT_FLAG, "nimHasWarnUnnamedBreak" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_293 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_292};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_294 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_295 = { 19 | NIM_STRLIT_FLAG, "nimHasGenericDefine" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_296 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_295};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_297 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_298 = { 19 | NIM_STRLIT_FLAG, "nimHasDefineAliases" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_299 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_298};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_300 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_301 = { 20 | NIM_STRLIT_FLAG, "nimHasWarnBareExcept" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_302 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_301};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_303 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_304 = { 9 | NIM_STRLIT_FLAG, "nimHasDup" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_305 = {9, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_304};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_306 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_307 = { 15 | NIM_STRLIT_FLAG, "nimHasChecksums" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_308 = {15, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_307};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_309 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_310 = { 14 | NIM_STRLIT_FLAG, "nimHasSendable" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_311 = {14, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_310};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_312 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_313 = { 24 | NIM_STRLIT_FLAG, "nimAllowNonVarDestructor" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_314 = {24, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_313};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_315 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_316 = { 12 | NIM_STRLIT_FLAG, "nimHasQuirky" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_317 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_316};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_318 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_319 = { 16 | NIM_STRLIT_FLAG, "nimHasEnsureMove" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_320 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_319};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_321 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_322 = { 19 | NIM_STRLIT_FLAG, "nimHasNoReturnError" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_323 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_322};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_324 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_325 = { 16 | NIM_STRLIT_FLAG, "nimUseStrictDefs" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_326 = {16, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_325};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_327 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_328 = { 19 | NIM_STRLIT_FLAG, "nimHasNolineTooLong" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_329 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_328};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_330 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_331 = { 20 | NIM_STRLIT_FLAG, "nimHasCastExtendedVm" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_332 = {20, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_331};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_333 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_334 = { 19 | NIM_STRLIT_FLAG, "nimHasWarnStdPrefix" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_335 = {19, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_334};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_336 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_337 = { 13 | NIM_STRLIT_FLAG, "nimHasVtables" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_338 = {13, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_337};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_339 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_340 = { 22 | NIM_STRLIT_FLAG, "nimHasGenericsOpenSym2" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_341 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_340};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_342 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_343 = { 22 | NIM_STRLIT_FLAG, "nimHasGenericsOpenSym3" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_344 = {22, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_343};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_345 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_346 = { 23 | NIM_STRLIT_FLAG, "nimHasJsNoLambdaLifting" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_347 = {23, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_346};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_348 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_349 = { 27 | NIM_STRLIT_FLAG, "nimHasDefaultFloatRoundtrip" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_350 = {27, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_349};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_351 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_352 = { 12 | NIM_STRLIT_FLAG, "nimHasXorSet" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_353 = {12, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_352};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_354 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__UpH3CWy69aOHB2xkQBDirlg_355 = { 33 | NIM_STRLIT_FLAG, "nimHasPreviewDuplicateModuleError" };
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_356 = {33, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_355};
static const NimStringV2 TM__UpH3CWy69aOHB2xkQBDirlg_357 = {4, (NimStrPayload*)&TM__UpH3CWy69aOHB2xkQBDirlg_4};
extern NIM_BOOL nimInErrorMode__system_u4261;
extern TFrame* framePtr__system_u2667;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4261);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4479();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, defineSymbol__condsyms_u4)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* symbols_p0, NimStringV2 symbol_p1, NimStringV2 value_p2) {
NIM_BOOL* nimErr_;
	nimfr_("defineSymbol", "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(19, "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");	nstPut(symbols_p0, symbol_p1, value_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, undefSymbol__condsyms_u8)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* symbols_p0, NimStringV2 symbol_p1) {
NIM_BOOL* nimErr_;
	nimfr_("undefSymbol", "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimln_(22);	del__pureZstrtabs_u624(symbols_p0, symbol_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__UpH3CWy69aOHB2xkQBDirlg_191;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1728(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__UpH3CWy69aOHB2xkQBDirlg_191)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__UpH3CWy69aOHB2xkQBDirlg_191);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initDefines__condsyms_u17)(tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* symbols_p0) {
NIM_BOOL* nimErr_;
	nimfr_("initDefines", "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");
{nimErr_ = nimErrorFlag();
	nimln_(37);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_3, TM__UpH3CWy69aOHB2xkQBDirlg_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(38);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_7, TM__UpH3CWy69aOHB2xkQBDirlg_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(39);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_10, TM__UpH3CWy69aOHB2xkQBDirlg_11);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(40);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_13, TM__UpH3CWy69aOHB2xkQBDirlg_14);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(41);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_16, TM__UpH3CWy69aOHB2xkQBDirlg_17);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(42);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_19, TM__UpH3CWy69aOHB2xkQBDirlg_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(43);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_22, TM__UpH3CWy69aOHB2xkQBDirlg_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(44);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_25, TM__UpH3CWy69aOHB2xkQBDirlg_26);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(45);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_28, TM__UpH3CWy69aOHB2xkQBDirlg_29);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(46);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_31, TM__UpH3CWy69aOHB2xkQBDirlg_32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(47);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_34, TM__UpH3CWy69aOHB2xkQBDirlg_35);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(48);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_37, TM__UpH3CWy69aOHB2xkQBDirlg_38);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(49);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_40, TM__UpH3CWy69aOHB2xkQBDirlg_41);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(50);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_43, TM__UpH3CWy69aOHB2xkQBDirlg_44);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(51);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_46, TM__UpH3CWy69aOHB2xkQBDirlg_47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(52);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_49, TM__UpH3CWy69aOHB2xkQBDirlg_50);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(53);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_52, TM__UpH3CWy69aOHB2xkQBDirlg_53);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(54);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_55, TM__UpH3CWy69aOHB2xkQBDirlg_56);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(55);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_58, TM__UpH3CWy69aOHB2xkQBDirlg_59);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(56);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_61, TM__UpH3CWy69aOHB2xkQBDirlg_62);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(57);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_64, TM__UpH3CWy69aOHB2xkQBDirlg_65);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(59);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_67, TM__UpH3CWy69aOHB2xkQBDirlg_68);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(60);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_70, TM__UpH3CWy69aOHB2xkQBDirlg_71);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(61);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_73, TM__UpH3CWy69aOHB2xkQBDirlg_74);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(62);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_76, TM__UpH3CWy69aOHB2xkQBDirlg_77);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(63);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_79, TM__UpH3CWy69aOHB2xkQBDirlg_80);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(64);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_82, TM__UpH3CWy69aOHB2xkQBDirlg_83);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(65);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_85, TM__UpH3CWy69aOHB2xkQBDirlg_86);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(66);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_88, TM__UpH3CWy69aOHB2xkQBDirlg_89);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(67);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_91, TM__UpH3CWy69aOHB2xkQBDirlg_92);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(68);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_94, TM__UpH3CWy69aOHB2xkQBDirlg_95);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(69);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_97, TM__UpH3CWy69aOHB2xkQBDirlg_98);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(70);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_100, TM__UpH3CWy69aOHB2xkQBDirlg_101);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(71);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_103, TM__UpH3CWy69aOHB2xkQBDirlg_104);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(72);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_106, TM__UpH3CWy69aOHB2xkQBDirlg_107);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(73);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_109, TM__UpH3CWy69aOHB2xkQBDirlg_110);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(74);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_112, TM__UpH3CWy69aOHB2xkQBDirlg_113);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(75);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_115, TM__UpH3CWy69aOHB2xkQBDirlg_116);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(76);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_118, TM__UpH3CWy69aOHB2xkQBDirlg_119);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(77);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_121, TM__UpH3CWy69aOHB2xkQBDirlg_122);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(78);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_124, TM__UpH3CWy69aOHB2xkQBDirlg_125);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(79);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_127, TM__UpH3CWy69aOHB2xkQBDirlg_128);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(80);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_130, TM__UpH3CWy69aOHB2xkQBDirlg_131);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(81);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_133, TM__UpH3CWy69aOHB2xkQBDirlg_134);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(82);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_136, TM__UpH3CWy69aOHB2xkQBDirlg_137);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(83);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_139, TM__UpH3CWy69aOHB2xkQBDirlg_140);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(84);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_142, TM__UpH3CWy69aOHB2xkQBDirlg_143);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(85);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_145, TM__UpH3CWy69aOHB2xkQBDirlg_146);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(86);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_148, TM__UpH3CWy69aOHB2xkQBDirlg_149);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(87);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_151, TM__UpH3CWy69aOHB2xkQBDirlg_152);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(88);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_154, TM__UpH3CWy69aOHB2xkQBDirlg_155);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(89);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_157, TM__UpH3CWy69aOHB2xkQBDirlg_158);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(90);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_160, TM__UpH3CWy69aOHB2xkQBDirlg_161);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(91);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_163, TM__UpH3CWy69aOHB2xkQBDirlg_164);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(92);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_166, TM__UpH3CWy69aOHB2xkQBDirlg_167);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(93);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_169, TM__UpH3CWy69aOHB2xkQBDirlg_170);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(94);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_172, TM__UpH3CWy69aOHB2xkQBDirlg_173);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(95);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_175, TM__UpH3CWy69aOHB2xkQBDirlg_176);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(96);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_178, TM__UpH3CWy69aOHB2xkQBDirlg_179);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(97);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_181, TM__UpH3CWy69aOHB2xkQBDirlg_182);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(98);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_184, TM__UpH3CWy69aOHB2xkQBDirlg_185);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(99);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_187, TM__UpH3CWy69aOHB2xkQBDirlg_188);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyEnum_Feature__XN19al371OTpj0brEFc9bFog f_1;
		f_1 = (tyEnum_Feature__XN19al371OTpj0brEFc9bFog)0;
		{
			tyEnum_Feature__XN19al371OTpj0brEFc9bFog v_1;
			NI res_1;
			v_1 = (tyEnum_Feature__XN19al371OTpj0brEFc9bFog)0;
			nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");			res_1 = ((NI)0);
			{
				nimln_(97);				while (1) {
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T5_;
					NI TM__UpH3CWy69aOHB2xkQBDirlg_193;
					if (!(res_1 <= ((NI)24))) goto LA4;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					nimlf_(137, "/opt/local/lib/nim/lib/system/iterators.nim");					v_1 = ((tyEnum_Feature__XN19al371OTpj0brEFc9bFog) (res_1));
					nimlf_(103, "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");					f_1 = v_1;
					nimln_(104);					T5_.len = 0; T5_.p = NIM_NIL;
					colontmpD_ = dollar___options_u262(f_1);
					T5_ = rawNewString(colontmpD_.len + 6);
appendString((&T5_), TM__UpH3CWy69aOHB2xkQBDirlg_190);
appendString((&T5_), colontmpD_);
					colontmpD__2 = T5_;
					defineSymbol__condsyms_u4(symbols_p0, colontmpD__2, TM__UpH3CWy69aOHB2xkQBDirlg_192);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(res_1, ((NI)1), &TM__UpH3CWy69aOHB2xkQBDirlg_193)) { raiseOverflow(); goto BeforeRet_;
					};
					res_1 = (NI)(TM__UpH3CWy69aOHB2xkQBDirlg_193);
					nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");					eqdestroy___system_u2629(colontmpD__2);
					eqdestroy___system_u2629(colontmpD_);
				} LA4: ;
			}
		}
	}
	{
		tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA s_1;
		NI res_2;
		s_1 = (tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_2 = ((NI)20);
		{
			nimln_(97);			while (1) {
				NimStringV2 colontmpD__3;
				NimStringV2 colontmpD__4;
				NimStringV2 T9_;
				NI TM__UpH3CWy69aOHB2xkQBDirlg_197;
				if (!(res_2 <= ((NI)85))) goto LA8;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				nimlf_(106, "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");				s_1 = ((tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA) (res_2));
				nimln_(107);				T9_.len = 0; T9_.p = NIM_NIL;
				colontmpD__3 = dollar___lineinfos_u131(s_1);
				T9_ = rawNewString(colontmpD__3.len + 13);
appendString((&T9_), TM__UpH3CWy69aOHB2xkQBDirlg_195);
appendString((&T9_), colontmpD__3);
				colontmpD__4 = T9_;
				defineSymbol__condsyms_u4(symbols_p0, colontmpD__4, TM__UpH3CWy69aOHB2xkQBDirlg_196);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_2, ((NI)1), &TM__UpH3CWy69aOHB2xkQBDirlg_197)) { raiseOverflow(); goto BeforeRet_;
				};
				res_2 = (NI)(TM__UpH3CWy69aOHB2xkQBDirlg_197);
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD__4);
				eqdestroy___system_u2629(colontmpD__3);
			} LA8: ;
		}
	}
	{
		tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA s_2;
		NI res_3;
		s_2 = (tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_3 = ((NI)86);
		{
			nimln_(97);			while (1) {
				NimStringV2 colontmpD__5;
				NimStringV2 colontmpD__6;
				NimStringV2 T13_;
				NI TM__UpH3CWy69aOHB2xkQBDirlg_201;
				if (!(res_3 <= ((NI)120))) goto LA12;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				nimlf_(108, "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");				s_2 = ((tyEnum_TMsgKind__OjBmduYMQWIpXH3i9cUlajA) (res_3));
				nimln_(109);				T13_.len = 0; T13_.p = NIM_NIL;
				colontmpD__5 = dollar___lineinfos_u131(s_2);
				T13_ = rawNewString(colontmpD__5.len + 10);
appendString((&T13_), TM__UpH3CWy69aOHB2xkQBDirlg_199);
appendString((&T13_), colontmpD__5);
				colontmpD__6 = T13_;
				defineSymbol__condsyms_u4(symbols_p0, colontmpD__6, TM__UpH3CWy69aOHB2xkQBDirlg_200);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_3, ((NI)1), &TM__UpH3CWy69aOHB2xkQBDirlg_201)) { raiseOverflow(); goto BeforeRet_;
				};
				res_3 = (NI)(TM__UpH3CWy69aOHB2xkQBDirlg_201);
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD__6);
				eqdestroy___system_u2629(colontmpD__5);
			} LA12: ;
		}
	}
	nimlf_(111, "/Users/svacchanda/Dev/nimv2/compiler/condsyms.nim");	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_203, TM__UpH3CWy69aOHB2xkQBDirlg_204);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(112);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_206, TM__UpH3CWy69aOHB2xkQBDirlg_207);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(120);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_209, TM__UpH3CWy69aOHB2xkQBDirlg_210);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(121);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_212, TM__UpH3CWy69aOHB2xkQBDirlg_213);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(122);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_215, TM__UpH3CWy69aOHB2xkQBDirlg_216);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(123);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_218, TM__UpH3CWy69aOHB2xkQBDirlg_219);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(124);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_221, TM__UpH3CWy69aOHB2xkQBDirlg_222);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(125);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_224, TM__UpH3CWy69aOHB2xkQBDirlg_225);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(126);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_227, TM__UpH3CWy69aOHB2xkQBDirlg_228);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(127);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_230, TM__UpH3CWy69aOHB2xkQBDirlg_231);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(128);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_233, TM__UpH3CWy69aOHB2xkQBDirlg_234);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(129);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_236, TM__UpH3CWy69aOHB2xkQBDirlg_237);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(130);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_239, TM__UpH3CWy69aOHB2xkQBDirlg_240);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(131);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_242, TM__UpH3CWy69aOHB2xkQBDirlg_243);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(132);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_245, TM__UpH3CWy69aOHB2xkQBDirlg_246);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(133);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_248, TM__UpH3CWy69aOHB2xkQBDirlg_249);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(134);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_251, TM__UpH3CWy69aOHB2xkQBDirlg_252);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(135);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_254, TM__UpH3CWy69aOHB2xkQBDirlg_255);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(136);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_257, TM__UpH3CWy69aOHB2xkQBDirlg_258);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(137);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_260, TM__UpH3CWy69aOHB2xkQBDirlg_261);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(138);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_263, TM__UpH3CWy69aOHB2xkQBDirlg_264);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(139);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_266, TM__UpH3CWy69aOHB2xkQBDirlg_267);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(141);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_269, TM__UpH3CWy69aOHB2xkQBDirlg_270);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(142);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_272, TM__UpH3CWy69aOHB2xkQBDirlg_273);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(143);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_275, TM__UpH3CWy69aOHB2xkQBDirlg_276);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(144);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_278, TM__UpH3CWy69aOHB2xkQBDirlg_279);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(145);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_281, TM__UpH3CWy69aOHB2xkQBDirlg_282);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(147);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_284, TM__UpH3CWy69aOHB2xkQBDirlg_285);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(148);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_287, TM__UpH3CWy69aOHB2xkQBDirlg_288);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(149);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_290, TM__UpH3CWy69aOHB2xkQBDirlg_291);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(150);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_293, TM__UpH3CWy69aOHB2xkQBDirlg_294);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(151);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_296, TM__UpH3CWy69aOHB2xkQBDirlg_297);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(152);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_299, TM__UpH3CWy69aOHB2xkQBDirlg_300);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(153);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_302, TM__UpH3CWy69aOHB2xkQBDirlg_303);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(154);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_305, TM__UpH3CWy69aOHB2xkQBDirlg_306);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(155);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_308, TM__UpH3CWy69aOHB2xkQBDirlg_309);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(156);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_311, TM__UpH3CWy69aOHB2xkQBDirlg_312);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(157);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_314, TM__UpH3CWy69aOHB2xkQBDirlg_315);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(158);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_317, TM__UpH3CWy69aOHB2xkQBDirlg_318);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(159);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_320, TM__UpH3CWy69aOHB2xkQBDirlg_321);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(160);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_323, TM__UpH3CWy69aOHB2xkQBDirlg_324);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(162);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_326, TM__UpH3CWy69aOHB2xkQBDirlg_327);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(163);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_329, TM__UpH3CWy69aOHB2xkQBDirlg_330);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(165);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_332, TM__UpH3CWy69aOHB2xkQBDirlg_333);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(166);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_335, TM__UpH3CWy69aOHB2xkQBDirlg_336);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(168);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_338, TM__UpH3CWy69aOHB2xkQBDirlg_339);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(169);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_341, TM__UpH3CWy69aOHB2xkQBDirlg_342);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(170);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_344, TM__UpH3CWy69aOHB2xkQBDirlg_345);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(171);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_347, TM__UpH3CWy69aOHB2xkQBDirlg_348);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(172);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_350, TM__UpH3CWy69aOHB2xkQBDirlg_351);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(173);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_353, TM__UpH3CWy69aOHB2xkQBDirlg_354);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(175);	defineSymbol__condsyms_u4(symbols_p0, TM__UpH3CWy69aOHB2xkQBDirlg_356, TM__UpH3CWy69aOHB2xkQBDirlg_357);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
