/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ;
typedef struct tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w;
typedef struct tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg;
typedef struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ;
typedef struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA;
typedef struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg;
typedef struct tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg;
typedef struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA;
typedef struct tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA;
typedef struct tyObject_CountTable__wjTlk1kHyVlLDhtpJTNang tyObject_CountTable__wjTlk1kHyVlLDhtpJTNang;
typedef struct tySequence__14eaenldYvaMipHPmyNPjQ tySequence__14eaenldYvaMipHPmyNPjQ;
typedef struct tySequence__14eaenldYvaMipHPmyNPjQ_Content tySequence__14eaenldYvaMipHPmyNPjQ_Content;
typedef struct tyObject_Target__ZiMt9cLer9ck76lZ8l1TCLfw tyObject_Target__ZiMt9cLer9ck76lZ8l1TCLfw;
typedef struct tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w;
typedef struct tyObject_MsgConfig__oyuZDuFkUoO2ITWE0IRsuQ tyObject_MsgConfig__oyuZDuFkUoO2ITWE0IRsuQ;
typedef struct tySequence__ShJEiHHo1aNtCljYBp41CQ tySequence__ShJEiHHo1aNtCljYBp41CQ;
typedef struct tySequence__ShJEiHHo1aNtCljYBp41CQ_Content tySequence__ShJEiHHo1aNtCljYBp41CQ_Content;
typedef struct tyObject_Table__TfSbAADD2D1hZlKgnmloOA tyObject_Table__TfSbAADD2D1hZlKgnmloOA;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw tySequence__7lEisrXlQEzwtUKW5pzRCw;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content tySequence__7lEisrXlQEzwtUKW5pzRCw_Content;
typedef struct tySequence__5bkr9aLWkPbIt1PGy0PRQ4g tySequence__5bkr9aLWkPbIt1PGy0PRQ4g;
typedef struct tySequence__5bkr9aLWkPbIt1PGy0PRQ4g_Content tySequence__5bkr9aLWkPbIt1PGy0PRQ4g_Content;
typedef struct tyObject_HashSet__dcTrLn4kfefktxRri5vkXw tyObject_HashSet__dcTrLn4kfefktxRri5vkXw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg;
typedef struct tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg_Content tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg_Content;
typedef struct tyObject_SuggestcolonObjectType___cw8T4l0P9bfRcw9aAuJQpe0A tyObject_SuggestcolonObjectType___cw8T4l0P9bfRcw9aAuJQpe0A;
typedef struct tyObject_ProfileDatacolonObjectType___JmSf22j9cfqvwddpMvl3kMQ tyObject_ProfileDatacolonObjectType___JmSf22j9cfqvwddpMvl3kMQ;
typedef struct tyTuple__m0WV9c6zw9bvNqarbA9c7ZT4g tyTuple__m0WV9c6zw9bvNqarbA9c7ZT4g;
typedef struct tyTuple__dGN8y0EmZCyHJuMZprBENw tyTuple__dGN8y0EmZCyHJuMZprBENw;
typedef struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw tyTuple__xYhUhS7X82rKTqbT9bRfCnw;
typedef struct tyObject_TFileInfo__PCIONCsQP5N3d2CZ5ERsGg tyObject_TFileInfo__PCIONCsQP5N3d2CZ5ERsGg;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Cfile__qYriQG53x4WbtSdCuV7Piw tyObject_Cfile__qYriQG53x4WbtSdCuV7Piw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw {
	NI id;
	NimStringV2 s;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* next;
	NI h;
};
struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA {
	NI32 module;
	NI32 item;
};
typedef NU8 tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ;
typedef NU16 tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ;
typedef NU64 tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw;
typedef NU32 tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg;
typedef NU8 tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw;
typedef NU8 tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ;
typedef NU16 tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ;
struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA {
	tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw k;
	tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ storage;
	tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* lode;
	NimStringV2 snippet;
};
struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ {
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA itemId;
	tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ kind;
union{
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* gcUnsafetyReason;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* transformedBody;
} _kind_1;
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* guard;
	NI bitsize;
	NI alignment;
} _kind_2;
};
	tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ magic;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* name;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* ownerField;
	tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* ast;
	tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg options;
	NI position;
	NI32 offset;
	NI32 disamb;
	tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA loc;
	tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA* annex;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* constraint;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* instantiatedFrom;
};
struct tySequence__14eaenldYvaMipHPmyNPjQ {
  NI len; tySequence__14eaenldYvaMipHPmyNPjQ_Content* p;
};
struct tyObject_CountTable__wjTlk1kHyVlLDhtpJTNang {
	tySequence__14eaenldYvaMipHPmyNPjQ data;
	NI counter;
	NIM_BOOL isSorted;
};
struct tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg {
	NI32 module;
	NI32 symId;
	NI32 typeId_0;
	NIM_BOOL sealed;
	tyObject_CountTable__wjTlk1kHyVlLDhtpJTNang disambTable;
};
typedef NU8 tyEnum_TBackend__OSqsYcxbmrETlmXiqoYW6g;
typedef NU8 tyEnum_TSystemCPU__Rso9bNBb6Pesx9a03T4YvXAA;
typedef NU8 tyEnum_TSystemOS__B0ZwW9cGEoq4o9bM9aF9aq27XA;
struct tyObject_Target__ZiMt9cLer9ck76lZ8l1TCLfw {
	tyEnum_TSystemCPU__Rso9bNBb6Pesx9a03T4YvXAA targetCPU;
	tyEnum_TSystemCPU__Rso9bNBb6Pesx9a03T4YvXAA hostCPU;
	tyEnum_TSystemOS__B0ZwW9cGEoq4o9bM9aF9aq27XA targetOS;
	tyEnum_TSystemOS__B0ZwW9cGEoq4o9bM9aF9aq27XA hostOS;
	NI intSize;
	NI floatSize;
	NI ptrSize;
	NimStringV2 tnl;
};
typedef NU64 tySet_tyEnum_TGlobalOption__iK79b9b4srcAOQr9aY9bm4SawQ;
typedef NU8 tySet_tyEnum_TErrorOutput__Fb0Tpb4nhoVPU3gFg8Wutg;
struct tySequence__ShJEiHHo1aNtCljYBp41CQ {
  NI len; tySequence__ShJEiHHo1aNtCljYBp41CQ_Content* p;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw {
  NI len; tySequence__7lEisrXlQEzwtUKW5pzRCw_Content* p;
};
struct tyObject_Table__TfSbAADD2D1hZlKgnmloOA {
	tySequence__7lEisrXlQEzwtUKW5pzRCw data;
	NI counter;
};
struct tySequence__5bkr9aLWkPbIt1PGy0PRQ4g {
  NI len; tySequence__5bkr9aLWkPbIt1PGy0PRQ4g_Content* p;
};
struct tyObject_MsgConfig__oyuZDuFkUoO2ITWE0IRsuQ {
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ trackPos;
	NIM_BOOL trackPosAttached;
	tySet_tyEnum_TErrorOutput__Fb0Tpb4nhoVPU3gFg8Wutg errorOutputs;
	tySequence__ShJEiHHo1aNtCljYBp41CQ msgContext;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ lastError;
	tyObject_Table__TfSbAADD2D1hZlKgnmloOA filenameToIndexTbl;
	tySequence__5bkr9aLWkPbIt1PGy0PRQ4g fileInfos;
	NI32 systemFileIdx;
};
typedef NU8 tyEnum_FilenameOption__si9cLCGlyHHTxkcdug5PK1w;
typedef NU8 tyEnum_Command__ux5ZYcz1liJoGVeMNnQlNA;
typedef NU8 tyEnum_TGCMode__McCkKH9a7OfCczqA6wyZesQ;
typedef NU8 tyEnum_ExceptionSystem__WQbp9aeq4u37xIVSpJ5oJqQ;
typedef NU8 tyEnum_SymbolFilesOption__eJWjRN1zic6WVBnsnUvGig;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__dcTrLn4kfefktxRri5vkXw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
typedef NU32 tySet_tyEnum_Feature__XN19al371OTpj0brEFc9bFog;
typedef NU8 tySet_tyEnum_LegacyFeature__ToQX7X0QqacrS9a9b69c3tdbA;
typedef NU8 tyEnum_IdeCmd__SS1kiW9b1rtzZAguF61iVcA;
typedef NU8 tyEnum_TSystemCC__sSNQ475JGU9cHkcB9a07E0zQ;
typedef NU8 tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg[13];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyEnum_StdOrrKind__9aHDNYchPVd5a5c4lhqaVdg;
struct tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg {
  NI len; tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_SuggestcolonObjectType___cw8T4l0P9bfRcw9aAuJQpe0A* result_p0, void* ClE_0);
void* ClE_0;
} tyProc__ZW1kIYTYDKsUHVRB5Rx1MA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringV2 output_p0, void* ClE_0);
void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
typedef NU8 tyEnum_Severity__bnTaw0gxq9a9c5ypfdzREjAg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* config_p0, tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info_p1, NimStringV2 msg_p2, tyEnum_Severity__bnTaw0gxq9a9c5ypfdzREjAg severity_p3, void* ClE_0);
void* ClE_0;
} tyProc__UvCrLCoWDkGOBCPaqWGo2Q;
struct tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w {
	tyEnum_TBackend__OSqsYcxbmrETlmXiqoYW6g backend;
	tyObject_Target__ZiMt9cLer9ck76lZ8l1TCLfw target;
	NI linesCompiled;
	tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg options;
	tySet_tyEnum_TGlobalOption__iK79b9b4srcAOQr9aY9bm4SawQ globalOptions;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* macrosToExpand;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* arcToExpand;
	tyObject_MsgConfig__oyuZDuFkUoO2ITWE0IRsuQ m;
	tyEnum_FilenameOption__si9cLCGlyHHTxkcdug5PK1w filenameOption;
	NimStringV2 unitSep;
	NI evalTemplateCounter;
	NI evalMacroCounter;
	NI8 exitcode;
	tyEnum_Command__ux5ZYcz1liJoGVeMNnQlNA cmd;
	NimStringV2 cmdInput;
	NIM_BOOL projectIsCmd;
	NIM_BOOL implicitCmd;
	tyEnum_TGCMode__McCkKH9a7OfCczqA6wyZesQ selectedGC;
	tyEnum_ExceptionSystem__WQbp9aeq4u37xIVSpJ5oJqQ exc;
	NIM_BOOL hintProcessingDots;
	NI verbosity;
	NI numberOfProcessors;
	NF lastCmdTime;
	tyEnum_SymbolFilesOption__eJWjRN1zic6WVBnsnUvGig symbolFiles;
	NI spellSuggestMax;
	tyObject_HashSet__dcTrLn4kfefktxRri5vkXw cppDefines;
	NimStringV2 headerFile;
	NimStringV2 nimbasePattern;
	tySet_tyEnum_Feature__XN19al371OTpj0brEFc9bFog features;
	tySet_tyEnum_LegacyFeature__ToQX7X0QqacrS9a9b69c3tdbA legacyFeatures;
	NimStringV2 arguments;
	tyEnum_IdeCmd__SS1kiW9b1rtzZAguF61iVcA ideCmd;
	tyEnum_TSystemCC__sSNQ475JGU9cHkcB9a07E0zQ cCompiler;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg modifiedyNotes;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg cmdlineNotes;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg foreignPackageNotes;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg notes;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg warningAsErrors;
	tySet_tyEnum_TMsgKind__aaCH7Af6rSWIlwxJGbZLeg mainPackageNotes;
	NI mainPackageId;
	NI errorCounter;
	NI hintCounter;
	NI warnCounter;
	NI errorMax;
	NI maxLoopIterationsVM;
	NI maxCallDepthVM;
	NIM_BOOL isVmTrace;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* configVars;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* symbols;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* packageCache;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimblePaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ searchPaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lazyPaths;
	NimStringV2 outFile;
	NimStringV2 outDir;
	NimStringV2 jsonBuildFile;
	NimStringV2 prefixDir;
	NimStringV2 libpath;
	NimStringV2 nimcacheDir;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* dllOverrides;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* moduleOverrides;
	tyObject_StringTableObj__ovsFdjKjj28I9a0NwSpMi7w* cfileSpecificOptions;
	NimStringV2 projectName;
	NimStringV2 projectPath;
	NimStringV2 projectFull;
	NIM_BOOL projectIsStdin;
	NimStringV2 stdinFile;
	tySet_tyEnum_StdOrrKind__9aHDNYchPVd5a5c4lhqaVdg lastMsgWasDot;
	NI32 projectMainIdx;
	NI32 projectMainIdx2;
	NimStringV2 command;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ commandArgs;
	NimStringV2 commandLine;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ extraCmds;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitImports;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitIncludes;
	NimStringV2 docSeeSrcUrl;
	NimStringV2 docRoot;
	NimStringV2 docCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ configFiles;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cIncludes;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLinkedLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ externalToLink;
	NimStringV2 linkOptionsCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ compileOptionsCmd;
	NimStringV2 linkOptions;
	NimStringV2 compileOptions;
	NimStringV2 cCompilerPath;
	tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg toCompile;
	tyProc__ZW1kIYTYDKsUHVRB5Rx1MA suggestionResultHook;
	NI suggestVersion;
	NI suggestMaxResults;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ lastLineInfo;
	tyProc__k2HFjxisIgDALbEUFojxaQ writelnHook;
	tyProc__UvCrLCoWDkGOBCPaqWGo2Q structuredErrorHook;
	NimStringV2 cppCustomNamespace;
	NimStringV2 nimMainPrefix;
	tyObject_ProfileDatacolonObjectType___JmSf22j9cfqvwddpMvl3kMQ* vmProfileData;
	NIM_BOOL expandProgress;
	NI expandLevels;
	NimStringV2 expandNodeResult;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ expandPosition;
	NimStringV2 currentConfigDir;
	NI clientProcessId;
};
struct tyTuple__m0WV9c6zw9bvNqarbA9c7ZT4g {
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* Field0;
	NI Field1;
};
struct tySequence__14eaenldYvaMipHPmyNPjQ_Content { NI cap; tyTuple__m0WV9c6zw9bvNqarbA9c7ZT4g data[SEQ_DECL_SIZE]; };
struct tyTuple__dGN8y0EmZCyHJuMZprBENw {
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ Field0;
	NimStringV2 Field1;
};
struct tySequence__ShJEiHHo1aNtCljYBp41CQ_Content { NI cap; tyTuple__dGN8y0EmZCyHJuMZprBENw data[SEQ_DECL_SIZE]; };
struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw {
	NI Field0;
	NimStringV2 Field1;
	NI32 Field2;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content { NI cap; tyTuple__xYhUhS7X82rKTqbT9bRfCnw data[SEQ_DECL_SIZE]; };
struct tyObject_TFileInfo__PCIONCsQP5N3d2CZ5ERsGg {
	NimStringV2 fullPath;
	NimStringV2 projPath;
	NimStringV2 shortName;
	NimStringV2 quotedName;
	NimStringV2 quotedFullName;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lines;
	NimStringV2 dirtyFile;
	NimStringV2 hash;
	NIM_BOOL dirty;
};
struct tySequence__5bkr9aLWkPbIt1PGy0PRQ4g_Content { NI cap; tyObject_TFileInfo__PCIONCsQP5N3d2CZ5ERsGg data[SEQ_DECL_SIZE]; };
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
typedef NU8 tySet_tyEnum_CfileFlag__YZfAvYxNcIQufOEcyrNxvA;
struct tyObject_Cfile__qYriQG53x4WbtSdCuV7Piw {
	NimStringV2 nimname;
	NimStringV2 cname;
	NimStringV2 obj;
	tySet_tyEnum_CfileFlag__YZfAvYxNcIQufOEcyrNxvA flags;
	NimStringV2 customArgs;
};
struct tySequence__7OZ9bT4vZ9cZSRgByCPkLTqg_Content { NI cap; tyObject_Cfile__qYriQG53x4WbtSdCuV7Piw data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toFullPath__msgs_u624)(tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* conf_p0, NI32 fileIdx_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw*, getIdent__idents_u208)(tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ* ic_p0, NimStringV2 identifier_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg, splitFile__pathutils_u39)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ, newLineInfo__msgs_u419)(NI32 fileInfoIdx_p0, NI line_p1, NI col_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getPackageName__options_u3732)(tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* conf_p0, NimStringV2 path_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, newSym__ast_u4220)(tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ symKind_p0, tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* name_p1, tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg* idgen_p2, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* owner_p3, tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info_p4, tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg options_p5);
N_LIB_PRIVATE N_NIMCALL(tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg*, idGeneratorForPackage__ast_u3125)(NI32 nextIdWillBe_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3103)(tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___idents_u157)(tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2629)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pathutils_u73)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg dest_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4480)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, getPackageId__packages_u75)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, getPackageSymbol__packages_u18)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u242)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u4598)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ** dest_p0, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ast_u4604)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ** dest_p0, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* src_p1);
static N_INLINE(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, owner__ast_u6283)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u4595)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* dest_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, repr__packages_u37)(tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static const struct {
  NI cap; NIM_CHAR data[70+1];
} TM__eq6wv74ZVv4jzzfF1HSeLw_2 = { 70 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim(38, 3) `sym != nil` " };
static const NimStringV2 TM__eq6wv74ZVv4jzzfF1HSeLw_3 = {70, (NimStrPayload*)&TM__eq6wv74ZVv4jzzfF1HSeLw_2};
static const struct {
  NI cap; NIM_CHAR data[73+1];
} TM__eq6wv74ZVv4jzzfF1HSeLw_4 = { 73 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim(42, 5) `result != nil` " };
static const NimStringV2 TM__eq6wv74ZVv4jzzfF1HSeLw_5 = {73, (NimStrPayload*)&TM__eq6wv74ZVv4jzzfF1HSeLw_4};
extern NIM_BOOL nimInErrorMode__system_u4262;
extern TFrame* framePtr__system_u2667;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4262);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4480();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, getPackage__packages_u8)(tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* conf_p0, tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ* cache_p1, NI32 fileIdx_p2) {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* result;
	NimStringV2 filename_1;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* name_1;
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
	NimStringV2 pkgName_1;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* pkgIdent_1;
	tyObject_IdGeneratorcolonObjectType___PoMCJ5hAWC6V9btoMgk4Ieg* colontmpD__2;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info_1;
	tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("getPackage", "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	filename_1.len = 0; filename_1.p = NIM_NIL;
	name_1 = NIM_NIL;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
	pkgName_1.len = 0; pkgName_1.p = NIM_NIL;
	pkgIdent_1 = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(29, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");	filename_1 = toFullPath__msgs_u624(conf_p0, fileIdx_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(30);	colontmpD_ = splitFile__pathutils_u39(filename_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	name_1 = getIdent__idents_u208(cache_p1, colontmpD_.Field1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(31);	info_1 = newLineInfo__msgs_u419(fileIdx_p2, ((NI)1), ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(32);	pkgName_1 = getPackageName__options_u3732(conf_p0, filename_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(33);	pkgIdent_1 = getIdent__idents_u208(cache_p1, pkgName_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(23);	nimln_(34);	colontmpD__2 = idGeneratorForPackage__ast_u3125(fileIdx_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = 0;
	result = newSym__ast_u4220(((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)24), pkgIdent_1, colontmpD__2, ((tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*) NIM_NIL), info_1, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(972, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		eqdestroy___ast_u3103(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(71, "/Users/svacchanda/Dev/nimv2/compiler/idents.nim");		eqdestroy___idents_u157(pkgIdent_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		eqdestroy___system_u2629(pkgName_1);
		nimlf_(34, "/Users/svacchanda/Dev/nimv2/compiler/pathutils.nim");		eqdestroy___pathutils_u73(colontmpD_);
		nimlf_(71, "/Users/svacchanda/Dev/nimv2/compiler/idents.nim");		eqdestroy___idents_u157(name_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		eqdestroy___system_u2629(filename_1);
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, owner__ast_u6283)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* s_p0) {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* result;
NIM_BOOL* nimErr_;
	nimfr_("owner", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(1222, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	eqcopy___ast_u4598(&result, (*s_p0).ownerField);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU32)(((NU) (a_p0))) + (NU32)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__eq6wv74ZVv4jzzfF1HSeLw_6;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)2147483647)){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)2147483647)); goto BeforeRet_;
		}
		copyMem__system_u1728(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__eq6wv74ZVv4jzzfF1HSeLw_6)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__eq6wv74ZVv4jzzfF1HSeLw_6);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*, getPackageSymbol__packages_u18)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p0) {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* result;
NIM_BOOL* nimErr_;
	nimfr_("getPackageSymbol", "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(38, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");	{
		if (!!(!((sym_p0 == ((tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*) NIM_NIL))))) goto LA3_;
		failedAssertImpl__stdZassertions_u242(TM__eq6wv74ZVv4jzzfF1HSeLw_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimlf_(1222, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	eqcopy___ast_u4598(&result, sym_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		nimlf_(40, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");		while (1) {
			tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* T7_;
			if (!!(((*result).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)24)))) goto LA6;
			nimlf_(1222, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");			nimlf_(41, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");			T7_ = NIM_NIL;
			T7_ = owner__ast_u6283(result);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___ast_u4595(T7_); goto BeforeRet_;}
			nimlf_(1222, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");			eqsink___ast_u4604(&result, T7_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(42, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");			{
				NimStringV2 colontmpD_;
				NimStringV2 colontmpD__2;
				NimStringV2 T12_;
				if (!!(!((result == ((tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*) NIM_NIL))))) goto LA10_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				T12_.len = 0; T12_.p = NIM_NIL;
				colontmpD_ = repr__packages_u37((*sym_p0).info);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T12_ = rawNewString(colontmpD_.len + 73);
appendString((&T12_), TM__eq6wv74ZVv4jzzfF1HSeLw_5);
appendString((&T12_), colontmpD_);
				colontmpD__2 = T12_;
				failedAssertImpl__stdZassertions_u242(colontmpD__2);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD__2);
				eqdestroy___system_u2629(colontmpD_);
			}
LA10_: ;
		} LA6: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getPackageId__packages_u75)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p0) {
	NI result;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* colontmpD_;
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA xX60gensym9__1;
	NI TM__eq6wv74ZVv4jzzfF1HSeLw_7;
NIM_BOOL* nimErr_;
	nimfr_("getPackageId", "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	colontmpD_ = NIM_NIL;
	nimlf_(45, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");	nimlf_(954, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	nimlf_(46, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");	colontmpD_ = getPackageSymbol__packages_u18(sym_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	xX60gensym9__1 = (*colontmpD_).itemId;
	nimlf_(955, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	if (nimAddInt((NI)((NU32)(((NI) (xX60gensym9__1.module))) << (NU32)(((NI)20))), ((NI) (xX60gensym9__1.item)), &TM__eq6wv74ZVv4jzzfF1HSeLw_7)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__eq6wv74ZVv4jzzfF1HSeLw_7);
	nimln_(1222);	eqdestroy___ast_u4595(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, belongsToProjectPackage__packages_u85)(tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* conf_p0, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("belongsToProjectPackage", "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(49, "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");	nimln_(53);	T1_ = (NI)0;
	T1_ = getPackageId__packages_u75(sym_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((*conf_p0).mainPackageId == T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, belongsToProjectPackageMaybeNil__packages_u89)(tyObject_ConfigRefcolonObjectType___X9asap8dM7VungPayvbl9b1w* conf_p0, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym_p1) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T3_;
NIM_BOOL* nimErr_;
	nimfr_("belongsToProjectPackageMaybeNil", "/Users/svacchanda/Dev/nimv2/compiler/packages.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(56);	nimln_(61);	T1_ = (NIM_BOOL)0;
	T1_ = !((sym_p1 == ((tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ*) NIM_NIL)));
	if (!(T1_)) goto LA2_;
	T3_ = (NI)0;
	T3_ = getPackageId__packages_u75(sym_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_ = ((*conf_p0).mainPackageId == T3_);
LA2_: ;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
