/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg;
typedef struct tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg;
typedef struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ;
typedef struct tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw;
typedef struct tySequence__aoeG9bufSTIRNZegac1FEcg tySequence__aoeG9bufSTIRNZegac1FEcg;
typedef struct tySequence__aoeG9bufSTIRNZegac1FEcg_Content tySequence__aoeG9bufSTIRNZegac1FEcg_Content;
typedef struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA;
typedef struct tySequence__gpNDf0KkXfAoquVppKHCZA tySequence__gpNDf0KkXfAoquVppKHCZA;
typedef struct tySequence__gpNDf0KkXfAoquVppKHCZA_Content tySequence__gpNDf0KkXfAoquVppKHCZA_Content;
typedef struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA;
typedef struct tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q;
typedef struct tyObject_TrunkcolonObjectType___EmGe8hcg6AsRIlZP9cZUy2g tyObject_TrunkcolonObjectType___EmGe8hcg6AsRIlZP9cZUy2g;
typedef struct tySequence__9bOP3XKJO9cduo72I9cSJSTGQ tySequence__9bOP3XKJO9cduo72I9cSJSTGQ;
typedef struct tySequence__9bOP3XKJO9cduo72I9cSJSTGQ_Content tySequence__9bOP3XKJO9cduo72I9cSJSTGQ_Content;
typedef struct tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA;
struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU32 tySet_tyEnum_TNodeFlag__FhgPNE64ZbubRzUYw37NSA;
typedef NU8 tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__aoeG9bufSTIRNZegac1FEcg {
  NI len; tySequence__aoeG9bufSTIRNZegac1FEcg_Content* p;
};
struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typField;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info;
	tySet_tyEnum_TNodeFlag__FhgPNE64ZbubRzUYw37NSA flags;
	tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ kind;
union{
	struct {
	NI64 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym;
} _kind_4;
	struct {
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* ident;
} _kind_5;
	struct {
	tySequence__aoeG9bufSTIRNZegac1FEcg sons;
} _kind_6;
};
};
typedef NU8 tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ[21];
struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA {
	NI32 module;
	NI32 item;
};
typedef NU8 tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ;
typedef NU8 tyEnum_TCallingConvention__XXIh8WHDiwZFWOB6z9b9cQhw;
typedef NU64 tySet_tyEnum_TTypeFlag__GJmtY1UKY65JJNT2LxCtow;
struct tySequence__gpNDf0KkXfAoquVppKHCZA {
  NI len; tySequence__gpNDf0KkXfAoquVppKHCZA_Content* p;
};
typedef NU8 tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw;
typedef NU8 tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ;
typedef NU16 tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ;
struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA {
	tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw k;
	tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ storage;
	tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* lode;
	NimStringV2 snippet;
};
struct tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg {
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA itemId;
	tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ kind;
	tyEnum_TCallingConvention__XXIh8WHDiwZFWOB6z9b9cQhw callConv;
	tySet_tyEnum_TTypeFlag__GJmtY1UKY65JJNT2LxCtow flags;
	tySequence__gpNDf0KkXfAoquVppKHCZA sons;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* ownerField;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym;
	NI64 size;
	NI16 align;
	NI16 paddingAtEnd;
	tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA loc;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typeInst;
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA uniqueId;
};
typedef NU8 tyEnum_TTypeFlag__GJmtY1UKY65JJNT2LxCtow;
struct tySequence__9bOP3XKJO9cduo72I9cSJSTGQ {
  NI len; tySequence__9bOP3XKJO9cduo72I9cSJSTGQ_Content* p;
};
typedef NI tyArray__emiAJ8okywrJw7ZHLzlXbQ[34];
struct tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q {
	NI elems;
	NI counter;
	NI max;
	tyObject_TrunkcolonObjectType___EmGe8hcg6AsRIlZP9cZUy2g* head;
	tySequence__9bOP3XKJO9cduo72I9cSJSTGQ data;
	tyArray__emiAJ8okywrJw7ZHLzlXbQ a;
};
typedef NU8 tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA;
typedef NU8 tySet_tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ[9];
typedef NU8 tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ;
typedef NU16 tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ;
typedef NU64 tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw;
typedef NU32 tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg;
struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ {
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA itemId;
	tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ kind;
union{
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* gcUnsafetyReason;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* transformedBody;
} _kind_1;
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* guard;
	NI bitsize;
	NI alignment;
} _kind_2;
};
	tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ magic;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* name;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* ownerField;
	tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* ast;
	tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg options;
	NI position;
	NI32 offset;
	NI32 disamb;
	tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA loc;
	tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA* annex;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* constraint;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* instantiatedFrom;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__6w2Lz2rbvvwcK9bKhpUY8Lg) (tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
typedef NU8 tyEnum_TDistinctCompare__bGjBWtLv0FsENHY1SboCdg;
typedef NU16 tySet_tyEnum_TTypeCmpFlag__yS5h5n9agTW21qcU4sqaLWw;
struct tySequence__aoeG9bufSTIRNZegac1FEcg_Content { NI cap; tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* data[SEQ_DECL_SIZE]; };
struct tySequence__gpNDf0KkXfAoquVppKHCZA_Content { NI cap; tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* data[SEQ_DECL_SIZE]; };
struct tySequence__9bOP3XKJO9cduo72I9cSJSTGQ_Content { NI cap; tyObject_TrunkcolonObjectType___EmGe8hcg6AsRIlZP9cZUy2g* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsTyRef__types_u597)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___nodekinds_u168)(tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NI, len__ast_u3197)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4479)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkIsolate__isolation95check_u224)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3390)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** dest_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* src_p1);
static N_INLINE(NIM_BOOL, isCompileTimeOnly__types_u3711)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsDangerousRef__isolation95check_u202)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, initIntSet__pureZcollectionsZintsets_u608)(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* Result);
N_LIB_PRIVATE N_NIMCALL(void, initPackedSet__pureZcollectionsZintsets_u37)(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* Result);
N_LIB_PRIVATE N_NIMCALL(tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA, containsDangerousRefAux__isolation95check_u86)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsOrIncl__astyaml_u240)(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* s_p0, NI key_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, baseClass__ast_u5371)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, skipTypes__ast_u5402)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0, tySet_tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ kinds_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3387)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA, containsDangerousRefAux__isolation95check_u89)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u242)(NimStringV2 msg_p0);
static N_INLINE(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg*, lastSon__ast_u5231)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3264)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** dest_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* src_p1);
static N_INLINE(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg**, X5BX5D___ast_u5234)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** s_p0, NI s_p0Len_0, NI i_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3261)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* dest_p0);
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, skipModifier__ast_u5361)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0);
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg**, X5BX5D___ast_u5304)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, elementType__ast_u5354)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZcollectionsZintsets_u230)(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAlias__isolation95check_u210)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* ret_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValueOnlyType__isolation95check_u69)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, searchTypeFor__types_u429)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0, tyProc__6w2Lz2rbvvwcK9bKhpUY8Lg predicate_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, wrap__isolation95check_u72)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAlias__isolation95check_u6)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* ret_p1, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, compareTypes__types_u2814)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* x_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* y_p1, tyEnum_TDistinctCompare__bGjBWtLv0FsENHY1SboCdg cmp_p2, tySet_tyEnum_TTypeCmpFlag__yS5h5n9agTW21qcU4sqaLWw flags_p3);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isFinal__types_u778)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAliasN__isolation95check_u10)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsVariable__isolation95check_u216)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
static N_INLINE(NI, safeLen__ast_u3204)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
static NIM_CONST tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ TM__VSC6iKzck1XeooN9aLTqhXA_2 = {
0xec, 0xff, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__VSC6iKzck1XeooN9aLTqhXA_3 = { 62 | NIM_STRLIT_FLAG, "field \'sons\' is not accessible for type \'TNode\' using \'kind = " };
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_4 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_5 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_6 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_7 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static NIM_CONST tySet_tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ TM__VSC6iKzck1XeooN9aLTqhXA_9 = {
0x10, 0x09, 0xe0, 0x00, 0x00, 0xe0, 0x80, 0x00,
0x00}
;
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_10 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_12 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const struct {
  NI cap; NIM_CHAR data[86+1];
} TM__VSC6iKzck1XeooN9aLTqhXA_13 = { 86 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim(93, 11) `n[0].kind == nkSym` " };
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_14 = {86, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_13};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_15 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_16 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_18 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_19 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static NIM_CONST tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ TM__VSC6iKzck1XeooN9aLTqhXA_21 = {
0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[61+1];
} TM__VSC6iKzck1XeooN9aLTqhXA_22 = { 61 | NIM_STRLIT_FLAG, "field \'sym\' is not accessible for type \'TNode\' using \'kind = " };
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_23 = {61, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_22};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_27 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_29 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const struct {
  NI cap; NIM_CHAR data[86+1];
} TM__VSC6iKzck1XeooN9aLTqhXA_30 = { 86 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim(31, 11) `n[0].kind == nkSym` " };
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_31 = {86, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_30};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_32 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_33 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_34 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_36 = {61, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_22};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_38 = {61, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_22};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_39 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_41 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_43 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_45 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_47 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_49 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_51 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_52 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_53 = {62, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_3};
static const NimStringV2 TM__VSC6iKzck1XeooN9aLTqhXA_55 = {61, (NimStrPayload*)&TM__VSC6iKzck1XeooN9aLTqhXA_22};
extern TFrame* framePtr__system_u2667;
extern NIM_BOOL nimInErrorMode__system_u4261;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4479();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
static N_INLINE(NI, len__ast_u3197)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NI result;
	NI T1_;
	nimfr_("len", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{	nimlf_(1008, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 	{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_5, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
	}
	T1_ = (*n_p0)._kind_6.sons.len;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isCompileTimeOnly__types_u3711)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0) {
	NIM_BOOL result;
	nimfr_("isCompileTimeOnly", "/Users/svacchanda/Dev/nimv2/compiler/types.nim");
	nimlf_(1689, "/Users/svacchanda/Dev/nimv2/compiler/types.nim");	result = ((*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)8) || (*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)60) || (*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)12));
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4261);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, initIntSet__pureZcollectionsZintsets_u608)(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* Result) {
NIM_BOOL* nimErr_;
	nimfr_("initIntSet", "/opt/local/lib/nim/lib/pure/collections/intsets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q));
	initPackedSet__pureZcollectionsZintsets_u37(Result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, baseClass__ast_u5371)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0) {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* result;
NIM_BOOL* nimErr_;
	nimfr_("baseClass", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(934, "/opt/local/lib/nim/lib/system.nim");	if (((NI)0) < 0 || ((NI)0) >= (*n_p0).sons.len){ raiseIndexError2(((NI)0),(*n_p0).sons.len-1); goto BeforeRet_;
	}
	eqcopy___ast_u3390(&result, (*n_p0).sons.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg**, X5BX5D___ast_u5234)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** s_p0, NI s_p0Len_0, NI i_p1) {
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** result;
	NI TM__VSC6iKzck1XeooN9aLTqhXA_17;
	nimfr_("[]", "/opt/local/lib/nim/lib/system/indices.nim");
{	result = (tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg**)0;
	nimlf_(30, "/opt/local/lib/nim/lib/system/indices.nim");	if (nimSubInt(s_p0Len_0, i_p1, &TM__VSC6iKzck1XeooN9aLTqhXA_17)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_17) < 0 || (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_17) >= s_p0Len_0){ raiseIndexError2((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_17),s_p0Len_0-1); goto BeforeRet_;
	}
	result = &s_p0[(NI)(TM__VSC6iKzck1XeooN9aLTqhXA_17)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg*, lastSon__ast_u5231)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* result;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** T1_;
NIM_BOOL* nimErr_;
	nimfr_("lastSon", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	nimln_(1329);	if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 	{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_18, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
	}
	T1_ = (tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg**)0;
	T1_ = X5BX5D___ast_u5234((((*n_p0)._kind_6.sons).p) ? ((*n_p0)._kind_6.sons.p->data) : NIM_NIL, (*n_p0)._kind_6.sons.len, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(1023);	eqcopy___ast_u3264(&result, (*T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA, containsDangerousRefAux__isolation95check_u89)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p1) {
	tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA result;
NIM_BOOL oldNimErrFin22_;
NIM_BOOL* nimErr_;
	nimfr_("containsDangerousRefAux", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(86, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");	result = ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0);
	nimln_(87);	switch ((*n_p0).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)138):
	{
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(89, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			colontmp_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_2 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NI TM__VSC6iKzck1XeooN9aLTqhXA_11;
					if (!(i_2 < colontmp_)) goto LA4;
					nimlf_(89, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");					i_1 = i_2;
					nimln_(90);					if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_10, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
					}
					result = containsDangerousRefAux__isolation95check_u89((*n_p0)._kind_6.sons.p->data[i_1], marker_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(91);					{
						if (!(result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2))) goto LA7_;
						goto BeforeRet_;
					}
LA7_: ;
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_11)) { raiseOverflow(); goto BeforeRet_;
					};
					i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_11);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)139):
	{
		nimlf_(93, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		{
			if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_12, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
			}
			if (!!(((*(*n_p0)._kind_6.sons.p->data[((NI)0)]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3)))) goto LA12_;
			failedAssertImpl__stdZassertions_u242(TM__VSC6iKzck1XeooN9aLTqhXA_14);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA12_: ;
		nimln_(94);		if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_15, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
		}
		result = containsDangerousRefAux__isolation95check_u89((*n_p0)._kind_6.sons.p->data[((NI)0)], marker_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(95);		{
			if (!(result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2))) goto LA16_;
			goto BeforeRet_;
		}
LA16_: ;
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(96, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			colontmp__2 = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_4 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NI TM__VSC6iKzck1XeooN9aLTqhXA_20;
					if (!(i_4 < colontmp__2)) goto LA20;
					nimlf_(96, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");					i_3 = i_4;
					nimln_(97);					if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_16, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
					}
					if (i_3 < 0 || i_3 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
					}
					switch ((*(*n_p0)._kind_6.sons.p->data[i_3]).kind) {
					case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)85):
					case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)88):
					{
						tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* colontmpD_;
						colontmpD_ = NIM_NIL;
						nimln_(99);						if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_19, dollar___nodekinds_u168((*n_p0).kind)); goto LA22_;
						}
						if (i_3 < 0 || i_3 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p0)._kind_6.sons.len-1); goto LA22_;
						}
						colontmpD_ = lastSon__ast_u5231((*n_p0)._kind_6.sons.p->data[i_3]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						result = containsDangerousRefAux__isolation95check_u89(colontmpD_, marker_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						nimln_(100);						{
							if (!(result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2))) goto LA25_;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							goto BeforeRet_;
						}
LA25_: ;
						{
							LA22_:;
						}
						{
							oldNimErrFin22_ = *nimErr_; *nimErr_ = NIM_FALSE;
							eqdestroy___ast_u3261(colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							*nimErr_ = oldNimErrFin22_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					break;
					default:
					{
					}
					break;
					}
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_4, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_20)) { raiseOverflow(); goto BeforeRet_;
					};
					i_4 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_20);
				} LA20: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
	{
		nimlf_(103, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		if (!(((TM__VSC6iKzck1XeooN9aLTqhXA_21[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_23, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		result = containsDangerousRefAux__isolation95check_u86((*(*n_p0)._kind_4.sym).typ, marker_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg**, X5BX5D___ast_u5304)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** s_p0, NI s_p0Len_0, NI i_p1) {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** result;
	NI TM__VSC6iKzck1XeooN9aLTqhXA_24;
	nimfr_("[]", "/opt/local/lib/nim/lib/system/indices.nim");
{	result = (tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg**)0;
	nimlf_(30, "/opt/local/lib/nim/lib/system/indices.nim");	if (nimSubInt(s_p0Len_0, i_p1, &TM__VSC6iKzck1XeooN9aLTqhXA_24)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_24) < 0 || (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_24) >= s_p0Len_0){ raiseIndexError2((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_24),s_p0Len_0-1); goto BeforeRet_;
	}
	result = &s_p0[(NI)(TM__VSC6iKzck1XeooN9aLTqhXA_24)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, skipModifier__ast_u5361)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0) {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* result;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** T1_;
NIM_BOOL* nimErr_;
	nimfr_("skipModifier", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(934, "/opt/local/lib/nim/lib/system.nim");	nimlf_(1347, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	T1_ = (tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg**)0;
	T1_ = X5BX5D___ast_u5304((((*n_p0).sons).p) ? ((*n_p0).sons.p->data) : NIM_NIL, (*n_p0).sons.len, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/opt/local/lib/nim/lib/system.nim");	eqcopy___ast_u3390(&result, (*T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*, elementType__ast_u5354)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* n_p0) {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* result;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** T1_;
NIM_BOOL* nimErr_;
	nimfr_("elementType", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(934);	nimlf_(1346, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	T1_ = (tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg**)0;
	T1_ = X5BX5D___ast_u5304((((*n_p0).sons).p) ? ((*n_p0).sons.p->data) : NIM_NIL, (*n_p0).sons.len, ((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(934, "/opt/local/lib/nim/lib/system.nim");	eqcopy___ast_u3390(&result, (*T1_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA, containsDangerousRefAux__isolation95check_u86)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p1) {
	tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA result;
NIM_BOOL oldNimErrFin32_;
NIM_BOOL oldNimErrFin27_;
NIM_BOOL oldNimErrFin42_;
NIM_BOOL oldNimErrFin46_;
NIM_BOOL oldNimErrFin51_;
NIM_BOOL* nimErr_;
	nimfr_("containsDangerousRefAux", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(107, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");	result = ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0);
	nimln_(108);	{
		if (!(t_p0 == ((tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(109);	{
		tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA xX60gensym20__1;
		NI TM__VSC6iKzck1XeooN9aLTqhXA_8;
		NIM_BOOL T7_;
		nimlf_(954, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		xX60gensym20__1 = (*t_p0).itemId;
		nimlf_(109, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		nimlf_(955, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		if (nimAddInt((NI)((NU32)(((NI) (xX60gensym20__1.module))) << (NU32)(((NI)20))), ((NI) (xX60gensym20__1.item)), &TM__VSC6iKzck1XeooN9aLTqhXA_8)) { raiseOverflow(); goto BeforeRet_;
		};
		nimlf_(109, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		T7_ = (NIM_BOOL)0;
		T7_ = containsOrIncl__astyaml_u240(marker_p1, (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_8));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T7_) goto LA8_;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(111);	{
		NIM_BOOL T12_;
		NIM_BOOL T14_;
		T12_ = (NIM_BOOL)0;
		T12_ = ((*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)22));
		if (T12_) goto LA13_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)25));
		if (!(T14_)) goto LA15_;
		T14_ = ((*t_p0).callConv == ((tyEnum_TCallingConvention__XXIh8WHDiwZFWOB6z9b9cQhw)9));
LA15_: ;
		T12_ = T14_;
LA13_: ;
		if (!T12_) goto LA16_;
		nimln_(112);		result = ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2);
	}
	goto LA10_;
LA16_: ;
	{
		nimln_(113);		if (!(((*t_p0).flags &((NU64)1<<((NU)((((tyEnum_TTypeFlag__GJmtY1UKY65JJNT2LxCtow)46)))&63U)))!=0)) goto LA19_;
		nimln_(114);		result = ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)1);
	}
	goto LA10_;
LA19_: ;
	{
		nimln_(117);		result = ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0);
	}
LA10_: ;
	nimln_(119);	{
		if (!!((result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0)))) goto LA24_;
		goto BeforeRet_;
	}
LA24_: ;
	nimln_(120);	switch ((*t_p0).kind) {
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)17):
	{
		tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD_;
		colontmpD_ = NIM_NIL;
		nimln_(122);		{
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__2;
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__3;
			colontmpD_ = baseClass__ast_u5371(t_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
			if (!!((colontmpD_ == ((tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*) NIM_NIL)))) goto LA30_;
			colontmpD__2 = NIM_NIL;
			colontmpD__3 = NIM_NIL;
			nimln_(123);			colontmpD__2 = baseClass__ast_u5371(t_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
			colontmpD__3 = skipTypes__ast_u5402(colontmpD__2, TM__VSC6iKzck1XeooN9aLTqhXA_9);
			if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
			result = containsDangerousRefAux__isolation95check_u86(colontmpD__3, marker_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA32_;
			{
				LA32_:;
			}
			{
				oldNimErrFin32_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(934, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___ast_u3387(colontmpD__3);
				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
				eqdestroy___ast_u3387(colontmpD__2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
				*nimErr_ = oldNimErrFin32_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
		}
LA30_: ;
		nimlf_(124, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		{
			if (!(result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0))) goto LA37_;
			result = containsDangerousRefAux__isolation95check_u89((*t_p0).n, marker_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
		}
LA37_: ;
		{
			LA27_:;
		}
		{
			oldNimErrFin27_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___ast_u3387(colontmpD_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin27_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)11):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)13):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)4):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)46):
	{
		tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__4;
		colontmpD__4 = NIM_NIL;
		nimlf_(126, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		colontmpD__4 = skipModifier__ast_u5361(t_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
		result = containsDangerousRefAux__isolation95check_u86(colontmpD__4, marker_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
		{
			LA42_:;
		}
		{
			oldNimErrFin42_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___ast_u3387(colontmpD__4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin42_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)16):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)19):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)24):
	{
		tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__5;
		colontmpD__5 = NIM_NIL;
		nimlf_(128, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		colontmpD__5 = elementType__ast_u5354(t_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
		result = containsDangerousRefAux__isolation95check_u86(colontmpD__5, marker_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA46_;
		{
			LA46_:;
		}
		{
			oldNimErrFin46_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___ast_u3387(colontmpD__5);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin46_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)18):
	{
		{
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* a_1;
			a_1 = NIM_NIL;
			{
				NI i_1;
				NI colontmp_;
				NI T53_;
				NI i_2;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(1526, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				T53_ = (*t_p0).sons.len;
				colontmp_ = T53_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NI TM__VSC6iKzck1XeooN9aLTqhXA_25;
						if (!(i_2 < colontmp_)) goto LA55;
						nimlf_(1526, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");						i_1 = i_2;
						nimlf_(934, "/opt/local/lib/nim/lib/system.nim");						if (i_1 < 0 || i_1 >= (*t_p0).sons.len){ raiseIndexError2(i_1,(*t_p0).sons.len-1); goto LA51_;
						}
						eqcopy___ast_u3390(&a_1, (*t_p0).sons.p->data[i_1]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
						nimlf_(131, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						result = containsDangerousRefAux__isolation95check_u86(a_1, marker_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
						nimln_(132);						{
							if (!(result == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2))) goto LA58_;
							nimlf_(934, "/opt/local/lib/nim/lib/system.nim");							eqdestroy___ast_u3387(a_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							goto BeforeRet_;
						}
LA58_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_25)) { raiseOverflow(); goto LA51_;
						};
						i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_25);
					} LA55: ;
				}
			}
			{
				LA51_:;
			}
			{
				oldNimErrFin51_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(934, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___ast_u3387(a_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin51_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsDangerousRef__isolation95check_u202)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0) {
	NIM_BOOL result;
	tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q marker_1;
	tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("containsDangerousRef", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&marker_1), sizeof(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q));
	nimlf_(141, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");	initIntSet__pureZcollectionsZintsets_u608((&marker_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(142);	T2_ = (tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)0;
	T2_ = containsDangerousRefAux__isolation95check_u86(t_p0, (&marker_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = (T2_ == ((tyEnum_SearchResult__VzMn9bNyQ4t9bU7MwObyO9clA)2));
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(174, "/opt/local/lib/nim/lib/std/packedsets.nim");		eqdestroy___pureZcollectionsZintsets_u230((&marker_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, wrap__isolation95check_u72)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0) {
	NIM_BOOL result;
	nimfr_("wrap", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
	result = ((*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)22) || (*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)21) || (*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)23) || (*t_p0).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)47));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValueOnlyType__isolation95check_u69)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* t_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("isValueOnlyType", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(77, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");	T1_ = (NIM_BOOL)0;
	T1_ = searchTypeFor__types_u429(t_p0, wrap__isolation95check_u72);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = !(T1_);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAliasN__isolation95check_u10)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p2) {
	NIM_BOOL result;
NIM_BOOL oldNimErrFin22_;
NIM_BOOL* nimErr_;
	nimfr_("canAliasN", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(24);	switch ((*n_p1).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)138):
	{
		nimln_(26);		result = NIM_FALSE;
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(27, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			colontmp_ = len__ast_u3197(n_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_2 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NI TM__VSC6iKzck1XeooN9aLTqhXA_28;
					if (!(i_2 < colontmp_)) goto LA4;
					nimlf_(27, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");					i_1 = i_2;
					nimln_(28);					if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_27, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p1)._kind_6.sons.len-1); goto BeforeRet_;
					}
					result = canAliasN__isolation95check_u10(arg_p0, (*n_p1)._kind_6.sons.p->data[i_1], marker_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(29);					{
						if (!result) goto LA7_;
						goto BeforeRet_;
					}
LA7_: ;
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_28)) { raiseOverflow(); goto BeforeRet_;
					};
					i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_28);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)139):
	{
		nimlf_(31, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		{
			if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_29, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p1)._kind_6.sons.len-1); goto BeforeRet_;
			}
			if (!!(((*(*n_p1)._kind_6.sons.p->data[((NI)0)]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3)))) goto LA12_;
			failedAssertImpl__stdZassertions_u242(TM__VSC6iKzck1XeooN9aLTqhXA_31);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA12_: ;
		nimln_(32);		if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_32, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
		}
		if (((NI)0) < 0 || ((NI)0) >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p1)._kind_6.sons.len-1); goto BeforeRet_;
		}
		result = canAliasN__isolation95check_u10(arg_p0, (*n_p1)._kind_6.sons.p->data[((NI)0)], marker_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(33);		{
			if (!result) goto LA16_;
			goto BeforeRet_;
		}
LA16_: ;
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(34, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			colontmp__2 = len__ast_u3197(n_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_4 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NI TM__VSC6iKzck1XeooN9aLTqhXA_35;
					if (!(i_4 < colontmp__2)) goto LA20;
					nimlf_(34, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");					i_3 = i_4;
					nimln_(35);					if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_33, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
					}
					if (i_3 < 0 || i_3 >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p1)._kind_6.sons.len-1); goto BeforeRet_;
					}
					switch ((*(*n_p1)._kind_6.sons.p->data[i_3]).kind) {
					case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)85):
					case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)88):
					{
						tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* colontmpD_;
						colontmpD_ = NIM_NIL;
						nimln_(37);						if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_34, dollar___nodekinds_u168((*n_p1).kind)); goto LA22_;
						}
						if (i_3 < 0 || i_3 >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p1)._kind_6.sons.len-1); goto LA22_;
						}
						colontmpD_ = lastSon__ast_u5231((*n_p1)._kind_6.sons.p->data[i_3]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						result = canAliasN__isolation95check_u10(arg_p0, colontmpD_, marker_p2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
						nimln_(38);						{
							if (!result) goto LA25_;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							goto BeforeRet_;
						}
LA25_: ;
						{
							LA22_:;
						}
						{
							oldNimErrFin22_ = *nimErr_; *nimErr_ = NIM_FALSE;
							eqdestroy___ast_u3261(colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							*nimErr_ = oldNimErrFin22_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					break;
					default:
					{
					}
					break;
					}
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_4, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_35)) { raiseOverflow(); goto BeforeRet_;
					};
					i_4 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_35);
				} LA20: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
	{
		nimlf_(41, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		if (!(((TM__VSC6iKzck1XeooN9aLTqhXA_21[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_36, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
		}
		result = canAlias__isolation95check_u6(arg_p0, (*(*n_p1)._kind_4.sym).typ, marker_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		nimln_(42);		result = NIM_FALSE;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAlias__isolation95check_u6)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* ret_p1, tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q* marker_p2) {
	NIM_BOOL result;
NIM_BOOL oldNimErrFin29_;
NIM_BOOL oldNimErrFin22_;
NIM_BOOL oldNimErrFin37_;
NIM_BOOL oldNimErrFin49_;
NIM_BOOL* nimErr_;
	nimfr_("canAlias", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(45);	{
		tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA xX60gensym8__1;
		NI TM__VSC6iKzck1XeooN9aLTqhXA_26;
		NIM_BOOL T3_;
		nimlf_(954, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		xX60gensym8__1 = (*ret_p1).itemId;
		nimlf_(45, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		nimlf_(955, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		if (nimAddInt((NI)((NU32)(((NI) (xX60gensym8__1.module))) << (NU32)(((NI)20))), ((NI) (xX60gensym8__1.item)), &TM__VSC6iKzck1XeooN9aLTqhXA_26)) { raiseOverflow(); goto BeforeRet_;
		};
		nimlf_(45, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		T3_ = (NIM_BOOL)0;
		T3_ = containsOrIncl__astyaml_u240(marker_p2, (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_26));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(46);		nimln_(44);		nimln_(46);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(48);	{
		if (!((*ret_p1).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)21) || (*ret_p1).kind == ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)26))) goto LA8_;
		nimln_(50);		nimln_(44);		nimln_(50);		result = NIM_FALSE;
		goto BeforeRet_;
	}
LA8_: ;
	nimln_(51);	{
		tySet_tyEnum_TTypeCmpFlag__yS5h5n9agTW21qcU4sqaLWw T12_;
		NIM_BOOL T13_;
		T12_ = 0;
		T13_ = (NIM_BOOL)0;
		T13_ = compareTypes__types_u2814(arg_p0, ret_p1, ((tyEnum_TDistinctCompare__bGjBWtLv0FsENHY1SboCdg)1), T12_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T13_) goto LA14_;
		nimln_(52);		nimln_(44);		nimln_(52);		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA14_: ;
	nimln_(53);	switch ((*ret_p1).kind) {
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)17):
	{
		nimln_(55);		{
			NIM_BOOL T19_;
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD_;
			T19_ = (NIM_BOOL)0;
			T19_ = isFinal__types_u778(ret_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T19_) goto LA20_;
			colontmpD_ = NIM_NIL;
			nimln_(56);			result = canAliasN__isolation95check_u10(arg_p0, (*ret_p1).n, marker_p2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
			nimln_(57);			{
				NIM_BOOL T25_;
				tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__2;
				T25_ = (NIM_BOOL)0;
				T25_ = !(result);
				if (!(T25_)) goto LA26_;
				colontmpD_ = baseClass__ast_u5371(ret_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				T25_ = !((colontmpD_ == ((tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*) NIM_NIL)));
LA26_: ;
				if (!T25_) goto LA27_;
				colontmpD__2 = NIM_NIL;
				nimln_(58);				colontmpD__2 = baseClass__ast_u5371(ret_p1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
				result = canAlias__isolation95check_u6(arg_p0, colontmpD__2, marker_p2);
				if (NIM_UNLIKELY(*nimErr_)) goto LA29_;
				{
					LA29_:;
				}
				{
					oldNimErrFin29_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/opt/local/lib/nim/lib/system.nim");					eqdestroy___ast_u3387(colontmpD__2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
					*nimErr_ = oldNimErrFin29_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
			}
LA27_: ;
			{
				LA22_:;
			}
			{
				oldNimErrFin22_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___ast_u3387(colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin22_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA17_;
LA20_: ;
		{
			nimlf_(60, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_TRUE;
		}
LA17_: ;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)18):
	{
		nimln_(62);		result = NIM_FALSE;
		{
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* r_1;
			r_1 = NIM_NIL;
			{
				NI i_1;
				NI colontmp_;
				NI T39_;
				NI i_2;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(1526, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				T39_ = (*ret_p1).sons.len;
				colontmp_ = T39_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NI TM__VSC6iKzck1XeooN9aLTqhXA_37;
						if (!(i_2 < colontmp_)) goto LA41;
						nimlf_(1526, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");						i_1 = i_2;
						nimlf_(934, "/opt/local/lib/nim/lib/system.nim");						if (i_1 < 0 || i_1 >= (*ret_p1).sons.len){ raiseIndexError2(i_1,(*ret_p1).sons.len-1); goto LA37_;
						}
						eqcopy___ast_u3390(&r_1, (*ret_p1).sons.p->data[i_1]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA37_;
						nimlf_(64, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						result = canAlias__isolation95check_u6(arg_p0, r_1, marker_p2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA37_;
						nimln_(65);						{
							if (!result) goto LA44_;
							nimlf_(934, "/opt/local/lib/nim/lib/system.nim");							eqdestroy___ast_u3387(r_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimlf_(65, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							goto LA36;
						}
LA44_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_37)) { raiseOverflow(); goto LA37_;
						};
						i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_37);
					} LA41: ;
				}
			}
			{
				LA37_:;
			}
			{
				oldNimErrFin37_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(934, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___ast_u3387(r_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin37_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA36: ;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)16):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)24):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)13):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)11):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)4):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)55):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)46):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)47):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)45):
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)22):
	{
		tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* colontmpD__3;
		colontmpD__3 = NIM_NIL;
		nimlf_(68, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		colontmpD__3 = skipModifier__ast_u5361(ret_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
		result = canAlias__isolation95check_u6(arg_p0, colontmpD__3, marker_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
		{
			LA49_:;
		}
		{
			oldNimErrFin49_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___ast_u3387(colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin49_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TTypeKind__IPpTjnWPY8YNHgTB8czCiQ)25):
	{
		nimlf_(70, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		result = ((*ret_p1).callConv == ((tyEnum_TCallingConvention__XXIh8WHDiwZFWOB6z9b9cQhw)9));
	}
	break;
	default:
	{
		nimln_(72);		result = NIM_FALSE;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, canAlias__isolation95check_u210)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* arg_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* ret_p1) {
	NIM_BOOL result;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL* nimErr_;
	nimfr_("canAlias", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(145);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValueOnlyType__isolation95check_u69(arg_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(147);		result = NIM_FALSE;
	}
	goto LA1_;
LA4_: ;
	{
		tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q marker_1;
		nimZeroMem((void*)(&marker_1), sizeof(tyObject_PackedSet__i3gtUlUrPDCqptv09aSM27Q));
		nimln_(149);		initIntSet__pureZcollectionsZintsets_u608((&marker_1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		nimln_(150);		result = canAlias__isolation95check_u6(arg_p0, ret_p1, (&marker_1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		{
			LA7_:;
		}
		{
			oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(174, "/opt/local/lib/nim/lib/std/packedsets.nim");			eqdestroy___pureZcollectionsZintsets_u230((&marker_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin7_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, safeLen__ast_u3204)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("safeLen", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1012, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	{
		if (!((*n_p0).kind >= ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)0) && (*n_p0).kind <= ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)23))) goto LA3_;
		result = ((NI)0);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(1013);		result = len__ast_u3197(n_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, containsVariable__isolation95check_u216)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NIM_BOOL result;
NIM_BOOL oldNimErrFin5_;
NIM_BOOL* nimErr_;
	nimfr_("containsVariable", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(156, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");	switch ((*n_p0).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)0) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)2):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)4) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)23):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)51) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)52):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)79) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)84):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)90):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)98):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)101) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)102):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)116):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)118):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)121) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)123):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)125):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)132):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)158) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)159):
	{
		nimln_(158);		result = NIM_FALSE;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
	{
		nimln_(160);		if (!(((TM__VSC6iKzck1XeooN9aLTqhXA_21[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_38, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		result = ((*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)21) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)3) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)8) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)9) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)10) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)11) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)5));
	}
	break;
	default:
	{
		{
			tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* ch_1;
			ch_1 = NIM_NIL;
			{
				NI i_1;
				NI colontmp_;
				NI i_2;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				colontmp_ = safeLen__ast_u3204(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_2 = ((NI)0);
				{
					nimln_(129);					while (1) {
						NI TM__VSC6iKzck1XeooN9aLTqhXA_40;
						if (!(i_2 < colontmp_)) goto LA8;
						nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");						i_1 = i_2;
						nimln_(1023);						if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_39, dollar___nodekinds_u168((*n_p0).kind)); goto LA5_;
						}
						if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto LA5_;
						}
						eqcopy___ast_u3264(&ch_1, (*n_p0)._kind_6.sons.p->data[i_1]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
						nimlf_(163, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						{
							NIM_BOOL T11_;
							T11_ = (NIM_BOOL)0;
							T11_ = containsVariable__isolation95check_u216(ch_1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
							if (!T11_) goto LA12_;
							nimln_(155);							nimln_(163);							result = NIM_TRUE;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(ch_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							goto BeforeRet_;
						}
LA12_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_40)) { raiseOverflow(); goto LA5_;
						};
						i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_40);
					} LA8: ;
				}
			}
			{
				LA5_:;
			}
			{
				oldNimErrFin5_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				eqdestroy___ast_u3261(ch_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin5_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		nimlf_(164, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");		result = NIM_FALSE;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkIsolate__isolation95check_u224)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NIM_BOOL result;
NIM_BOOL oldNimErrFin21_;
NIM_BOOL oldNimErrFin45_;
NIM_BOOL oldNimErrFin41_;
NIM_BOOL oldNimErrFin58_;
NIM_BOOL oldNimErrFin69_;
NIM_BOOL oldNimErrFin78_;
NIM_BOOL oldNimErrFin103_;
NIM_BOOL* nimErr_;
	nimfr_("checkIsolate", "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(167);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = containsTyRef__types_u597((*n_p0).typField);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimln_(170);		switch ((*n_p0).kind) {
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)5) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)23):
		{
			nimln_(172);			result = NIM_TRUE;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)26) ... ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)32):
		{
			nimln_(177);			{
				if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 				{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_4, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
				}
				if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
				}
				if (!!((((*(*(*n_p0)._kind_6.sons.p->data[((NI)0)]).typField).flags &((NU64)1<<((NU)((((tyEnum_TTypeFlag__GJmtY1UKY65JJNT2LxCtow)1)))&63U)))!=0))) goto LA10_;
				nimln_(178);				nimln_(166);				nimln_(178);				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA10_: ;
			{
				NI i_1;
				NI colontmp_;
				NI i_2;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(179, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");				colontmp_ = len__ast_u3197(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_2 = ((NI)1);
				{
					nimln_(129);					while (1) {
						NI TM__VSC6iKzck1XeooN9aLTqhXA_42;
						if (!(i_2 < colontmp_)) goto LA14;
						nimlf_(179, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						i_1 = i_2;
						nimln_(180);						{
							NIM_BOOL T17_;
							if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 							{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_6, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
							}
							if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
							}
							T17_ = (NIM_BOOL)0;
							T17_ = checkIsolate__isolation95check_u224((*n_p0)._kind_6.sons.p->data[i_1]);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T17_) goto LA18_;
						}
						goto LA15_;
LA18_: ;
						{
							tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* argType_1;
							argType_1 = NIM_NIL;
							nimlf_(934, "/opt/local/lib/nim/lib/system.nim");							if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 							{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_7, dollar___nodekinds_u168((*n_p0).kind)); goto LA21_;
							}
							if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto LA21_;
							}
							eqcopy___ast_u3390(&argType_1, (*(*n_p0)._kind_6.sons.p->data[i_1]).typField);
							if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
							nimlf_(184, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							{
								NIM_BOOL T24_;
								NIM_BOOL T25_;
								NIM_BOOL T27_;
								T24_ = (NIM_BOOL)0;
								T25_ = (NIM_BOOL)0;
								T25_ = !((argType_1 == ((tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*) NIM_NIL)));
								if (!(T25_)) goto LA26_;
								T27_ = (NIM_BOOL)0;
								T27_ = isCompileTimeOnly__types_u3711(argType_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
								T25_ = !(T27_);
LA26_: ;
								T24_ = T25_;
								if (!(T24_)) goto LA28_;
								T24_ = containsDangerousRef__isolation95check_u202(argType_1);
								if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
LA28_: ;
								if (!T24_) goto LA29_;
								nimln_(185);								{
									NIM_BOOL T33_;
									T33_ = (NIM_BOOL)0;
									T33_ = canAlias__isolation95check_u210(argType_1, (*n_p0).typField);
									if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
									if (T33_) goto LA34_;
									if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 									{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_41, dollar___nodekinds_u168((*n_p0).kind)); goto LA21_;
									}
									if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto LA21_;
									}
									T33_ = containsVariable__isolation95check_u216((*n_p0)._kind_6.sons.p->data[i_1]);
									if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
LA34_: ;
									if (!T33_) goto LA35_;
									nimln_(190);									nimln_(166);									nimln_(190);									result = NIM_FALSE;
									nimlf_(934, "/opt/local/lib/nim/lib/system.nim");									eqdestroy___ast_u3387(argType_1);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									goto BeforeRet_;
								}
LA35_: ;
							}
LA29_: ;
							{
								LA21_:;
							}
							{
								oldNimErrFin21_ = *nimErr_; *nimErr_ = NIM_FALSE;
								eqdestroy___ast_u3387(argType_1);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								*nimErr_ = oldNimErrFin21_;
							}
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA15_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_42)) { raiseOverflow(); goto BeforeRet_;
						};
						i_2 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_42);
					} LA14: ;
				}
			}
			nimlf_(191, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_TRUE;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)92):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)48):
		{
			nimln_(193);			result = NIM_FALSE;
			{
				tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* it_1;
				it_1 = NIM_NIL;
				{
					NI i_3;
					NI colontmp__2;
					NI i_4;
					i_3 = (NI)0;
					colontmp__2 = (NI)0;
					nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");					nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");					colontmp__2 = safeLen__ast_u3204(n_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
					nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");					i_4 = ((NI)0);
					{
						nimln_(129);						while (1) {
							tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* colontmpD_;
							NI TM__VSC6iKzck1XeooN9aLTqhXA_44;
							if (!(i_4 < colontmp__2)) goto LA44;
							colontmpD_ = NIM_NIL;
							nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							i_3 = i_4;
							nimln_(1023);							if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 							{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_43, dollar___nodekinds_u168((*n_p0).kind)); goto LA45_;
							}
							if (i_3 < 0 || i_3 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p0)._kind_6.sons.len-1); goto LA45_;
							}
							eqcopy___ast_u3264(&it_1, (*n_p0)._kind_6.sons.p->data[i_3]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA45_;
							nimlf_(195, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							colontmpD_ = lastSon__ast_u5231(it_1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA45_;
							result = checkIsolate__isolation95check_u224(colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto LA45_;
							nimln_(196);							{
								if (!!(result)) goto LA48_;
								nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");								eqdestroy___ast_u3261(colontmpD_);
								if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
								eqdestroy___ast_u3261(it_1);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimlf_(196, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");								goto LA40;
							}
LA48_: ;
							nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");							if (nimAddInt(i_4, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_44)) { raiseOverflow(); goto LA45_;
							};
							i_4 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_44);
							{
								LA45_:;
							}
							{
								oldNimErrFin45_ = *nimErr_; *nimErr_ = NIM_FALSE;
								nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");								eqdestroy___ast_u3261(colontmpD_);
								if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
								*nimErr_ = oldNimErrFin45_;
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
						} LA44: ;
					}
				}
				{
					LA41_:;
				}
				{
					oldNimErrFin41_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___ast_u3261(it_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					*nimErr_ = oldNimErrFin41_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA40: ;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)97):
		{
			nimlf_(198, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_FALSE;
			{
				NI i_5;
				NI colontmp__3;
				NI i_6;
				i_5 = (NI)0;
				colontmp__3 = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(199, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");				colontmp__3 = len__ast_u3197(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_6 = ((NI)1);
				{
					nimln_(129);					while (1) {
						tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* colontmpD__2;
						NI TM__VSC6iKzck1XeooN9aLTqhXA_46;
						if (!(i_6 < colontmp__3)) goto LA57;
						colontmpD__2 = NIM_NIL;
						nimlf_(199, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						i_5 = i_6;
						nimln_(200);						if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_45, dollar___nodekinds_u168((*n_p0).kind)); goto LA58_;
						}
						if (i_5 < 0 || i_5 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_5,(*n_p0)._kind_6.sons.len-1); goto LA58_;
						}
						colontmpD__2 = lastSon__ast_u5231((*n_p0)._kind_6.sons.p->data[i_5]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						result = checkIsolate__isolation95check_u224(colontmpD__2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
						nimln_(201);						{
							if (!!(result)) goto LA61_;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD__2);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimlf_(201, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							goto LA55;
						}
LA61_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_6, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_46)) { raiseOverflow(); goto LA58_;
						};
						i_6 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_46);
						{
							LA58_:;
						}
						{
							oldNimErrFin58_ = *nimErr_; *nimErr_ = NIM_FALSE;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD__2);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							*nimErr_ = oldNimErrFin58_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					} LA57: ;
				}
			} LA55: ;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)38):
		{
			nimlf_(203, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_TRUE;
			{
				NI i_7;
				NI colontmp__4;
				NI i_8;
				i_7 = (NI)0;
				colontmp__4 = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(204, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");				colontmp__4 = len__ast_u3197(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_8 = ((NI)1);
				{
					nimln_(129);					while (1) {
						tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* colontmpD__3;
						NI TM__VSC6iKzck1XeooN9aLTqhXA_48;
						if (!(i_8 < colontmp__4)) goto LA68;
						colontmpD__3 = NIM_NIL;
						nimlf_(204, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");						i_7 = i_8;
						nimln_(205);						if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_47, dollar___nodekinds_u168((*n_p0).kind)); goto LA69_;
						}
						if (i_7 < 0 || i_7 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_7,(*n_p0)._kind_6.sons.len-1); goto LA69_;
						}
						colontmpD__3 = lastSon__ast_u5231((*n_p0)._kind_6.sons.p->data[i_7]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						result = checkIsolate__isolation95check_u224(colontmpD__3);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						nimln_(206);						{
							if (!!(result)) goto LA72_;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD__3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimlf_(206, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							goto LA66;
						}
LA72_: ;
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_8, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_48)) { raiseOverflow(); goto LA69_;
						};
						i_8 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_48);
						{
							LA69_:;
						}
						{
							oldNimErrFin69_ = *nimErr_; *nimErr_ = NIM_FALSE;
							nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							eqdestroy___ast_u3261(colontmpD__3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							*nimErr_ = oldNimErrFin69_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					} LA68: ;
				}
			} LA66: ;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)41):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)160):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)37):
		{
			nimlf_(208, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_FALSE;
			{
				tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* it_2;
				it_2 = NIM_NIL;
				{
					NI i_9;
					NI colontmp__5;
					NI i_10;
					i_9 = (NI)0;
					colontmp__5 = (NI)0;
					nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");					nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");					colontmp__5 = safeLen__ast_u3204(n_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA78_;
					nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");					i_10 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NI TM__VSC6iKzck1XeooN9aLTqhXA_50;
							if (!(i_10 < colontmp__5)) goto LA81;
							nimlf_(1947, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");							i_9 = i_10;
							nimln_(1023);							if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 							{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_49, dollar___nodekinds_u168((*n_p0).kind)); goto LA78_;
							}
							if (i_9 < 0 || i_9 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_9,(*n_p0)._kind_6.sons.len-1); goto LA78_;
							}
							eqcopy___ast_u3264(&it_2, (*n_p0)._kind_6.sons.p->data[i_9]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA78_;
							nimlf_(210, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");							result = checkIsolate__isolation95check_u224(it_2);
							if (NIM_UNLIKELY(*nimErr_)) goto LA78_;
							nimln_(211);							{
								if (!!(result)) goto LA84_;
								nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");								eqdestroy___ast_u3261(it_2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimlf_(211, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");								goto LA77;
							}
LA84_: ;
							nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");							if (nimAddInt(i_10, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_50)) { raiseOverflow(); goto LA78_;
							};
							i_10 = (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_50);
						} LA81: ;
					}
				}
				{
					LA78_:;
				}
				{
					oldNimErrFin78_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");					eqdestroy___ast_u3261(it_2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					*nimErr_ = oldNimErrFin78_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA77: ;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)58):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)59):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)61):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)60):
		{
			nimlf_(213, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_51, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			if (((NI)1) < 0 || ((NI)1) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)1),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
			}
			result = checkIsolate__isolation95check_u224((*n_p0)._kind_6.sons.p->data[((NI)1)]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)67):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)66):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)45):
		{
			nimln_(215);			if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_52, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
			}
			result = checkIsolate__isolation95check_u224((*n_p0)._kind_6.sons.p->data[((NI)0)]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)115):
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)126):
		{
			nimln_(217);			{
				NI T93_;
				NI T96_;
				NI TM__VSC6iKzck1XeooN9aLTqhXA_54;
				T93_ = (NI)0;
				T93_ = len__ast_u3197(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(((NI)0) < T93_)) goto LA94_;
				nimln_(218);				if (((TM__VSC6iKzck1XeooN9aLTqhXA_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 				{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_53, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
				}
				nimlf_(1031, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				T96_ = (NI)0;
				T96_ = len__ast_u3197(n_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimSubInt(T96_, ((NI)1), &TM__VSC6iKzck1XeooN9aLTqhXA_54)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_54) < 0 || (NI)(TM__VSC6iKzck1XeooN9aLTqhXA_54) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2((NI)(TM__VSC6iKzck1XeooN9aLTqhXA_54),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
				}
				nimlf_(218, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");				result = checkIsolate__isolation95check_u224((*n_p0)._kind_6.sons.p->data[(NI)(TM__VSC6iKzck1XeooN9aLTqhXA_54)]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			goto LA91_;
LA94_: ;
			{
				nimln_(220);				result = NIM_FALSE;
			}
LA91_: ;
		}
		break;
		case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
		{
			nimln_(222);			result = NIM_TRUE;
			nimln_(223);			{
				tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* argType_2;
				if (!(((TM__VSC6iKzck1XeooN9aLTqhXA_21[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 				{ raiseFieldErrorStr(TM__VSC6iKzck1XeooN9aLTqhXA_55, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
				}
				if (!((*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)21) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)3) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)8) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)9) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)10) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)11) || (*(*n_p0)._kind_4.sym).kind == ((tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ)5))) goto LA101_;
				argType_2 = NIM_NIL;
				nimlf_(934, "/opt/local/lib/nim/lib/system.nim");				eqcopy___ast_u3390(&argType_2, (*n_p0).typField);
				if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
				nimlf_(225, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");				{
					NIM_BOOL T106_;
					NIM_BOOL T107_;
					NIM_BOOL T109_;
					T106_ = (NIM_BOOL)0;
					T107_ = (NIM_BOOL)0;
					T107_ = !((argType_2 == ((tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg*) NIM_NIL)));
					if (!(T107_)) goto LA108_;
					T109_ = (NIM_BOOL)0;
					T109_ = isCompileTimeOnly__types_u3711(argType_2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
					T107_ = !(T109_);
LA108_: ;
					T106_ = T107_;
					if (!(T106_)) goto LA110_;
					T106_ = containsDangerousRef__isolation95check_u202(argType_2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
LA110_: ;
					if (!T106_) goto LA111_;
					nimln_(226);					result = NIM_FALSE;
				}
LA111_: ;
				{
					LA103_:;
				}
				{
					oldNimErrFin103_ = *nimErr_; *nimErr_ = NIM_FALSE;
					nimlf_(934, "/opt/local/lib/nim/lib/system.nim");					eqdestroy___ast_u3387(argType_2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					*nimErr_ = oldNimErrFin103_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA101_: ;
		}
		break;
		default:
		{
			nimlf_(229, "/Users/svacchanda/Dev/nimv2/compiler/isolation_check.nim");			result = NIM_FALSE;
		}
		break;
		}
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(232);		result = NIM_TRUE;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
