/* Generated by Nim Compiler v2.3.1 */
#define NIM_INTBITS 32
#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw;
typedef struct tyObject_Target__KQjOBnRpvUcQCKmgtWbZKw tyObject_Target__KQjOBnRpvUcQCKmgtWbZKw;
typedef struct tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w;
typedef struct tyObject_MsgConfig__DhchQlXfo3yFOmBLzsK1yg tyObject_MsgConfig__DhchQlXfo3yFOmBLzsK1yg;
typedef struct tySequence__RVxmrbMmX4ZakGUzNkGkkw tySequence__RVxmrbMmX4ZakGUzNkGkkw;
typedef struct tySequence__RVxmrbMmX4ZakGUzNkGkkw_Content tySequence__RVxmrbMmX4ZakGUzNkGkkw_Content;
typedef struct tyObject_Table__F9cGjmeM3hzxMFmRa3kjK9bw tyObject_Table__F9cGjmeM3hzxMFmRa3kjK9bw;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw tySequence__7lEisrXlQEzwtUKW5pzRCw;
typedef struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content tySequence__7lEisrXlQEzwtUKW5pzRCw_Content;
typedef struct tySequence__SZPdSphn6g9c2Izma1UrGLg tySequence__SZPdSphn6g9c2Izma1UrGLg;
typedef struct tySequence__SZPdSphn6g9c2Izma1UrGLg_Content tySequence__SZPdSphn6g9c2Izma1UrGLg_Content;
typedef struct tyObject_HashSet__zH55kRxY9cb9aFtz07gKs8bw tyObject_HashSet__zH55kRxY9cb9aFtz07gKs8bw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__XIjEkMz32CtxRFsUfX6hww tySequence__XIjEkMz32CtxRFsUfX6hww;
typedef struct tySequence__XIjEkMz32CtxRFsUfX6hww_Content tySequence__XIjEkMz32CtxRFsUfX6hww_Content;
typedef struct tyObject_SuggestcolonObjectType___9cIWVHcEKNwbBZ9adNGa0Hvg tyObject_SuggestcolonObjectType___9cIWVHcEKNwbBZ9adNGa0Hvg;
typedef struct tyObject_ProfileDatacolonObjectType___jrGvkEPYX2qZuP73AJSFwQ tyObject_ProfileDatacolonObjectType___jrGvkEPYX2qZuP73AJSFwQ;
typedef struct tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg;
typedef struct tySequence__6j25whH7XTBoIXcM0x1T7A tySequence__6j25whH7XTBoIXcM0x1T7A;
typedef struct tySequence__6j25whH7XTBoIXcM0x1T7A_Content tySequence__6j25whH7XTBoIXcM0x1T7A_Content;
typedef struct tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw;
typedef struct tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg;
typedef struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tyTuple__7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyTuple__9cdgeqdY7FRioNKBoD6G66A tyTuple__9cdgeqdY7FRioNKBoD6G66A;
typedef struct tyTuple__3Y9cBw3WJ7Zcr8BbBUZ82Zg tyTuple__3Y9cBw3WJ7Zcr8BbBUZ82Zg;
typedef struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw tyTuple__xYhUhS7X82rKTqbT9bRfCnw;
typedef struct tyObject_TFileInfo__F9beq9bq01HotF2x51baY8pQ tyObject_TFileInfo__F9beq9bq01HotF2x51baY8pQ;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct tyObject_Cfile__J0HCGRV7nOa8rFgHNa7I6A tyObject_Cfile__J0HCGRV7nOa8rFgHNa7I6A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU8 tyEnum_TBackend__b9bsKSgXpAuHBbPu9aNF34qg;
typedef NU8 tyEnum_TSystemCPU__SrLE7eSewCMuhqMCBBvCLA;
typedef NU8 tyEnum_TSystemOS__QR8tHj2g9arMbjKU9c4JC3Lg;
struct tyObject_Target__KQjOBnRpvUcQCKmgtWbZKw {
	tyEnum_TSystemCPU__SrLE7eSewCMuhqMCBBvCLA targetCPU;
	tyEnum_TSystemCPU__SrLE7eSewCMuhqMCBBvCLA hostCPU;
	tyEnum_TSystemOS__QR8tHj2g9arMbjKU9c4JC3Lg targetOS;
	tyEnum_TSystemOS__QR8tHj2g9arMbjKU9c4JC3Lg hostOS;
	NI intSize;
	NI floatSize;
	NI ptrSize;
	NimStringV2 tnl;
};
typedef NU32 tySet_tyEnum_TOption__bCUMbCQcztaP2hGJ0vc7xw;
typedef NU64 tySet_tyEnum_TGlobalOption__T9bPQvcSbvi9bUPnqulI0EgA;
typedef NU8 tySet_tyEnum_TErrorOutput__yMsgx6dAQt5pQl0xZix5Ow;
struct tySequence__RVxmrbMmX4ZakGUzNkGkkw {
	NI len;
	tySequence__RVxmrbMmX4ZakGUzNkGkkw_Content* p;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw {
	NI len;
	tySequence__7lEisrXlQEzwtUKW5pzRCw_Content* p;
};
struct tyObject_Table__F9cGjmeM3hzxMFmRa3kjK9bw {
	tySequence__7lEisrXlQEzwtUKW5pzRCw data;
	NI counter;
};
struct tySequence__SZPdSphn6g9c2Izma1UrGLg {
	NI len;
	tySequence__SZPdSphn6g9c2Izma1UrGLg_Content* p;
};
struct tyObject_MsgConfig__DhchQlXfo3yFOmBLzsK1yg {
	tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw trackPos;
	NIM_BOOL trackPosAttached;
	tySet_tyEnum_TErrorOutput__yMsgx6dAQt5pQl0xZix5Ow errorOutputs;
	tySequence__RVxmrbMmX4ZakGUzNkGkkw msgContext;
	tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw lastError;
	tyObject_Table__F9cGjmeM3hzxMFmRa3kjK9bw filenameToIndexTbl;
	tySequence__SZPdSphn6g9c2Izma1UrGLg fileInfos;
	NI32 systemFileIdx;
};
typedef NU8 tyEnum_FilenameOption__NoKqRdCqZCX2wtl9bqRVqoQ;
typedef NU8 tyEnum_Command__kd0o9ax4tip5Xhs1gEARN1w;
typedef NU8 tyEnum_TGCMode__a7X1pgnx8nZ4mryWZGBWFw;
typedef NU8 tyEnum_ExceptionSystem__69ccecoRGGV866EonNBUR4w;
typedef NU8 tyEnum_SymbolFilesOption__xyUkjkK84UhTke1KwsmO8w;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
	NI len;
	tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__zH55kRxY9cb9aFtz07gKs8bw {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
typedef NU32 tySet_tyEnum_Feature__kltKw9czG40tHHiR9c9aeLkaQ;
typedef NU8 tySet_tyEnum_LegacyFeature__ilG4wnoNdrKk8lx2nqyKGg;
typedef NU8 tyEnum_IdeCmd__M2EMeYKqZvToUHECycNN6g;
typedef NU8 tyEnum_TSystemCC__9cxBIDqYszaAZKQFeBbhWTA;
typedef NU8 tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ[13];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
	NI len;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyEnum_StdOrrKind__ek5RmOW15GN540khLxJIZw;
struct tySequence__XIjEkMz32CtxRFsUfX6hww {
	NI len;
	tySequence__XIjEkMz32CtxRFsUfX6hww_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(tyObject_SuggestcolonObjectType___9cIWVHcEKNwbBZ9adNGa0Hvg* result_p0, void* ClE_0);
	void* ClE_0;
} tyProc__hWBm9bFvg6Pqpy9cIJotGsjQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(NimStringV2 output_p0, void* ClE_0);
	void* ClE_0;
} tyProc__k2HFjxisIgDALbEUFojxaQ;
typedef NU8 tyEnum_Severity__AFCq9btkxd8BONZR2AblOcA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* config_p0, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p1, NimStringV2 msg_p2, tyEnum_Severity__AFCq9btkxd8BONZR2AblOcA severity_p3, void* ClE_0);
	void* ClE_0;
} tyProc__zcbKQsjzTVdY9cVf7rRQeOg;
struct tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g {
	tyEnum_TBackend__b9bsKSgXpAuHBbPu9aNF34qg backend;
	tyObject_Target__KQjOBnRpvUcQCKmgtWbZKw target;
	NI linesCompiled;
	tySet_tyEnum_TOption__bCUMbCQcztaP2hGJ0vc7xw options;
	tySet_tyEnum_TGlobalOption__T9bPQvcSbvi9bUPnqulI0EgA globalOptions;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* macrosToExpand;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* arcToExpand;
	tyObject_MsgConfig__DhchQlXfo3yFOmBLzsK1yg m;
	tyEnum_FilenameOption__NoKqRdCqZCX2wtl9bqRVqoQ filenameOption;
	NimStringV2 unitSep;
	NI evalTemplateCounter;
	NI evalMacroCounter;
	NI8 exitcode;
	tyEnum_Command__kd0o9ax4tip5Xhs1gEARN1w cmd;
	NimStringV2 cmdInput;
	NIM_BOOL projectIsCmd;
	NIM_BOOL implicitCmd;
	tyEnum_TGCMode__a7X1pgnx8nZ4mryWZGBWFw selectedGC;
	tyEnum_ExceptionSystem__69ccecoRGGV866EonNBUR4w exc;
	NIM_BOOL hintProcessingDots;
	NI verbosity;
	NI numberOfProcessors;
	NF lastCmdTime;
	tyEnum_SymbolFilesOption__xyUkjkK84UhTke1KwsmO8w symbolFiles;
	NI spellSuggestMax;
	tyObject_HashSet__zH55kRxY9cb9aFtz07gKs8bw cppDefines;
	NimStringV2 headerFile;
	NimStringV2 nimbasePattern;
	tySet_tyEnum_Feature__kltKw9czG40tHHiR9c9aeLkaQ features;
	tySet_tyEnum_LegacyFeature__ilG4wnoNdrKk8lx2nqyKGg legacyFeatures;
	NimStringV2 arguments;
	tyEnum_IdeCmd__M2EMeYKqZvToUHECycNN6g ideCmd;
	tyEnum_TSystemCC__9cxBIDqYszaAZKQFeBbhWTA cCompiler;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ modifiedyNotes;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ cmdlineNotes;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ foreignPackageNotes;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ notes;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ warningAsErrors;
	tySet_tyEnum_TMsgKind__JZ6hfMLp5vQFcseV1nEyLQ mainPackageNotes;
	NI mainPackageId;
	NI errorCounter;
	NI hintCounter;
	NI warnCounter;
	NI errorMax;
	NI maxLoopIterationsVM;
	NI maxCallDepthVM;
	NIM_BOOL isVmTrace;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* configVars;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* symbols;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* packageCache;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimblePaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ searchPaths;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lazyPaths;
	NimStringV2 outFile;
	NimStringV2 outDir;
	NimStringV2 jsonBuildFile;
	NimStringV2 prefixDir;
	NimStringV2 libpath;
	NimStringV2 nimcacheDir;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* dllOverrides;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* moduleOverrides;
	tyObject_StringTableObj__w9c0TWK2tuZlCSuJXyJLX1w* cfileSpecificOptions;
	NimStringV2 projectName;
	NimStringV2 projectPath;
	NimStringV2 projectFull;
	NIM_BOOL projectIsStdin;
	NimStringV2 stdinFile;
	tySet_tyEnum_StdOrrKind__ek5RmOW15GN540khLxJIZw lastMsgWasDot;
	NI32 projectMainIdx;
	NI32 projectMainIdx2;
	NimStringV2 command;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ commandArgs;
	NimStringV2 commandLine;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ extraCmds;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitImports;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ implicitIncludes;
	NimStringV2 docSeeSrcUrl;
	NimStringV2 docRoot;
	NimStringV2 docCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ configFiles;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cIncludes;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ cLinkedLibs;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ externalToLink;
	NimStringV2 linkOptionsCmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ compileOptionsCmd;
	NimStringV2 linkOptions;
	NimStringV2 compileOptions;
	NimStringV2 cCompilerPath;
	tySequence__XIjEkMz32CtxRFsUfX6hww toCompile;
	tyProc__hWBm9bFvg6Pqpy9cIJotGsjQ suggestionResultHook;
	NI suggestVersion;
	NI suggestMaxResults;
	tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw lastLineInfo;
	tyProc__k2HFjxisIgDALbEUFojxaQ writelnHook;
	tyProc__zcbKQsjzTVdY9cVf7rRQeOg structuredErrorHook;
	NimStringV2 cppCustomNamespace;
	NimStringV2 nimMainPrefix;
	tyObject_ProfileDatacolonObjectType___jrGvkEPYX2qZuP73AJSFwQ* vmProfileData;
	NIM_BOOL expandProgress;
	NI expandLevels;
	NimStringV2 expandNodeResult;
	tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw expandPosition;
	NimStringV2 currentConfigDir;
	NI clientProcessId;
};
struct tySequence__6j25whH7XTBoIXcM0x1T7A {
	NI len;
	tySequence__6j25whH7XTBoIXcM0x1T7A_Content* p;
};
struct tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg {
	tySequence__6j25whH7XTBoIXcM0x1T7A data;
	NI counter;
};
typedef NU8 tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw;
struct tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg {
	NI32 dwLowDateTime;
	NI32 dwHighDateTime;
};
typedef NI16 tyArray__EKfNt9b8uxndgFbu2Ky3XAQ[260];
typedef NI16 tyArray__Get9cpRTS5VjGKP6CDsI9bYA[14];
struct tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw {
	NI32 dwFileAttributes;
	tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg ftCreationTime;
	tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg ftLastAccessTime;
	tyObject_FILETIME__cWFCImZiVoGGGcpqBGtmBg ftLastWriteTime;
	NI32 nFileSizeHigh;
	NI32 nFileSizeLow;
	NI32 dwReserved0;
	NI32 dwReserved1;
	tyArray__EKfNt9b8uxndgFbu2Ky3XAQ cFileName;
	tyArray__Get9cpRTS5VjGKP6CDsI9bYA cAlternateFileName;
};
struct tyTuple__7q7q3E6Oj24ZNVJb9aonhAg {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
};
struct tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g {
	NI a;
	NI b;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
	NimStringV2 Field0;
	NimStringV2 Field1;
};
typedef NU8 tyEnum_TMsgKind__JKNkZ4SkwI4rbqnu3OS3OQ;
typedef NU8 tyEnum_TErrorHandling__GRtK9ayzkQ4jQUDEsPFQ2Uw;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
	NimStringV2 Field0;
	NI Field1;
	NI Field2;
};
typedef N_STDCALL_PTR(NI32, tyProc__CGE29bryGjdkIBZX79bYpaGQ)(NI hFindFile_p0, tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw* lpFindFileData_p1);
typedef N_STDCALL_PTR(NI32, tyProc__9bXer9a4ps9aSGctILcxWReVw)(void);
typedef N_STDCALL_PTR(void, tyProc__ofoySXaAAlxxs9bQS9a1etlg)(NI hFindFile_p0);
struct tyTuple__9cdgeqdY7FRioNKBoD6G66A {
	NI Field0;
	NimStringV2 Field1;
	tyTuple__UV3llMMYFckfui8YMBuUZA Field2;
};
struct tyTuple__3Y9cBw3WJ7Zcr8BbBUZ82Zg {
	tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw Field0;
	NimStringV2 Field1;
};
struct tySequence__RVxmrbMmX4ZakGUzNkGkkw_Content {
	NI cap;
	tyTuple__3Y9cBw3WJ7Zcr8BbBUZ82Zg data[SEQ_DECL_SIZE];
};
struct tyTuple__xYhUhS7X82rKTqbT9bRfCnw {
	NI Field0;
	NimStringV2 Field1;
	NI32 Field2;
};
struct tySequence__7lEisrXlQEzwtUKW5pzRCw_Content {
	NI cap;
	tyTuple__xYhUhS7X82rKTqbT9bRfCnw data[SEQ_DECL_SIZE];
};
struct tyObject_TFileInfo__F9beq9bq01HotF2x51baY8pQ {
	NimStringV2 fullPath;
	NimStringV2 projPath;
	NimStringV2 shortName;
	NimStringV2 quotedName;
	NimStringV2 quotedFullName;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ lines;
	NimStringV2 dirtyFile;
	NimStringV2 hash;
	NIM_BOOL dirty;
};
struct tySequence__SZPdSphn6g9c2Izma1UrGLg_Content {
	NI cap;
	tyObject_TFileInfo__F9beq9bq01HotF2x51baY8pQ data[SEQ_DECL_SIZE];
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content {
	NI cap;
	tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE];
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content {
	NI cap;
	NimStringV2 data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_CfileFlag__7htHmsegGiQe9aYvjQ7weKg;
struct tyObject_Cfile__J0HCGRV7nOa8rFgHNa7I6A {
	NimStringV2 nimname;
	NimStringV2 cname;
	NimStringV2 obj;
	tySet_tyEnum_CfileFlag__7htHmsegGiQe9aYvjQ7weKg flags;
	NimStringV2 customArgs;
};
struct tySequence__XIjEkMz32CtxRFsUfX6hww_Content {
	NI cap;
	tyObject_Cfile__J0HCGRV7nOa8rFgHNa7I6A data[SEQ_DECL_SIZE];
};
struct tySequence__6j25whH7XTBoIXcM0x1T7A_Content {
	NI cap;
	tyTuple__9cdgeqdY7FRioNKBoD6G66A data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, contains__nimblecmd_u17)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
static N_INLINE(NI, find__nimblecmd_u22)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___nimblecmd_u42)(NimStringV2 x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4376)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, insert__nimblecmd_u52)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 item_p1, NI i_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2659)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, addPathRec__nimblecmd_u2208)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 dir_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2164)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg, initTable__nimblecmd_u2226)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(NI, findFirstFile__stdZprivateZoscommon_u27)(NimStringV2 a_p0, tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw* b_p1);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u90)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u123)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u126)(void);
static N_INLINE(NIM_BOOL, skipFindData__stdZprivateZoscommon_u36)(tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw* f_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosextractFilename)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___stdZwidestrs_u394)(NI16* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2653)(NimStringV2 dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2662)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2650)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, addPackage__nimblecmd_u247)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg* packages_p1, NimStringV2 p_p2, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p3);
N_LIB_PRIVATE N_NIMCALL(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg, getPathVersionChecksum__nimblecmd_u211)(NimStringV2 p_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuRFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8712)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValidSha1Hash__OOZdistZchecksumsZsrcZchecksumsZsha1_u1026)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuRFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8699)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1292)(NimStringV2 s_p0, tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g x_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2402)(NimStringV2* s_p0);
static N_INLINE(tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g, dotdot___stdZstrbasics_u49)(NI a_p0, NI b_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValidVersion__nimblecmd_u175)(NimStringV2 v_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, newVersion__nimblecmd_u138)(NimStringV2 ver_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u76)(NimStringV2 msg_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1734)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt___nimblecmd_u186)(NimStringV2 ver_p0, NimStringV2 ver2_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSpecial__nimblecmd_u172)(NimStringV2 ver_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuNormalize)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1742)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5524)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitChar)(NimStringV2 s_p0, NIM_CHAR sep_p1, NI maxsplit_p2);
N_LIB_PRIVATE N_NIMCALL(NI, parseInt__pureZparseutils_u989)(NimStringV2 s_p0, NI* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(tyTuple__UV3llMMYFckfui8YMBuUZA, getOrDefault__nimblecmd_u319)(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__nimblecmd_u799)(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg t_p0, NimStringV2 key_p1);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___nimblecmd_u848)(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg* t_p0, NimStringV2 key_p1, tyTuple__UV3llMMYFckfui8YMBuUZA val_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZntpath_u119)(tyTuple__UV3llMMYFckfui8YMBuUZA dest_p0);
N_LIB_PRIVATE N_NOINLINE(void, liMessage__msgs_u1213)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p1, tyEnum_TMsgKind__JKNkZ4SkwI4rbqnu3OS3OQ msg_p2, NimStringV2 arg_p3, tyEnum_TErrorHandling__GRtK9ayzkQ4jQUDEsPFQ2Uw eh_p4, tyTuple__kN8up2W6YKc5YA9avn5mV5w info2_p5, NIM_BOOL isRaw_p6, NIM_BOOL ignoreError_p7);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZprivateZosdirs_u88)(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, len__nimblecmd_u1915)(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg t_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u32)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2656)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZprivateZntpath_u128)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest_p0, tyTuple__UV3llMMYFckfui8YMBuUZA src_p1);
N_LIB_PRIVATE N_NIMCALL(tyTuple__UV3llMMYFckfui8YMBuUZA, eqdup___stdZprivateZntpath_u125)(tyTuple__UV3llMMYFckfui8YMBuUZA src_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, addNimblePath__nimblecmd_u2173)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 p_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__stdZprivateZospaths2_u291)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg, nossplitFile)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u71)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u5521)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitLines)(NimStringV2 s_p0, NIM_BOOL keepEol_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__stdZsyncio_u625)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nimblecmd_u2155)(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg dest_p0);
static N_INLINE(NI, find__nimblecmd_u2266)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ a_p0, NimStringV2 item_p1);
N_LIB_PRIVATE N_NIMCALL(void, delete__nimblecmd_u2286)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NI i_p1);
static const struct {
	NI cap;
	NIM_CHAR data[2];
} TM__asNQM9aynXXg9ccUABbReyew_5 = {(1 | NIM_STRLIT_FLAG), "*"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_6 = {1, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_5))};
static const struct {
	NI cap;
	NIM_CHAR data[1];
} TM__asNQM9aynXXg9ccUABbReyew_8 = {(0 | NIM_STRLIT_FLAG), ""};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_9 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_10 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_11 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_13 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const struct {
	NI cap;
	NIM_CHAR data[3];
} TM__asNQM9aynXXg9ccUABbReyew_14 = {(2 | NIM_STRLIT_FLAG), "-#"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_15 = {2, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_14))};
static const struct {
	NI cap;
	NIM_CHAR data[124];
} TM__asNQM9aynXXg9ccUABbReyew_27 = {(123 | NIM_STRLIT_FLAG), "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim(32, 11) `ver.len == 0 or ver[0] in {\'#\', \'\\x00\'} + Digits` Wrong version: "};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_28 = {123, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_27))};
static const struct {
	NI cap;
	NIM_CHAR data[6];
} TM__asNQM9aynXXg9ccUABbReyew_29 = {(5 | NIM_STRLIT_FLAG), "#head"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_30 = {5, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_29))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_31 = {5, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_29))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_32 = {5, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_29))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_34 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const struct {
	NI cap;
	NIM_CHAR data[23];
} TM__asNQM9aynXXg9ccUABbReyew_35 = {(22 | NIM_STRLIT_FLAG), "invalid package name: "};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_36 = {22, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_35))};
static const struct {
	NI cap;
	NIM_CHAR data[49];
} TM__asNQM9aynXXg9ccUABbReyew_38 = {(48 | NIM_STRLIT_FLAG), "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_39 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const struct {
	NI cap;
	NIM_CHAR data[14];
} TM__asNQM9aynXXg9ccUABbReyew_40 = {(13 | NIM_STRLIT_FLAG), "*.nimble-link"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_41 = {13, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_40))};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_46 = {0, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_8))};
static const struct {
	NI cap;
	NIM_CHAR data[137];
} TM__asNQM9aynXXg9ccUABbReyew_48 = {(136 | NIM_STRLIT_FLAG), "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim(771, 13) `len(t) == L` the length of the table changed while iterating over it"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_49 = {136, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_48))};
static const struct {
	NI cap;
	NIM_CHAR data[128];
} TM__asNQM9aynXXg9ccUABbReyew_52 = {(127 | NIM_STRLIT_FLAG), "/Users/svacchanda/Dev/Nim/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"};
static const NimStringV2 TM__asNQM9aynXXg9ccUABbReyew_53 = {127, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_52))};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__asNQM9aynXXg9ccUABbReyew_37 = {{48, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_38))}, ((NI) 126), ((NI) 14)};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__asNQM9aynXXg9ccUABbReyew_47 = {{48, ((NimStrPayload*) (&TM__asNQM9aynXXg9ccUABbReyew_38))}, ((NI) 152), ((NI) 11)};
extern NIM_BOOL nimInErrorMode__system_u4158;
extern TFrame* framePtr__system_u2695;
extern tyProc__CGE29bryGjdkIBZX79bYpaGQ Dl_1392509182_;
extern tyProc__9bXer9a4ps9aSGctILcxWReVw Dl_1392509099_;
extern tyProc__ofoySXaAAlxxs9bQS9a1etlg Dl_1392509185_;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4158));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
	if ((!((framePtr__system_u2695 == ((TFrame*) NIM_NIL))))) {
	goto LA3_;
}
(*s_p0).calldepth = ((NI16) 0);
}
goto LA1_;
LA3_: ;
{
	(*s_p0).calldepth = ((NI16) ((*framePtr__system_u2695).calldepth + ((NI16) 1)));
}
LA1_: ;
(*s_p0).prev = framePtr__system_u2695;
framePtr__system_u2695 = s_p0;
{
	if ((!(((*s_p0).calldepth == ((NI16) 2000))))) {
	goto LA8_;
}
callDepthLimitReached__system_u4376();
}
LA8_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2695 = (*framePtr__system_u2695).prev;
}

static N_INLINE(NI, find__nimblecmd_u22)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("find", "/Users/svacchanda/Dev/Nim/lib/system.nim");
{
		nimErr_ = nimErrorFlag();
	nimlf_(1918, "/Users/svacchanda/Dev/Nim/lib/system.nim");result = ((NI) 0);
{
	NimStringV2* i_1;
NI i_2;
i_1 = ((NimStringV2*) 0);
		nimlf_(18, "/Users/svacchanda/Dev/Nim/lib/system/iterators.nim");i_2 = ((NI) 0);
{
				nimln_(19);while (1) {
	NI TM__asNQM9aynXXg9ccUABbReyew_2;
if ((!((i_2 < a_p0Len_0)))) {
	goto LA3;
}
				nimlf_(1919, "/Users/svacchanda/Dev/Nim/lib/system.nim");if (((i_2 < 0) || (i_2 >= a_p0Len_0))) {
	raiseIndexError2(i_2, (a_p0Len_0 - 1));
	goto BeforeRet_;
}
i_1 = ((&a_p0[i_2]));
				nimln_(1920);{
	NIM_BOOL T6_;
T6_ = ((NIM_BOOL) 0);
T6_ = eqeq___nimblecmd_u42((*i_1), item_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!(T6_))) {
	goto LA7_;
}
goto BeforeRet_;
}
LA7_: ;
				nimln_(1921);if (nimAddInt(result, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_2))) {
	raiseOverflow();
	goto BeforeRet_;
}
result = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_2));
				nimlf_(13, "/Users/svacchanda/Dev/Nim/lib/system/iterators.nim");i_2 += ((NI) 1);
}
LA3: ;
}
}
	nimlf_(1922, "/Users/svacchanda/Dev/Nim/lib/system.nim");result = ((NI) -1);
}
	BeforeRet_: ;
		popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains__nimblecmd_u17)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 item_p1) {
	NIM_BOOL result;
NI T1_;
	nimfr_("contains", "/Users/svacchanda/Dev/Nim/lib/system.nim");
{
			nimln_(1936);	nimln_(1924);	nimln_(1936);T1_ = ((NI) 0);
T1_ = find__nimblecmd_u22(a_p0, a_p0Len_0, item_p1);
result = (((NI) 0) <= T1_);
goto BeforeRet_;
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addPath__nimblecmd_u13)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 path_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2) {
		nimfr_("addPath", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
	nimlf_(22, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T3_;
NimStringV2 colontmpD_;
T3_ = ((NIM_BOOL) 0);
T3_ = contains__nimblecmd_u17((((*conf_p0).searchPaths).p ? ((*conf_p0).searchPaths).p->data : NIM_NIL), (*conf_p0).searchPaths.len, path_p1);
if ((!((!(T3_))))) {
	goto LA4_;
}
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
		nimln_(23);		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");colontmpD_ = eqdup___system_u2659(path_p1);
		nimlf_(23, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");insert__nimblecmd_u52(((&(*conf_p0).searchPaths)), colontmpD_, ((NI) 0));
}
LA4_: ;
	popFrame();
}

static N_INLINE(void, nimSetMem__system_u2164)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}

static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2164(p_p0, ((int) 0), size_p1);
}

static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u90)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/Users/svacchanda/Dev/Nim/lib/std/private/ospaths2.nim");
{
		nimErr_ = nimErrorFlag();
result.len = 0;
result.p = NIM_NIL;
	nimlf_(178, "/Users/svacchanda/Dev/Nim/lib/std/private/ospaths2.nim");result = nosjoinPath(head_p0, tail_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, skipFindData__stdZprivateZoscommon_u36)(tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw* f_p0) {
	NIM_BOOL result;
NIM_BOOL T1_;
NIM_BOOL T3_;
NIM_BOOL T5_;
	nimfr_("skipFindData", "/Users/svacchanda/Dev/Nim/lib/std/private/oscommon.nim");
	nimlf_(67, "/Users/svacchanda/Dev/Nim/lib/std/private/oscommon.nim");T1_ = ((NIM_BOOL) 0);
T1_ = (((NI) ((*f_p0).cFileName[(((NI) 0) - 0)])) == ((NI) 46));
if ((!(T1_))) {
	goto LA2_;
}
T3_ = ((NIM_BOOL) 0);
T3_ = (((NI) ((*f_p0).cFileName[(((NI) 1) - 0)])) == ((NI) 0));
if (T3_) {
	goto LA4_;
}
	nimln_(68);T5_ = ((NIM_BOOL) 0);
T5_ = (((NI) ((*f_p0).cFileName[(((NI) 1) - 0)])) == ((NI) 46));
if ((!(T5_))) {
	goto LA6_;
}
T5_ = (((NI) ((*f_p0).cFileName[(((NI) 2) - 0)])) == ((NI) 0));
LA6_: ;
T3_ = T5_;
LA4_: ;
T1_ = T3_;
LA2_: ;
result = T1_;
	popFrame();
	return result;
}

static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = (!(((*s_p0).p == ((NimStrPayload*) NIM_NIL))));
if ((!(T3_))) {
	goto LA4_;
}
T3_ = (((NI) ((*(*s_p0).p).cap & ((NI) 1073741824))) == ((NI) 1073741824));
LA4_: ;
if ((!(T3_))) {
	goto LA5_;
}
nimPrepareStrMutationImpl__system_u2402(s_p0);
}
LA5_: ;
}

static N_INLINE(NimStringV2, X5BX5D___pureZstrutils_u1292)(NimStringV2 s_p0, tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g x_p1) {
	NimStringV2 result;
NI a_1;
NI L_1;
NI TM__asNQM9aynXXg9ccUABbReyew_22;
NI TM__asNQM9aynXXg9ccUABbReyew_23;
	nimfr_("[]", "/Users/svacchanda/Dev/Nim/lib/system/indices.nim");
{
		result.len = 0;
result.p = NIM_NIL;
	nimlf_(83, "/Users/svacchanda/Dev/Nim/lib/system/indices.nim");a_1 = x_p1.a;
	nimln_(84);if (nimSubInt(x_p1.b, a_1, (&TM__asNQM9aynXXg9ccUABbReyew_22))) {
	raiseOverflow();
	goto BeforeRet_;
}
if (nimAddInt(((NI) TM__asNQM9aynXXg9ccUABbReyew_22), ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_23))) {
	raiseOverflow();
	goto BeforeRet_;
}
L_1 = ((NI) TM__asNQM9aynXXg9ccUABbReyew_23);
	nimln_(85);if (((L_1 < ((NI) 0)) || (L_1 > ((NI) 2147483647)))) {
	raiseRangeErrorI(L_1, ((NI) 0), ((NI) 2147483647));
	goto BeforeRet_;
}
result = mnewString((L_1));
{
	NI i_1;
NI i_2;
i_1 = ((NI) 0);
		nimlf_(128, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");i_2 = ((NI) 0);
{
				nimln_(129);while (1) {
	NI TM__asNQM9aynXXg9ccUABbReyew_24;
NI TM__asNQM9aynXXg9ccUABbReyew_25;
if ((!((i_2 < L_1)))) {
	goto LA3;
}
				nimlf_(86, "/Users/svacchanda/Dev/Nim/lib/system/indices.nim");i_1 = i_2;
if (((i_1 < 0) || (i_1 >= result.len))) {
	raiseIndexError2(i_1, (result.len - 1));
	goto BeforeRet_;
}
nimPrepareStrMutationV2(((&result)));
if (nimAddInt(i_1, a_1, (&TM__asNQM9aynXXg9ccUABbReyew_24))) {
	raiseOverflow();
	goto BeforeRet_;
}
if (((((NI) TM__asNQM9aynXXg9ccUABbReyew_24) < 0) || (((NI) TM__asNQM9aynXXg9ccUABbReyew_24) >= s_p0.len))) {
	raiseIndexError2(((NI) TM__asNQM9aynXXg9ccUABbReyew_24), (s_p0.len - 1));
	goto BeforeRet_;
}
(result).p->data[i_1] = (s_p0).p->data[((NI) TM__asNQM9aynXXg9ccUABbReyew_24)];
				nimlf_(131, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");if (nimAddInt(i_2, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_25))) {
	raiseOverflow();
	goto BeforeRet_;
}
i_2 = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_25));
}
LA3: ;
}
}
}
	BeforeRet_: ;
		popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g, dotdot___stdZstrbasics_u49)(NI a_p0, NI b_p1) {
	tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g result;
	nimfr_("..", "/Users/svacchanda/Dev/Nim/lib/system.nim");
	nimlf_(436, "/Users/svacchanda/Dev/Nim/lib/system.nim");result.a = a_p0;
result.b = b_p1;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg, getPathVersionChecksum__nimblecmd_u211)(NimStringV2 p_p0) {
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg result;
NimStringV2 colontmp_;
NimStringV2 colontmp__2;
NimStringV2 colontmp__3;
NimStringV2 blitTmp_1;
NimStringV2 blitTmp_2;
NimStringV2 blitTmp_3;
NI checksumSeparatorIndex_1;
NI versionSeparatorIndex_1;
NI TM__asNQM9aynXXg9ccUABbReyew_16;
NI TM__asNQM9aynXXg9ccUABbReyew_26;
tyObject_HSlice__PKdPmrV9a9bvn82gf9avrgC5g T24_;
NimStringV2 T25_;
NIM_BOOL* nimErr_;
	nimfr_("getPathVersionChecksum", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
colontmp_.len = 0;
colontmp_.p = NIM_NIL;
colontmp__2.len = 0;
colontmp__2.p = NIM_NIL;
colontmp__3.len = 0;
colontmp__3.p = NIM_NIL;
	nimlf_(82, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");colontmp_ = TM__asNQM9aynXXg9ccUABbReyew_9;
colontmp__2 = TM__asNQM9aynXXg9ccUABbReyew_10;
colontmp__3 = TM__asNQM9aynXXg9ccUABbReyew_11;
blitTmp_1 = colontmp_;
result.Field0 = blitTmp_1;
blitTmp_2 = colontmp__2;
result.Field1 = blitTmp_2;
blitTmp_3 = colontmp__3;
result.Field2 = blitTmp_3;
	nimln_(89);checksumSeparatorIndex_1 = nsuRFindChar(p_p0, 45, ((NI) 0), ((NI) -1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
	nimln_(90);{
	NI TM__asNQM9aynXXg9ccUABbReyew_12;
NimStringV2 T5_;
if ((!((!((checksumSeparatorIndex_1 == ((NI) -1))))))) {
	goto LA3_;
}
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");		nimlf_(91, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");if (nimAddInt(checksumSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_12))) {
	raiseOverflow();
	goto BeforeRet_;
}
T5_.len = 0;
T5_.p = NIM_NIL;
T5_ = substr__system_u8712(p_p0, ((NI) TM__asNQM9aynXXg9ccUABbReyew_12));
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&result.Field2)), T5_);
		nimlf_(92, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T8_;
T8_ = ((NIM_BOOL) 0);
T8_ = isValidSha1Hash__OOZdistZchecksumsZsrcZchecksumsZsha1_u1026(result.Field2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!((!(T8_))))) {
	goto LA9_;
}
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&result.Field2)), TM__asNQM9aynXXg9ccUABbReyew_13);
			nimlf_(94, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");checksumSeparatorIndex_1 = p_p0.len;
}
LA9_: ;
}
goto LA1_;
LA3_: ;
{
			nimln_(96);checksumSeparatorIndex_1 = p_p0.len;
}
LA1_: ;
	nimln_(98);	nimln_(99);if (nimSubInt(checksumSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_16))) {
	raiseOverflow();
	goto BeforeRet_;
}
	nimln_(98);versionSeparatorIndex_1 = nsuRFindStr(p_p0, TM__asNQM9aynXXg9ccUABbReyew_15, ((NI) 0), ((NI) TM__asNQM9aynXXg9ccUABbReyew_16));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
	nimln_(100);{
	NI TM__asNQM9aynXXg9ccUABbReyew_17;
NI TM__asNQM9aynXXg9ccUABbReyew_18;
NimStringV2 T16_;
if ((!((!((versionSeparatorIndex_1 == ((NI) -1))))))) {
	goto LA14_;
}
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");		nimlf_(101, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");		nimln_(102);if (nimAddInt(versionSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_17))) {
	raiseOverflow();
	goto BeforeRet_;
}
if (nimSubInt(checksumSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_18))) {
	raiseOverflow();
	goto BeforeRet_;
}
		nimln_(101);T16_.len = 0;
T16_.p = NIM_NIL;
T16_ = substr__system_u8699(p_p0, ((NI) TM__asNQM9aynXXg9ccUABbReyew_17), ((NI) TM__asNQM9aynXXg9ccUABbReyew_18));
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&result.Field1)), T16_);
}
goto LA12_;
LA14_: ;
{
	NI TM__asNQM9aynXXg9ccUABbReyew_19;
		nimlf_(104, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");		nimln_(105);if (nimSubInt(checksumSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_19))) {
	raiseOverflow();
	goto BeforeRet_;
}
		nimln_(104);versionSeparatorIndex_1 = nsuRFindChar(p_p0, 45, ((NI) 0), ((NI) TM__asNQM9aynXXg9ccUABbReyew_19));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
		nimln_(106);{
	NI TM__asNQM9aynXXg9ccUABbReyew_20;
NI TM__asNQM9aynXXg9ccUABbReyew_21;
NimStringV2 T22_;
if ((!((!((versionSeparatorIndex_1 == ((NI) -1))))))) {
	goto LA20_;
}
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");			nimlf_(107, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");			nimln_(108);if (nimAddInt(versionSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_20))) {
	raiseOverflow();
	goto BeforeRet_;
}
if (nimSubInt(checksumSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_21))) {
	raiseOverflow();
	goto BeforeRet_;
}
			nimln_(107);T22_.len = 0;
T22_.p = NIM_NIL;
T22_ = substr__system_u8699(p_p0, ((NI) TM__asNQM9aynXXg9ccUABbReyew_20), ((NI) TM__asNQM9aynXXg9ccUABbReyew_21));
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&result.Field1)), T22_);
}
goto LA18_;
LA20_: ;
{
				nimlf_(110, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");versionSeparatorIndex_1 = checksumSeparatorIndex_1;
}
LA18_: ;
}
LA12_: ;
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");	nimlf_(112, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");	nimlf_(53, "/Users/svacchanda/Dev/Nim/lib/system/indices.nim");if (nimSubInt(versionSeparatorIndex_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_26))) {
	raiseOverflow();
	goto BeforeRet_;
}
	nimlf_(112, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");T24_ = dotdot___stdZstrbasics_u49(((NI) 0), ((NI) TM__asNQM9aynXXg9ccUABbReyew_26));
T25_.len = 0;
T25_.p = NIM_NIL;
T25_ = X5BX5D___pureZstrutils_u1292(p_p0, T24_);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___system_u2653(T25_);
	goto BeforeRet_;
}
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&result.Field0)), T25_);
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isValidVersion__nimblecmd_u175)(NimStringV2 v_p0) {
	NIM_BOOL result;
	nimfr_("isValidVersion", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
			nimlf_(40, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	if ((!((((NI) 0) < v_p0.len)))) {
	goto LA3_;
}
		nimln_(41);{
	if (((((NI) 0) < 0) || (((NI) 0) >= v_p0.len))) {
	raiseIndexError2(((NI) 0), (v_p0.len - 1));
	goto BeforeRet_;
}
if ((!(((((NU8) (v_p0).p->data[((NI) 0)]) == ((NU8) 35)) || ((((NU8) (v_p0).p->data[((NI) 0)]) >= ((NU8) 48)) && (((NU8) (v_p0).p->data[((NI) 0)]) <= ((NU8) 57))))))) {
	goto LA7_;
}
			nimln_(42);result = NIM_TRUE;
}
goto LA5_;
LA7_: ;
{
				nimln_(44);result = NIM_FALSE;
}
LA5_: ;
}
goto LA1_;
LA3_: ;
{
			nimln_(46);result = NIM_FALSE;
}
LA1_: ;
}
	BeforeRet_: ;
		popFrame();
	return result;
}

static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
T1_ = ((void*) 0);
T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}

static N_INLINE(void, copyMem__system_u1734)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}

static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
	if ((!((((NI) 0) < src_p1.len)))) {
	goto LA3_;
}
copyMem__system_u1734(((void*) (((&(*(*dest_p0).p).data[(*dest_p0).len])))), ((void*) (((&(*src_p1.p).data[((NI) 0)])))), (src_p1.len));
(*dest_p0).len += src_p1.len;
(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(NimStringV2, newVersion__nimblecmd_u138)(NimStringV2 ver_p0) {
	NimStringV2 result;
NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("newVersion", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
result.len = 0;
result.p = NIM_NIL;
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
	nimln_(32);{
	NIM_BOOL T3_;
NimStringV2 colontmpD__2;
NimStringV2 T7_;
T3_ = ((NIM_BOOL) 0);
T3_ = (ver_p0.len == ((NI) 0));
if (T3_) {
	goto LA4_;
}
if (((((NI) 0) < 0) || (((NI) 0) >= ver_p0.len))) {
	raiseIndexError2(((NI) 0), (ver_p0.len - 1));
	goto BeforeRet_;
}
T3_ = (((((NU8) (ver_p0).p->data[((NI) 0)]) == ((NU8) 0)) || (((NU8) (ver_p0).p->data[((NI) 0)]) == ((NU8) 35))) || ((((NU8) (ver_p0).p->data[((NI) 0)]) >= ((NU8) 48)) && (((NU8) (ver_p0).p->data[((NI) 0)]) <= ((NU8) 57))));
LA4_: ;
if ((!((!(T3_))))) {
	goto LA5_;
}
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
T7_.len = 0;
T7_.p = NIM_NIL;
T7_ = rawNewString((123 + ver_p0.len));
appendString(((&T7_)), TM__asNQM9aynXXg9ccUABbReyew_28);
appendString(((&T7_)), ver_p0);
colontmpD__2 = T7_;
failedAssertImpl__stdZassertions_u76(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__2);
}
LA5_: ;
	nimlf_(34, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");	nimln_(31);	nimln_(34);	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");colontmpD_ = eqdup___system_u2659(ver_p0);
result = colontmpD_;
goto BeforeRet_;
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSpecial__nimblecmd_u172)(NimStringV2 ver_p0) {
	NIM_BOOL result;
NIM_BOOL T1_;
	nimfr_("isSpecial", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
			nimlf_(37, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");	nimln_(36);	nimln_(37);T1_ = ((NIM_BOOL) 0);
T1_ = (((NI) 0) < ver_p0.len);
if ((!(T1_))) {
	goto LA2_;
}
if (((((NI) 0) < 0) || (((NI) 0) >= ver_p0.len))) {
	raiseIndexError2(((NI) 0), (ver_p0.len - 1));
	goto BeforeRet_;
}
T1_ = (((NU8) (ver_p0).p->data[((NI) 0)]) == ((NU8) 35));
LA2_: ;
result = T1_;
goto BeforeRet_;
}
	BeforeRet_: ;
		popFrame();
	return result;
}

static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}

static N_INLINE(NIM_BOOL, equalMem__system_u1742)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
int T1_;
T1_ = ((int) 0);
T1_ = nimCmpMem(a_p0, b_p1, size_p2);
result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
NI alen_1;
NI blen_1;
	nimfr_("eqStrings", "/Users/svacchanda/Dev/Nim/lib/system/strmantle.nim");
{
			nimlf_(33, "/Users/svacchanda/Dev/Nim/lib/system/strmantle.nim");result = NIM_FALSE;
	nimln_(34);alen_1 = a_p0.len;
	nimln_(35);blen_1 = b_p1.len;
	nimln_(36);{
	if ((!((alen_1 == blen_1)))) {
	goto LA3_;
}
		nimln_(37);{
	if ((!((alen_1 == ((NI) 0))))) {
	goto LA7_;
}
			nimln_(32);			nimln_(37);result = NIM_TRUE;
goto BeforeRet_;
}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);result = equalMem__system_u1742(((void*) (((&(a_p0).p->data[((NI) 0)])))), ((void*) (((&(b_p1).p->data[((NI) 0)])))), (alen_1));
goto BeforeRet_;
}
LA3_: ;
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt___nimblecmd_u186)(NimStringV2 ver_p0, NimStringV2 ver2_p1) {
	NIM_BOOL result;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ sVer_1;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ sVer2_1;
NIM_BOOL* nimErr_;
	nimfr_("<", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
result = ((NIM_BOOL) 0);
sVer_1.len = 0;
sVer_1.p = NIM_NIL;
sVer2_1.len = 0;
sVer2_1.p = NIM_NIL;
	nimlf_(50, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");result = NIM_FALSE;
	nimln_(52);{
	NIM_BOOL T4_;
NimStringV2 colontmpD_;
T4_ = ((NIM_BOOL) 0);
T4_ = isSpecial__nimblecmd_u172(ver_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
if (T4_) {
	goto LA5_;
}
T4_ = isSpecial__nimblecmd_u172(ver2_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
LA5_: ;
if ((!(T4_))) {
	goto LA6_;
}
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
		nimln_(53);{
	NIM_BOOL T11_;
NimStringV2 colontmpD__2;
T11_ = ((NIM_BOOL) 0);
T11_ = isSpecial__nimblecmd_u172(ver2_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
if ((!(T11_))) {
	goto LA12_;
}
colontmpD_ = nsuNormalize(ver2_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
T11_ = eqStrings(colontmpD_, TM__asNQM9aynXXg9ccUABbReyew_30);
LA12_: ;
if ((!(T11_))) {
	goto LA13_;
}
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
			nimln_(54);			nimln_(48);			nimln_(54);colontmpD__2 = nsuNormalize(ver_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA15_;
}
result = (!(eqStrings(colontmpD__2, TM__asNQM9aynXXg9ccUABbReyew_31)));
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__2);
eqdestroy___system_u2653(colontmpD_);
			nimln_(2219);eqdestroy___system_u5524(sVer2_1);
eqdestroy___system_u5524(sVer_1);
goto BeforeRet_;
{
	LA15_: ;
}
{
					nimln_(1715);eqdestroy___system_u2653(colontmpD__2);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
}
LA13_: ;
		nimlf_(56, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T20_;
NimStringV2 colontmpD__3;
T20_ = ((NIM_BOOL) 0);
T20_ = isSpecial__nimblecmd_u172(ver2_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
if ((!((!(T20_))))) {
	goto LA21_;
}
colontmpD__3.len = 0;
colontmpD__3.p = NIM_NIL;
			nimln_(58);			nimln_(48);			nimln_(58);colontmpD__3 = nsuNormalize(ver_p0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA23_;
}
result = (!(eqStrings(colontmpD__3, TM__asNQM9aynXXg9ccUABbReyew_32)));
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__3);
eqdestroy___system_u2653(colontmpD_);
			nimln_(2219);eqdestroy___system_u5524(sVer2_1);
eqdestroy___system_u5524(sVer_1);
goto BeforeRet_;
{
	LA23_: ;
}
{
					nimln_(1715);eqdestroy___system_u2653(colontmpD__3);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
}
LA21_: ;
{
	LA8_: ;
}
{
	eqdestroy___system_u2653(colontmpD_);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA6_: ;
	nimlf_(61, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");sVer_1 = nsuSplitChar(ver_p0, 46, ((NI) -1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
	nimln_(62);sVer2_1 = nsuSplitChar(ver2_p1, 46, ((NI) -1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
{
	NI i_1;
NI colontmp_;
NI T29_;
NI T30_;
NI i_2;
i_1 = ((NI) 0);
colontmp_ = ((NI) 0);
		nimlf_(126, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");		nimlf_(63, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");T29_ = sVer_1.len;
T30_ = sVer2_1.len;
colontmp_ = ((T29_ >= T30_) ? T29_ : T30_);
		nimlf_(128, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");i_2 = ((NI) 0);
{
				nimln_(129);while (1) {
	NI sVerI_1;
NI sVerI2_1;
NI TM__asNQM9aynXXg9ccUABbReyew_33;
if ((!((i_2 < colontmp_)))) {
	goto LA32;
}
				nimlf_(63, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");i_1 = i_2;
				nimln_(64);sVerI_1 = ((NI) 0);
				nimln_(65);{
	NI T35_;
NI T38_;
T35_ = sVer_1.len;
if ((!((i_1 < T35_)))) {
	goto LA36_;
}
					nimln_(66);if (((i_1 < 0) || (i_1 >= sVer_1.len))) {
	raiseIndexError2(i_1, (sVer_1.len - 1));
	goto LA1_;
}
T38_ = ((NI) 0);
T38_ = parseInt__pureZparseutils_u989((sVer_1).p->data[i_1], ((&sVerI_1)), ((NI) 0));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
(void)T38_;
}
LA36_: ;
				nimln_(67);sVerI2_1 = ((NI) 0);
				nimln_(68);{
	NI T41_;
NI T44_;
T41_ = sVer2_1.len;
if ((!((i_1 < T41_)))) {
	goto LA42_;
}
					nimln_(69);if (((i_1 < 0) || (i_1 >= sVer2_1.len))) {
	raiseIndexError2(i_1, (sVer2_1.len - 1));
	goto LA1_;
}
T44_ = ((NI) 0);
T44_ = parseInt__pureZparseutils_u989((sVer2_1).p->data[i_1], ((&sVerI2_1)), ((NI) 0));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
(void)T44_;
}
LA42_: ;
				nimln_(70);{
	if ((!((sVerI_1 < sVerI2_1)))) {
	goto LA47_;
}
					nimln_(71);					nimln_(48);					nimln_(71);result = NIM_TRUE;
					nimlf_(2219, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u5524(sVer2_1);
eqdestroy___system_u5524(sVer_1);
goto BeforeRet_;
}
goto LA45_;
LA47_: ;
{
						nimlf_(72, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");if ((!((sVerI_1 == sVerI2_1)))) {
	goto LA50_;
}
}
goto LA45_;
LA50_: ;
{
						nimln_(75);					nimln_(48);					nimln_(75);result = NIM_FALSE;
					nimlf_(2219, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u5524(sVer2_1);
eqdestroy___system_u5524(sVer_1);
goto BeforeRet_;
}
LA45_: ;
				nimlf_(131, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");if (nimAddInt(i_2, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_33))) {
	raiseOverflow();
	goto LA1_;
}
i_2 = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_33));
}
LA32: ;
}
}
{
	LA1_: ;
}
{
			nimlf_(2219, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u5524(sVer2_1);
eqdestroy___system_u5524(sVer_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addPackage__nimblecmd_u247)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg* packages_p1, NimStringV2 p_p2, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p3) {
	tyTuple__7q7q3E6Oj24ZNVJb9aonhAg tmpTuple_1;
NimStringV2 name_1;
NimStringV2 ver_1;
NimStringV2 checksum_1;
NIM_BOOL* nimErr_;
	nimfr_("addPackage", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&tmpTuple_1))), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
name_1.len = 0;
name_1.p = NIM_NIL;
ver_1.len = 0;
ver_1.p = NIM_NIL;
checksum_1.len = 0;
checksum_1.p = NIM_NIL;
	nimlf_(116, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");tmpTuple_1 = getPathVersionChecksum__nimblecmd_u211(p_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
name_1 = tmpTuple_1.Field0;
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&tmpTuple_1.Field0)));
	nimlf_(116, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");ver_1 = tmpTuple_1.Field1;
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&tmpTuple_1.Field1)));
	nimlf_(116, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");checksum_1 = tmpTuple_1.Field2;
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&tmpTuple_1.Field2)));
	nimlf_(117, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T4_;
NimStringV2 version_1;
tyTuple__UV3llMMYFckfui8YMBuUZA colontmpD_;
NimStringV2 colontmpD__2;
T4_ = ((NIM_BOOL) 0);
T4_ = isValidVersion__nimblecmd_u175(ver_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
if ((!(T4_))) {
	goto LA5_;
}
version_1.len = 0;
version_1.p = NIM_NIL;
nimZeroMem(((void*) ((&colontmpD_))), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
		nimln_(118);version_1 = newVersion__nimblecmd_u138(ver_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
		nimln_(119);{
	NIM_BOOL T10_;
NIM_BOOL T12_;
T10_ = ((NIM_BOOL) 0);
colontmpD_ = getOrDefault__nimblecmd_u319((*packages_p1), name_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
colontmpD__2 = newVersion__nimblecmd_u138(colontmpD_.Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
T10_ = lt___nimblecmd_u186(colontmpD__2, version_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
if (T10_) {
	goto LA11_;
}
			nimln_(120);T12_ = ((NIM_BOOL) 0);
T12_ = hasKey__nimblecmd_u799((*packages_p1), name_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
T10_ = (!(T12_));
LA11_: ;
if ((!(T10_))) {
	goto LA13_;
}
			nimln_(121);{
	NIM_BOOL T17_;
tyTuple__UV3llMMYFckfui8YMBuUZA T20_;
NimStringV2 blitTmp_1;
NimStringV2 blitTmp_2;
T17_ = ((NIM_BOOL) 0);
T17_ = isValidSha1Hash__OOZdistZchecksumsZsrcZchecksumsZsha1_u1026(checksum_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
if ((!(T17_))) {
	goto LA18_;
}
				nimln_(122);blitTmp_1 = version_1;
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&version_1)));
T20_.Field0 = blitTmp_1;
				nimlf_(122, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");blitTmp_2 = checksum_1;
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&checksum_1)));
T20_.Field1 = blitTmp_2;
				nimlf_(122, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");X5BX5Deq___nimblecmd_u848(packages_p1, name_1, T20_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
}
goto LA15_;
LA18_: ;
{
	tyTuple__UV3llMMYFckfui8YMBuUZA T22_;
NimStringV2 blitTmp_3;
				nimln_(124);blitTmp_3 = version_1;
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&version_1)));
T22_.Field0 = blitTmp_3;
T22_.Field1 = TM__asNQM9aynXXg9ccUABbReyew_34;
				nimlf_(124, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");X5BX5Deq___nimblecmd_u848(packages_p1, name_1, T22_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
}
LA15_: ;
}
LA13_: ;
{
	LA7_: ;
}
{
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__2);
			nimlf_(31, "/Users/svacchanda/Dev/Nim/lib/std/private/ntpath.nim");eqdestroy___stdZprivateZntpath_u119(colontmpD_);
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(version_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
goto LA2_;
LA5_: ;
{
	NimStringV2 colontmpD__3;
NimStringV2 T27_;
colontmpD__3.len = 0;
colontmpD__3.p = NIM_NIL;
		nimlf_(126, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");T27_.len = 0;
T27_.p = NIM_NIL;
T27_ = rawNewString((22 + p_p2.len));
appendString(((&T27_)), TM__asNQM9aynXXg9ccUABbReyew_36);
appendString(((&T27_)), p_p2);
colontmpD__3 = T27_;
liMessage__msgs_u1213(conf_p0, info_p3, ((tyEnum_TMsgKind__JKNkZ4SkwI4rbqnu3OS3OQ) 17), colontmpD__3, ((tyEnum_TErrorHandling__GRtK9ayzkQ4jQUDEsPFQ2Uw) 0), TM__asNQM9aynXXg9ccUABbReyew_37, NIM_FALSE, NIM_FALSE);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
{
	LA26_: ;
}
{
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__3);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA2_: ;
{
	LA1_: ;
}
{
	eqdestroy___system_u2653(checksum_1);
eqdestroy___system_u2653(ver_1);
eqdestroy___system_u2653(name_1);
		nimlf_(76, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");eqdestroy___stdZprivateZosdirs_u88(tmpTuple_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		popFrame();
}

static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u32)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "/Users/svacchanda/Dev/Nim/lib/pure/collections/hashcommon.nim");
	nimlf_(27, "/Users/svacchanda/Dev/Nim/lib/pure/collections/hashcommon.nim");result = (!((hcode_p0 == ((NI) 0))));
	popFrame();
	return result;
}

static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI) 1));
(*(*s_p0).p).data[(*s_p0).len] = c_p1;
(*s_p0).len += ((NI) 1);
(*(*s_p0).p).data[(*s_p0).len] = 0;
}

N_LIB_PRIVATE N_NIMCALL(void, addNimblePath__nimblecmd_u2173)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 p_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2) {
	NimStringV2 path_1;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimbleLinks_1;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ resultX60gensym40__1;
NIM_BOOL* nimErr_;
	nimfr_("addNimblePath", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
path_1.len = 0;
path_1.p = NIM_NIL;
nimbleLinks_1.len = 0;
nimbleLinks_1.p = NIM_NIL;
resultX60gensym40__1.len = 0;
resultX60gensym40__1.p = NIM_NIL;
	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqcopy___system_u2656(((&path_1)), p_p1);
	nimlf_(946, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");resultX60gensym40__1.len = 0;
resultX60gensym40__1.p = ((tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2)));
{
	NimStringV2 xX60gensym40__1;
NimStringV2 colontmp_;
tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw fX60gensym0__1;
NI resX60gensym0__1;
xX60gensym40__1.len = 0;
xX60gensym40__1.p = NIM_NIL;
colontmp_.len = 0;
colontmp_.p = NIM_NIL;
		nimlf_(97, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");		nimlf_(141, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");colontmp_ = slash___stdZprivateZospaths2_u90(p_p1, TM__asNQM9aynXXg9ccUABbReyew_41);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA3_;
}
nimZeroMem(((void*) ((&fX60gensym0__1))), sizeof(tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw));
resX60gensym0__1 = ((NI) 0);
		nimlf_(64, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");resX60gensym0__1 = findFirstFile__stdZprivateZoscommon_u27(colontmp_, ((&fX60gensym0__1)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA3_;
}
		nimln_(65);{
	NI dotPosX60gensym0__1;
if ((!((!((resX60gensym0__1 == ((NI) -1))))))) {
	goto LA6_;
}
			nimln_(67);dotPosX60gensym0__1 = searchExtPos__stdZprivateZospaths2_u291(colontmp_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
{
					nimln_(68);while (1) {
						nimln_(69);{
	NIM_BOOL T13_;
NIM_BOOL T14_;
NimStringV2 ffX60gensym0__1;
NI idxX60gensym0__1;
NI TM__asNQM9aynXXg9ccUABbReyew_42;
NI TM__asNQM9aynXXg9ccUABbReyew_43;
T13_ = ((NIM_BOOL) 0);
T14_ = ((NIM_BOOL) 0);
T14_ = skipFindData__stdZprivateZoscommon_u36(((&fX60gensym0__1)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
T13_ = (!(T14_));
if ((!(T13_))) {
	goto LA15_;
}
T13_ = NIM_TRUE;
LA15_: ;
if ((!(T13_))) {
	goto LA16_;
}
ffX60gensym0__1.len = 0;
ffX60gensym0__1.p = NIM_NIL;
						nimln_(72);ffX60gensym0__1 = dollar___stdZwidestrs_u394(((NI16*) (((&fX60gensym0__1.cFileName[(((NI) 0) - 0)])))));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
						nimln_(73);if (nimSubInt(ffX60gensym0__1.len, colontmp_.len, (&TM__asNQM9aynXXg9ccUABbReyew_42))) {
	raiseOverflow();
	goto LA8_;
}
if (nimAddInt(((NI) TM__asNQM9aynXXg9ccUABbReyew_42), dotPosX60gensym0__1, (&TM__asNQM9aynXXg9ccUABbReyew_43))) {
	raiseOverflow();
	goto LA8_;
}
idxX60gensym0__1 = ((NI) TM__asNQM9aynXXg9ccUABbReyew_43);
						nimln_(74);{
	NIM_BOOL T20_;
NIM_BOOL T21_;
NIM_BOOL T22_;
NIM_BOOL T25_;
NIM_BOOL T28_;
NIM_BOOL T29_;
NI TM__asNQM9aynXXg9ccUABbReyew_44;
NI TM__asNQM9aynXXg9ccUABbReyew_45;
tyTuple__7q7q3E6Oj24ZNVJb9aonhAg colontmpD_;
NimStringV2 colontmpD__2;
NimStringV2 T34_;
NimStringV2 blitTmp_1;
T20_ = ((NIM_BOOL) 0);
T21_ = ((NIM_BOOL) 0);
T22_ = ((NIM_BOOL) 0);
T22_ = (dotPosX60gensym0__1 < ((NI) 0));
if (T22_) {
	goto LA23_;
}
T22_ = (ffX60gensym0__1.len <= idxX60gensym0__1);
LA23_: ;
T21_ = T22_;
if (T21_) {
	goto LA24_;
}
T25_ = ((NIM_BOOL) 0);
T25_ = (((NI) 0) <= idxX60gensym0__1);
if ((!(T25_))) {
	goto LA26_;
}
if (((idxX60gensym0__1 < 0) || (idxX60gensym0__1 >= ffX60gensym0__1.len))) {
	raiseIndexError2(idxX60gensym0__1, (ffX60gensym0__1.len - 1));
	goto LA8_;
}
T25_ = (((NU8) (ffX60gensym0__1).p->data[idxX60gensym0__1]) == ((NU8) 46));
LA26_: ;
T21_ = T25_;
LA24_: ;
T20_ = T21_;
if (T20_) {
	goto LA27_;
}
							nimln_(75);T28_ = ((NIM_BOOL) 0);
T29_ = ((NIM_BOOL) 0);
T29_ = (((NI) 0) <= dotPosX60gensym0__1);
if ((!(T29_))) {
	goto LA30_;
}
if (nimAddInt(dotPosX60gensym0__1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_44))) {
	raiseOverflow();
	goto LA8_;
}
T29_ = (((NI) TM__asNQM9aynXXg9ccUABbReyew_44) < colontmp_.len);
LA30_: ;
T28_ = T29_;
if ((!(T28_))) {
	goto LA31_;
}
if (nimAddInt(dotPosX60gensym0__1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_45))) {
	raiseOverflow();
	goto LA8_;
}
if (((((NI) TM__asNQM9aynXXg9ccUABbReyew_45) < 0) || (((NI) TM__asNQM9aynXXg9ccUABbReyew_45) >= colontmp_.len))) {
	raiseIndexError2(((NI) TM__asNQM9aynXXg9ccUABbReyew_45), (colontmp_.len - 1));
	goto LA8_;
}
T28_ = (((NU8) (colontmp_).p->data[((NI) TM__asNQM9aynXXg9ccUABbReyew_45)]) == ((NU8) 42));
LA31_: ;
T20_ = T28_;
LA27_: ;
if ((!(T20_))) {
	goto LA32_;
}
nimZeroMem(((void*) ((&colontmpD_))), sizeof(tyTuple__7q7q3E6Oj24ZNVJb9aonhAg));
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");							nimlf_(947, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");							nimlf_(76, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");colontmpD_ = nossplitFile(colontmp_);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
colontmpD__2 = nosextractFilename(ffX60gensym0__1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
							nimlf_(947, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");T34_.len = 0;
T34_.p = NIM_NIL;
T34_ = slash___stdZprivateZospaths2_u90(colontmpD_.Field0, colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___system_u2653(T34_);
	goto LA8_;
}
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&xX60gensym40__1)), T34_);
							nimlf_(948, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");blitTmp_1 = xX60gensym40__1;
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&xX60gensym40__1)));
							nimlf_(948, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");add__stdZenumutils_u71(((&resultX60gensym40__1)), blitTmp_1);
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__2);
							nimlf_(76, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");eqdestroy___stdZprivateZosdirs_u88(colontmpD_);
}
LA32_: ;
						nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(ffX60gensym0__1);
}
LA16_: ;
					nimlf_(77, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");{
	NI32 T37_;
NI32 errCodeX60gensym0__1;
T37_ = ((NI32) 0);
T37_ = Dl_1392509182_(resX60gensym0__1, ((&fX60gensym0__1)));
if ((!((T37_ == ((NI32) 0))))) {
	goto LA38_;
}
						nimln_(78);errCodeX60gensym0__1 = Dl_1392509099_();
						nimln_(79);{
	if ((!((errCodeX60gensym0__1 == ((NI32) 18))))) {
	goto LA42_;
}
goto LA9;
}
goto LA40_;
LA42_: ;
{
								nimln_(80);raiseOSError__stdZoserrors_u123(errCodeX60gensym0__1, TM__asNQM9aynXXg9ccUABbReyew_46);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA8_;
}
}
LA40_: ;
}
LA38_: ;
}
}
LA9: ;
{
	LA8_: ;
}
{
					nimln_(66);Dl_1392509185_(resX60gensym0__1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA3_;
}
}
LA6_: ;
{
	LA3_: ;
}
{
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmp_);
eqdestroy___system_u2653(xX60gensym40__1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
	nimlf_(141, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");	nimlf_(949, "/Users/svacchanda/Dev/Nim/lib/pure/collections/sequtils.nim");nimbleLinks_1 = resultX60gensym40__1;
	nimlf_(2219, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u5521(((&resultX60gensym40__1)));
	nimlf_(142, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NI T51_;
tySequence__sM4lkSb7zS6F7OVMvW9cffQ nimbleLinkLines_1;
NimStringV2 colontmpD__3;
T51_ = nimbleLinks_1.len;
if ((!((((NI) 0) < T51_)))) {
	goto LA52_;
}
nimbleLinkLines_1.len = 0;
nimbleLinkLines_1.p = NIM_NIL;
colontmpD__3.len = 0;
colontmpD__3.p = NIM_NIL;
		nimln_(146);if (((((NI) 0) < 0) || (((NI) 0) >= nimbleLinks_1.len))) {
	raiseIndexError2(((NI) 0), (nimbleLinks_1.len - 1));
	goto LA54_;
}
colontmpD__3 = readFile__stdZsyncio_u625((nimbleLinks_1).p->data[((NI) 0)]);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA54_;
}
nimbleLinkLines_1 = nsuSplitLines(colontmpD__3, NIM_FALSE);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA54_;
}
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");if (((((NI) 1) < 0) || (((NI) 1) >= nimbleLinkLines_1.len))) {
	raiseIndexError2(((NI) 1), (nimbleLinkLines_1.len - 1));
	goto LA54_;
}
eqsink___system_u2662(((&path_1)), (nimbleLinkLines_1).p->data[((NI) 1)]);
if (((((NI) 1) < 0) || (((NI) 1) >= nimbleLinkLines_1.len))) {
	raiseIndexError2(((NI) 1), (nimbleLinkLines_1.len - 1));
	goto LA54_;
}
eqwasMoved___system_u2650(((&(nimbleLinkLines_1).p->data[((NI) 1)])));
		nimlf_(148, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T57_;
NimStringV2 T60_;
T57_ = ((NIM_BOOL) 0);
T57_ = nosisAbsolute(path_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA54_;
}
if ((!((!(T57_))))) {
	goto LA58_;
}
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");			nimlf_(149, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");T60_.len = 0;
T60_.p = NIM_NIL;
T60_ = slash___stdZprivateZospaths2_u90(p_p1, path_1);
if (NIM_UNLIKELY((*nimErr_))) {
	eqdestroy___system_u2653(T60_);
	goto LA54_;
}
			nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&path_1)), T60_);
}
LA58_: ;
{
	LA54_: ;
}
{
	eqdestroy___system_u2653(colontmpD__3);
			nimln_(2219);eqdestroy___system_u5524(nimbleLinkLines_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
LA52_: ;
	nimlf_(151, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T65_;
NimStringV2 blitTmp_2;
T65_ = ((NIM_BOOL) 0);
T65_ = contains__nimblecmd_u17((((*conf_p0).searchPaths).p ? ((*conf_p0).searchPaths).p->data : NIM_NIL), (*conf_p0).searchPaths.len, path_1);
if ((!((!(T65_))))) {
	goto LA66_;
}
		nimln_(152);liMessage__msgs_u1213(conf_p0, info_p2, ((tyEnum_TMsgKind__JKNkZ4SkwI4rbqnu3OS3OQ) 103), path_1, ((tyEnum_TErrorHandling__GRtK9ayzkQ4jQUDEsPFQ2Uw) 0), TM__asNQM9aynXXg9ccUABbReyew_47, NIM_FALSE, NIM_FALSE);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
		nimln_(153);blitTmp_2 = path_1;
		nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&path_1)));
		nimlf_(153, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");insert__nimblecmd_u52(((&(*conf_p0).lazyPaths)), blitTmp_2, ((NI) 0));
}
LA66_: ;
{
	LA1_: ;
}
{
			nimlf_(2219, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u5524(resultX60gensym40__1);
eqdestroy___system_u5524(nimbleLinks_1);
		nimln_(1715);eqdestroy___system_u2653(path_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addPathRec__nimblecmd_u2208)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 dir_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2) {
	tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg packages_1;
NI pos_1;
NI TM__asNQM9aynXXg9ccUABbReyew_3;
NIM_BOOL* nimErr_;
	nimfr_("addPathRec", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
nimZeroMem(((void*) ((&packages_1))), sizeof(tyObject_Table__Cp5nZmwfgh2szAeTBBlZcg));
	nimlf_(156, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");packages_1 = initTable__nimblecmd_u2226(((NI) 32));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
	nimln_(157);if (nimSubInt(dir_p1.len, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_3))) {
	raiseOverflow();
	goto LA1_;
}
pos_1 = ((NI) TM__asNQM9aynXXg9ccUABbReyew_3);
	nimln_(158);{
	NI TM__asNQM9aynXXg9ccUABbReyew_4;
if (((pos_1 < 0) || (pos_1 >= dir_p1.len))) {
	raiseIndexError2(pos_1, (dir_p1.len - 1));
	goto LA1_;
}
if ((!(((((NU8) (dir_p1).p->data[pos_1]) == ((NU8) 92)) || (((NU8) (dir_p1).p->data[pos_1]) == ((NU8) 47)))))) {
	goto LA4_;
}
if (nimAddInt(pos_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_4))) {
	raiseOverflow();
	goto LA1_;
}
pos_1 = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_4));
}
LA4_: ;
{
	NimStringV2 p_1;
NimStringV2 colontmpD_;
tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw k_1;
tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw f_1;
NI h_1;
p_1.len = 0;
p_1.p = NIM_NIL;
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
k_1 = ((tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw) 0);
nimZeroMem(((void*) ((&f_1))), sizeof(tyObject_WIN32_FIND_DATA__iITRHan9bAM01ZPwDDnuz9aw));
		nimlf_(201, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");colontmpD_ = slash___stdZprivateZospaths2_u90(dir_p1, TM__asNQM9aynXXg9ccUABbReyew_6);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
h_1 = findFirstFile__stdZprivateZoscommon_u27(colontmpD_, ((&f_1)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
		nimln_(202);{
	if ((!((h_1 == ((NI) -1))))) {
	goto LA10_;
}
			nimln_(203);{
	NI32 T16_;
if ((!(NIM_FALSE))) {
	goto LA14_;
}
				nimln_(204);T16_ = ((NI32) 0);
T16_ = osLastError__stdZoserrors_u126();
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
raiseOSError__stdZoserrors_u123(T16_, dir_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
}
LA14_: ;
}
goto LA8_;
LA10_: ;
{
	{
					nimln_(207);while (1) {
	tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw k_2;
					nimln_(208);k_2 = ((tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw) 0);
					nimln_(209);{
	NIM_BOOL T23_;
NimStringV2 xx_1;
NimStringV2 T35_;
T23_ = ((NIM_BOOL) 0);
T23_ = skipFindData__stdZprivateZoscommon_u36(((&f_1)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA18_;
}
if ((!((!(T23_))))) {
	goto LA24_;
}
xx_1.len = 0;
xx_1.p = NIM_NIL;
						nimln_(210);{
	if ((!((!((((NI32) (f_1.dwFileAttributes & ((NI32) 16))) == ((NI32) 0))))))) {
	goto LA29_;
}
							nimln_(211);k_2 = ((tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw) 2);
}
LA29_: ;
						nimln_(212);{
	NI TM__asNQM9aynXXg9ccUABbReyew_7;
if ((!((!((((NI32) (f_1.dwFileAttributes & ((NI32) 1024))) == ((NI32) 0))))))) {
	goto LA33_;
}
							nimln_(213);if (nimAddInt(k_2, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_7))) {
	raiseOverflow();
	goto LA26_;
}
if (((TM__asNQM9aynXXg9ccUABbReyew_7 < 0) || (TM__asNQM9aynXXg9ccUABbReyew_7 > 3))) {
	raiseOverflow();
	goto LA26_;
}
k_2 = ((tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw) TM__asNQM9aynXXg9ccUABbReyew_7);
}
LA33_: ;
T35_.len = 0;
T35_.p = NIM_NIL;
						nimln_(214);{
	NimStringV2 colontmpD__2;
if ((!(NIM_FALSE))) {
	goto LA38_;
}
colontmpD__2.len = 0;
colontmpD__2.p = NIM_NIL;
colontmpD__2 = dollar___stdZwidestrs_u394(((NI16*) (((&f_1.cFileName[(((NI) 0) - 0)])))));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
xx_1 = nosextractFilename(colontmpD__2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__2);
}
goto LA36_;
LA38_: ;
{
	NimStringV2 colontmpD__3;
NimStringV2 colontmpD__4;
colontmpD__3.len = 0;
colontmpD__3.p = NIM_NIL;
colontmpD__4.len = 0;
colontmpD__4.p = NIM_NIL;
							nimlf_(214, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");							nimln_(215);colontmpD__3 = dollar___stdZwidestrs_u394(((NI16*) (((&f_1.cFileName[(((NI) 0) - 0)])))));
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
colontmpD__4 = nosextractFilename(colontmpD__3);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
xx_1 = slash___stdZprivateZospaths2_u90(dir_p1, colontmpD__4);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD__4);
eqdestroy___system_u2653(colontmpD__3);
}
LA36_: ;
						nimlf_(159, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");k_1 = k_2;
						nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqsink___system_u2662(((&p_1)), xx_1);
eqwasMoved___system_u2650(((&xx_1)));
						nimlf_(160, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	NIM_BOOL T43_;
T43_ = ((NIM_BOOL) 0);
T43_ = (k_1 == ((tyEnum_PathComponent__9bWgleKuoe8hcUVGbQCXxiw) 2));
if ((!(T43_))) {
	goto LA44_;
}
if (((pos_1 < 0) || (pos_1 >= p_1.len))) {
	raiseIndexError2(pos_1, (p_1.len - 1));
	goto LA26_;
}
T43_ = (!((((NU8) (p_1).p->data[pos_1]) == ((NU8) 46))));
LA44_: ;
if ((!(T43_))) {
	goto LA45_;
}
							nimln_(161);addPackage__nimblecmd_u247(conf_p0, ((&packages_1)), p_1, info_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA26_;
}
}
LA45_: ;
{
	LA26_: ;
}
{
								nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(xx_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA18_;
}
}
LA24_: ;
					nimlf_(217, "/Users/svacchanda/Dev/Nim/lib/std/private/osdirs.nim");{
	NI32 T51_;
NI32 errCode_1;
T51_ = ((NI32) 0);
T51_ = Dl_1392509182_(h_1, ((&f_1)));
if ((!((T51_ == ((NI32) 0))))) {
	goto LA52_;
}
						nimln_(218);errCode_1 = Dl_1392509099_();
						nimln_(219);{
	if ((!((errCode_1 == ((NI32) 18))))) {
	goto LA56_;
}
goto LA19;
}
goto LA54_;
LA56_: ;
{
								nimln_(220);raiseOSError__stdZoserrors_u123(errCode_1, TM__asNQM9aynXXg9ccUABbReyew_39);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA18_;
}
}
LA54_: ;
}
LA52_: ;
}
}
LA19: ;
{
	LA18_: ;
}
{
					nimln_(206);Dl_1392509185_(h_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA7_;
}
}
LA8_: ;
{
	LA7_: ;
}
{
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(colontmpD_);
eqdestroy___system_u2653(p_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
{
	NimStringV2 p_2;
p_2.len = 0;
p_2.p = NIM_NIL;
{
	NimStringV2 key_1;
tyTuple__UV3llMMYFckfui8YMBuUZA val_1;
NI L_1;
key_1.len = 0;
key_1.p = NIM_NIL;
nimZeroMem(((void*) ((&val_1))), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
			nimlf_(767, "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim");L_1 = len__nimblecmd_u1915(packages_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA65_;
}
{
	NI h_2;
NI colontmp_;
NI T67_;
NI res_1;
h_2 = ((NI) 0);
colontmp_ = ((NI) 0);
				nimlf_(81, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");				nimlf_(768, "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim");T67_ = (packages_1.data.len - 1);
colontmp_ = T67_;
				nimlf_(96, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");res_1 = ((NI) 0);
{
						nimln_(97);while (1) {
	NI TM__asNQM9aynXXg9ccUABbReyew_50;
if ((!((res_1 <= colontmp_)))) {
	goto LA69;
}
						nimlf_(768, "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim");h_2 = ((NI) (res_1));
						nimln_(769);{
	NIM_BOOL T72_;
tyTuple__UV3llMMYFckfui8YMBuUZA colontmpD__5;
NimStringV2 res_2;
if (((h_2 < 0) || (h_2 >= packages_1.data.len))) {
	raiseIndexError2(h_2, (packages_1.data.len - 1));
	goto LA65_;
}
T72_ = ((NIM_BOOL) 0);
T72_ = isFilled__pureZcollectionsZtables_u32((packages_1.data).p->data[h_2].Field0);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA65_;
}
if ((!(T72_))) {
	goto LA73_;
}
nimZeroMem(((void*) ((&colontmpD__5))), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
res_2.len = 0;
res_2.p = NIM_NIL;
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");if (((h_2 < 0) || (h_2 >= packages_1.data.len))) {
	raiseIndexError2(h_2, (packages_1.data.len - 1));
	goto LA75_;
}
eqcopy___system_u2656(((&key_1)), (packages_1.data).p->data[h_2].Field1);
							nimlf_(31, "/Users/svacchanda/Dev/Nim/lib/std/private/ntpath.nim");							nimlf_(770, "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim");							nimlf_(31, "/Users/svacchanda/Dev/Nim/lib/std/private/ntpath.nim");if (((h_2 < 0) || (h_2 >= packages_1.data.len))) {
	raiseIndexError2(h_2, (packages_1.data.len - 1));
	goto LA75_;
}
colontmpD__5 = eqdup___stdZprivateZntpath_u125((packages_1.data).p->data[h_2].Field2);
eqsink___stdZprivateZntpath_u128(((&val_1)), colontmpD__5);
							nimlf_(130, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");res_2 = key_1;
							nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqwasMoved___system_u2650(((&key_1)));
							nimlf_(131, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");{
	if ((!((!((val_1.Field0.len == ((NI) 0))))))) {
	goto LA78_;
}
								nimln_(132);nimAddCharV1(((&res_2)), 45);
								nimln_(133);prepareAdd(((&res_2)), (0 + val_1.Field0.len));
appendString(((&res_2)), val_1.Field0);
}
LA78_: ;
							nimln_(134);{
	if ((!((!((val_1.Field1.len == ((NI) 0))))))) {
	goto LA82_;
}
								nimln_(135);nimAddCharV1(((&res_2)), 45);
								nimln_(136);prepareAdd(((&res_2)), (0 + val_1.Field1.len));
appendString(((&res_2)), val_1.Field1);
}
LA82_: ;
							nimln_(162);p_2 = res_2;
							nimln_(163);addNimblePath__nimblecmd_u2173(conf_p0, p_2, info_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA75_;
}
							nimlf_(771, "/Users/svacchanda/Dev/Nim/lib/pure/collections/tables.nim");{
	NI T86_;
T86_ = ((NI) 0);
T86_ = len__nimblecmd_u1915(packages_1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA75_;
}
if ((!((!((T86_ == L_1)))))) {
	goto LA87_;
}
failedAssertImpl__stdZassertions_u76(TM__asNQM9aynXXg9ccUABbReyew_49);
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA75_;
}
}
LA87_: ;
{
	LA75_: ;
}
{
									nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(res_2);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA65_;
}
}
LA73_: ;
						nimlf_(102, "/Users/svacchanda/Dev/Nim/lib/system/iterators_1.nim");if (nimAddInt(res_1, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_50))) {
	raiseOverflow();
	goto LA65_;
}
res_1 = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_50));
}
LA69: ;
}
}
{
	LA65_: ;
}
{
					nimlf_(31, "/Users/svacchanda/Dev/Nim/lib/std/private/ntpath.nim");eqdestroy___stdZprivateZntpath_u119(val_1);
				nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");eqdestroy___system_u2653(key_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto LA1_;
}
}
}
{
	LA1_: ;
}
{
			nimlf_(129, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");eqdestroy___nimblecmd_u2155(packages_1);
}
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
		popFrame();
}

static N_INLINE(NI, find__nimblecmd_u2266)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ a_p0, NimStringV2 item_p1) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("find", "/Users/svacchanda/Dev/Nim/lib/system.nim");
{
		nimErr_ = nimErrorFlag();
	nimlf_(1918, "/Users/svacchanda/Dev/Nim/lib/system.nim");result = ((NI) 0);
{
	NimStringV2* i_1;
NI i_2;
NI L_1;
NI T2_;
i_1 = ((NimStringV2*) 0);
		nimlf_(249, "/Users/svacchanda/Dev/Nim/lib/system/iterators.nim");i_2 = ((NI) 0);
		nimln_(250);T2_ = a_p0.len;
L_1 = T2_;
{
				nimln_(251);while (1) {
	NI TM__asNQM9aynXXg9ccUABbReyew_51;
if ((!((i_2 < L_1)))) {
	goto LA4;
}
				nimlf_(1919, "/Users/svacchanda/Dev/Nim/lib/system.nim");if (((i_2 < 0) || (i_2 >= a_p0.len))) {
	raiseIndexError2(i_2, (a_p0.len - 1));
	goto BeforeRet_;
}
i_1 = ((&(a_p0).p->data[i_2]));
				nimln_(1920);{
	NIM_BOOL T7_;
T7_ = ((NIM_BOOL) 0);
T7_ = eqeq___nimblecmd_u42((*i_1), item_p1);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
if ((!(T7_))) {
	goto LA8_;
}
goto BeforeRet_;
}
LA8_: ;
				nimln_(1921);if (nimAddInt(result, ((NI) 1), (&TM__asNQM9aynXXg9ccUABbReyew_51))) {
	raiseOverflow();
	goto BeforeRet_;
}
result = ((NI) (TM__asNQM9aynXXg9ccUABbReyew_51));
				nimlf_(13, "/Users/svacchanda/Dev/Nim/lib/system/iterators.nim");i_2 += ((NI) 1);
				nimln_(254);{
	NI T12_;
T12_ = a_p0.len;
if ((!((!((T12_ == L_1)))))) {
	goto LA13_;
}
failedAssertImpl__stdZassertions_u76(TM__asNQM9aynXXg9ccUABbReyew_53);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA13_: ;
}
LA4: ;
}
}
	nimlf_(1922, "/Users/svacchanda/Dev/Nim/lib/system.nim");result = ((NI) -1);
}
	BeforeRet_: ;
		popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, nimblePath__nimblecmd_u2262)(tyObject_ConfigRefcolonObjectType___irn5iEV4uSDc0UNz3HdP4g* conf_p0, NimStringV2 path_p1, tyObject_TLineInfo__oUG2bM4Le2s6K3lPXxWvEw info_p2) {
	NimStringV2 colontmpD_;
NI i_1;
NIM_BOOL* nimErr_;
	nimfr_("nimblePath", "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");
{
		nimErr_ = nimErrorFlag();
colontmpD_.len = 0;
colontmpD_.p = NIM_NIL;
	nimlf_(166, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");addPathRec__nimblecmd_u2208(conf_p0, path_p1, info_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
	nimln_(167);addNimblePath__nimblecmd_u2173(conf_p0, path_p1, info_p2);
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
	nimln_(168);i_1 = find__nimblecmd_u2266((*conf_p0).nimblePaths, path_p1);
	nimln_(169);{
	if ((!((!((i_1 == ((NI) -1))))))) {
	goto LA3_;
}
		nimln_(170);if (((i_1 < ((NI) 0)) || (i_1 > ((NI) 2147483647)))) {
	raiseRangeErrorI(i_1, ((NI) 0), ((NI) 2147483647));
	goto BeforeRet_;
}
delete__nimblecmd_u2286(((&(*conf_p0).nimblePaths)), (i_1));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
LA3_: ;
	nimln_(171);	nimlf_(1715, "/Users/svacchanda/Dev/Nim/lib/system.nim");colontmpD_ = eqdup___system_u2659(path_p1);
	nimlf_(171, "/Users/svacchanda/Dev/Nim/compiler/nimblecmd.nim");insert__nimblecmd_u52(((&(*conf_p0).nimblePaths)), colontmpD_, ((NI) 0));
}
	BeforeRet_: ;
		popFrame();
}

