/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg;
typedef struct tyObject_TContext__7o25R1eLhZZP3xzfuqE0OA tyObject_TContext__7o25R1eLhZZP3xzfuqE0OA;
typedef struct tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ;
typedef struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ;
typedef struct tyTuple__WC8oWjU9ba3bRWtrpDsnEQw tyTuple__WC8oWjU9ba3bRWtrpDsnEQw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef N_NIMCALL_PTR(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg*, tyProc__6sDDL9acn0CXuaVjW0cIXWg) (tyObject_TContext__7o25R1eLhZZP3xzfuqE0OA* c_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__WC8oWjU9ba3bRWtrpDsnEQw {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
	tyProc__6sDDL9acn0CXuaVjW0cIXWg Field3;
};
typedef tyTuple__WC8oWjU9ba3bRWtrpDsnEQw tyArray__f7zUyCqL9bUB9cjFYO1PwXlA[2];
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg*, iterToProcImpl__pluginsZitersgen_u7)(tyObject_TContext__7o25R1eLhZZP3xzfuqE0OA* c_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg*, semLocals__pluginsZlocals_u7)(tyObject_TContext__7o25R1eLhZZP3xzfuqE0OA* c_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pluginMatches__pluginsupport_u18)(tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ* ic_p0, tyTuple__WC8oWjU9ba3bRWtrpDsnEQw* p_p1, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* s_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4479)(void);
static N_INLINE(void, popFrame)(void);
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__UiphbyIkFgNr76Jpl4n42w_2 = { 6 | NIM_STRLIT_FLAG, "stdlib" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__UiphbyIkFgNr76Jpl4n42w_3 = { 6 | NIM_STRLIT_FLAG, "system" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__UiphbyIkFgNr76Jpl4n42w_4 = { 10 | NIM_STRLIT_FLAG, "iterToProc" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__UiphbyIkFgNr76Jpl4n42w_5 = { 6 | NIM_STRLIT_FLAG, "locals" };
N_LIB_PRIVATE NIM_CONST tyArray__f7zUyCqL9bUB9cjFYO1PwXlA plugins__pluginsZactive_u6 = {{{6, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_2},
{6, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_3},
{10, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_4},
iterToProcImpl__pluginsZitersgen_u7}
,
{{6, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_2},
{6, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_3},
{6, (NimStrPayload*)&TM__UiphbyIkFgNr76Jpl4n42w_5},
semLocals__pluginsZlocals_u7}
}
;
extern NIM_BOOL nimInErrorMode__system_u4261;
extern TFrame* framePtr__system_u2667;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4261);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4479();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyProc__6sDDL9acn0CXuaVjW0cIXWg, getPlugin__pluginsZactive_u7)(tyObject_IdentCachecolonObjectType___WuCY09aDmf8N6jKp7krOoTQ* ic_p0, tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* fn_p1) {
	tyProc__6sDDL9acn0CXuaVjW0cIXWg result;
NIM_BOOL* nimErr_;
	nimfr_("getPlugin", "/Users/svacchanda/Dev/nimv2/compiler/plugins/active.nim");
{nimErr_ = nimErrorFlag();
	{
		tyTuple__WC8oWjU9ba3bRWtrpDsnEQw p_1;
		NI i_1;
		nimZeroMem((void*)(&p_1), sizeof(tyTuple__WC8oWjU9ba3bRWtrpDsnEQw));
		nimlf_(43, "/opt/local/lib/nim/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(22, "/Users/svacchanda/Dev/nimv2/compiler/plugins/active.nim");				p_1 = plugins__pluginsZactive_u6[(i_1)- 0];
				nimln_(23);				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = pluginMatches__pluginsupport_u18(ic_p0, (&p_1), fn_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					nimln_(21);					nimln_(23);					result = p_1.Field3;
					goto BeforeRet_;
				}
LA7_: ;
				nimlf_(46, "/opt/local/lib/nim/lib/system/iterators.nim");				{
					if (!(((NI)1) <= i_1)) goto LA11_;
					goto LA2;
				}
LA11_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA2: ;
	}
	nimlf_(24, "/Users/svacchanda/Dev/nimv2/compiler/plugins/active.nim");	nimln_(21);	nimln_(24);	result = NIM_NIL;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
