/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg;
typedef struct tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg;
typedef struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ;
typedef struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ;
typedef struct tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw;
typedef struct tySequence__aoeG9bufSTIRNZegac1FEcg tySequence__aoeG9bufSTIRNZegac1FEcg;
typedef struct tySequence__aoeG9bufSTIRNZegac1FEcg_Content tySequence__aoeG9bufSTIRNZegac1FEcg_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA;
typedef struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA;
typedef struct tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ {
	NU16 line;
	NI16 col;
	NI32 fileIndex;
};
typedef NU32 tySet_tyEnum_TNodeFlag__FhgPNE64ZbubRzUYw37NSA;
typedef NU8 tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ;
struct tySequence__aoeG9bufSTIRNZegac1FEcg {
  NI len; tySequence__aoeG9bufSTIRNZegac1FEcg_Content* p;
};
struct tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg {
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typField;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info;
	tySet_tyEnum_TNodeFlag__FhgPNE64ZbubRzUYw37NSA flags;
	tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ kind;
union{
	struct {
	NI64 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* sym;
} _kind_4;
	struct {
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* ident;
} _kind_5;
	struct {
	tySequence__aoeG9bufSTIRNZegac1FEcg sons;
} _kind_6;
};
};
typedef NU8 tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ[21];
struct tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw {
	NI id;
	NimStringV2 s;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* next;
	NI h;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tyEnum_TPreferedDesc__ZPp9cjDDLuuf5JrmkQzA5gQ;
struct tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA {
	NI32 module;
	NI32 item;
};
typedef NU8 tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ;
typedef NU16 tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ;
typedef NU64 tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw;
typedef NU32 tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg;
typedef NU8 tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw;
typedef NU8 tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ;
typedef NU16 tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ;
struct tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA {
	tyEnum_TLocKind__spbsYMH9akLHt89ayQRkefgw k;
	tyEnum_TStorageLoc__r9cBmHG1jM9cMcNjP2TxFu9bQ storage;
	tySet_tyEnum_TLocFlag__tKn0yBGWnE0HuakUsP39aEQ flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* lode;
	NimStringV2 snippet;
};
struct tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ {
	tyObject_ItemId__MWa4q2Yec3WbfwdTGok2qA itemId;
	tyEnum_TSymKind__6yn5fRrOKz9cfdnI3EMEIuQ kind;
union{
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* gcUnsafetyReason;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* transformedBody;
} _kind_1;
	struct {
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* guard;
	NI bitsize;
	NI alignment;
} _kind_2;
};
	tyEnum_TMagic__aO8S9b9b69ab584i9bBGW9abWcQ magic;
	tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ;
	tyObject_TIdent__TgS4DVxBWxH1nCMTH4oGgw* name;
	tyObject_TLineInfo__20X1VdZ9aU0ckVGBxHntCQQ info;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* ownerField;
	tySet_tyEnum_TSymFlag__lsEkQHwNKhrJlO9aaOKmAtw flags;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* ast;
	tySet_tyEnum_TOption__2zJpgpZdccA3cOjwzONcgg options;
	NI position;
	NI32 offset;
	NI32 disamb;
	tyObject_TLoc__Nd1Ib5kJzOP9c5R34dDMFPA loc;
	tyObject_TLib__SWO2Ytr9bJNBtS4VkPI3KCA* annex;
	tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* constraint;
	tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* instantiatedFrom;
};
struct tySequence__aoeG9bufSTIRNZegac1FEcg_Content { NI cap; tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderPlainSymbolName__typesrenderer_u9)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___nodekinds_u168)(tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
static N_INLINE(NI, len__ast_u3197)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4516)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2632)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderDefinitionName__renderer_u125)(tyObject_TSym__P20oQ2ehYnPErV5x8ASQ9cQ* s_p0, NIM_BOOL noQuotes_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, renderParamTypes__typesrenderer_u121)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* found_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1, NIM_BOOL toNormalize_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u242)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderType__typesrenderer_u12)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, NIM_BOOL toNormalize_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__pureZstrutils_u124)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, typeToString__types_u54)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ_p0, tyEnum_TPreferedDesc__ZPp9cjDDLuuf5JrmkQzA5gQ prefer_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u2629)(NimStringV2 dest_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3264)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg** dest_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
static N_INLINE(void, X5BX5Deq___system_u7919)(NimStringV2* s_p0, NI i_p1, NIM_CHAR x_p2);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2378)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3261)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_u3390)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg** dest_p0, tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2638)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_u3387)(tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u71)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2635)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___renderer_u2165)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3755)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2626)(NimStringV2* dest_p0);
static NIM_CONST tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ TM__SgHDIVcSir4dkKoe0Xsi0A_2 = {
0xec, 0xff, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[62+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_3 = { 62 | NIM_STRLIT_FLAG, "field \'sons\' is not accessible for type \'TNode\' using \'kind = " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_4 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_5 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static NIM_CONST tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ TM__SgHDIVcSir4dkKoe0Xsi0A_7 = {
0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[63+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_8 = { 63 | NIM_STRLIT_FLAG, "field \'ident\' is not accessible for type \'TNode\' using \'kind = " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_9 = {63, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_8};
static NIM_CONST tySet_tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ TM__SgHDIVcSir4dkKoe0Xsi0A_10 = {
0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[61+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_11 = { 61 | NIM_STRLIT_FLAG, "field \'sym\' is not accessible for type \'TNode\' using \'kind = " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_12 = {61, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_11};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_13 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_14 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_15 = {0, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_14};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_16 = {0, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_14};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_17 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[77+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_20 = { 77 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(131, 5) `typePos > 0` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_21 = {77, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_20};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_22 = {63, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_8};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_23 = {63, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_8};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_24 = {61, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_11};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_25 = {61, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_11};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_26 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_27 = { 3 | NIM_STRLIT_FLAG, "var" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_28 = {3, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_27};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_29 = { 4 | NIM_STRLIT_FLAG, "ref." };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_30 = {4, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_29};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_32 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_33 = { 3 | NIM_STRLIT_FLAG, "ref" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_34 = {3, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_33};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_35 = { 4 | NIM_STRLIT_FLAG, "ptr." };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_36 = {4, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_35};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_37 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_38 = { 3 | NIM_STRLIT_FLAG, "ptr" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_39 = {3, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_38};
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_40 = { 75 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(67, 5) `n.len != 1` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_41 = {75, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_40};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_42 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_43 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[79+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_44 = { 79 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(70, 7) `params.len > 0` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_45 = {79, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_44};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_46 = { 5 | NIM_STRLIT_FLAG, "proc(" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_47 = {5, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_46};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_48 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_52 = { 4 | NIM_STRLIT_FLAG, "proc" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_53 = {4, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_52};
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_54 = { 75 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(77, 5) `n.len >= 3` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_55 = {75, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_54};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_57 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_58 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[94+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_59 = { 94 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(82, 7) `n[i].kind in {nkSym, nkIdent}` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_60 = {94, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_59};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_62 = { 6 | NIM_STRLIT_FLAG, "tuple[" };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_63 = {6, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_62};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_64 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[75+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_66 = { 75 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(89, 5) `n.len >= 2` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_67 = {75, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_66};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_68 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_69 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_71 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_72 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_73 = {2, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_72};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_74 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_76 = {0, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_14};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_77 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_78 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_80 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_83 = { 90 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(104, 3) `n.kind == nkFormalParams` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_84 = {90, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_83};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_85 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_86 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_88 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_89 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_90 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_91 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_93 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__SgHDIVcSir4dkKoe0Xsi0A_95 = { 90 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim(159, 3) `n.kind == nkFormalParams` " };
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_96 = {90, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_95};
static const NimStringV2 TM__SgHDIVcSir4dkKoe0Xsi0A_97 = {62, (NimStrPayload*)&TM__SgHDIVcSir4dkKoe0Xsi0A_3};
extern TFrame* framePtr__system_u2667;
extern NIM_BOOL nimInErrorMode__system_u4298;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4516();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
static N_INLINE(NI, len__ast_u3197)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NI result;
	NI T1_;
	nimfr_("len", "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");
{	nimlf_(1008, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");	if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 	{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_5, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
	}
	T1_ = (*n_p0)._kind_6.sons.len;
	result = T1_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4298);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderPlainSymbolName__typesrenderer_u9)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("renderPlainSymbolName", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(31, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");	switch ((*n_p0).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)31):
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)53):
	{
		NI T2_;
		NI TM__SgHDIVcSir4dkKoe0Xsi0A_6;
		nimln_(33);		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_4, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		nimlf_(1031, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");		T2_ = (NI)0;
		T2_ = len__ast_u3197(n_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimSubInt(T2_, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_6)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_6) < 0 || (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_6) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_6),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
		}
		nimlf_(33, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		result = renderPlainSymbolName__typesrenderer_u9((*n_p0)._kind_6.sons.p->data[(NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_6)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)2):
	{
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_7[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_9, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		eqcopy___system_u2632((&result), (*(*n_p0)._kind_5.ident).s);
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
	{
		nimlf_(37, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_10[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_12, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		result = renderDefinitionName__renderer_u125((*n_p0)._kind_4.sym, NIM_TRUE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)43):
	{
		nimln_(39);		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_13, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
		}
		result = renderPlainSymbolName__typesrenderer_u9((*n_p0)._kind_6.sons.p->data[((NI)0)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		nimln_(41);		result = TM__SgHDIVcSir4dkKoe0Xsi0A_15;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1728)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__SgHDIVcSir4dkKoe0Xsi0A_31;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1728(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__SgHDIVcSir4dkKoe0Xsi0A_31)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_31);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	NI TM__SgHDIVcSir4dkKoe0Xsi0A_49;
{	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	if (nimAddInt((*dest_p0).len, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_49)) { raiseOverflow(); goto BeforeRet_;
	};
	(*dest_p0).len = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_49);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2378(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, X5BX5Deq___system_u7919)(NimStringV2* s_p0, NI i_p1, NIM_CHAR x_p2) {
	NI TM__SgHDIVcSir4dkKoe0Xsi0A_51;
	nimfr_("[]=", "/opt/local/lib/nim/lib/system/indices.nim");
{	nimlf_(40, "/opt/local/lib/nim/lib/system/indices.nim");	if (nimSubInt((*s_p0).len, i_p1, &TM__SgHDIVcSir4dkKoe0Xsi0A_51)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_51) < 0 || (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_51) >= (*s_p0).len){ raiseIndexError2((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_51),(*s_p0).len-1); goto BeforeRet_;
	}
	nimPrepareStrMutationV2((&(*s_p0)));
	(*s_p0).p->data[(NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_51)] = x_p2;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderType__typesrenderer_u12)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, NIM_BOOL toNormalize_p1) {
	NimStringV2 result;
NIM_BOOL oldNimErrFin60_;
NIM_BOOL* nimErr_;
	nimfr_("renderType", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(48, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");	switch ((*n_p0).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)2):
	{
		NimStringV2 T2_;
		T2_.len = 0; T2_.p = NIM_NIL;
		nimln_(49);		{
			if (!toNormalize_p1) goto LA5_;
			nimln_(21);			if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_7[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_22, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			result = nimIdentNormalize__pureZstrutils_u124((*(*n_p0)._kind_5.ident).s);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA3_;
LA5_: ;
		{
			nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");			if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_7[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_23, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			eqcopy___system_u2632((&result), (*(*n_p0)._kind_5.ident).s);
		}
LA3_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3):
	{
		NimStringV2 T9_;
		T9_.len = 0; T9_.p = NIM_NIL;
		nimlf_(50, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		{
			NimStringV2 colontmpD_;
			if (!toNormalize_p1) goto LA12_;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			nimln_(21);			nimln_(50);			if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_10[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_24, dollar___nodekinds_u168((*n_p0).kind)); goto LA14_;
			}
			colontmpD_ = typeToString__types_u54((*(*n_p0)._kind_4.sym).typ, ((tyEnum_TPreferedDesc__ZPp9cjDDLuuf5JrmkQzA5gQ)0));
			if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
			nimln_(21);			result = nimIdentNormalize__pureZstrutils_u124(colontmpD_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
			{
				LA14_:;
			}
			{
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD_);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			nimlf_(50, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			if (!(((TM__SgHDIVcSir4dkKoe0Xsi0A_10[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0))) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_25, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			result = typeToString__types_u54((*(*n_p0)._kind_4.sym).typ, ((tyEnum_TPreferedDesc__ZPp9cjDDLuuf5JrmkQzA5gQ)0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA10_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)143):
	{
		nimln_(52);		{
			NI T21_;
			T21_ = (NI)0;
			T21_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(T21_ == ((NI)1))) goto LA22_;
			nimln_(53);			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_26, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
			}
			result = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA19_;
LA22_: ;
		{
			nimln_(55);			result = TM__SgHDIVcSir4dkKoe0Xsi0A_28;
		}
LA19_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)141):
	{
		nimln_(57);		{
			NI T28_;
			NimStringV2 colontmpD__2;
			NimStringV2 T32_;
			T28_ = (NI)0;
			T28_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(T28_ == ((NI)1))) goto LA29_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(58);			T32_.len = 0; T32_.p = NIM_NIL;
			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_32, dollar___nodekinds_u168((*n_p0).kind)); goto LA31_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto LA31_;
			}
			colontmpD__2 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
			T32_ = rawNewString(colontmpD__2.len + 4);
appendString((&T32_), TM__SgHDIVcSir4dkKoe0Xsi0A_30);
appendString((&T32_), colontmpD__2);
			result = T32_;
			{
				LA31_:;
			}
			{
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD__2);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA26_;
LA29_: ;
		{
			nimlf_(60, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			result = TM__SgHDIVcSir4dkKoe0Xsi0A_34;
		}
LA26_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)142):
	{
		nimln_(62);		{
			NI T39_;
			NimStringV2 colontmpD__3;
			NimStringV2 T43_;
			T39_ = (NI)0;
			T39_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(T39_ == ((NI)1))) goto LA40_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			nimln_(63);			T43_.len = 0; T43_.p = NIM_NIL;
			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_37, dollar___nodekinds_u168((*n_p0).kind)); goto LA42_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto LA42_;
			}
			colontmpD__3 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
			T43_ = rawNewString(colontmpD__3.len + 4);
appendString((&T43_), TM__SgHDIVcSir4dkKoe0Xsi0A_36);
appendString((&T43_), colontmpD__3);
			result = T43_;
			{
				LA42_:;
			}
			{
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___system_u2629(colontmpD__3);
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA37_;
LA40_: ;
		{
			nimlf_(65, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			result = TM__SgHDIVcSir4dkKoe0Xsi0A_39;
		}
LA37_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)147):
	{
		nimln_(67);		{
			NI T50_;
			T50_ = (NI)0;
			T50_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(!((T50_ == ((NI)1))))) goto LA51_;
			failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_41);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA51_: ;
		nimln_(68);		{
			NIM_BOOL T55_;
			NI T56_;
			tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* params_1;
			T55_ = (NIM_BOOL)0;
			T56_ = (NI)0;
			T56_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T55_ = (((NI)1) < T56_);
			if (!(T55_)) goto LA57_;
			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_42, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
			}
			T55_ = ((*(*n_p0)._kind_6.sons.p->data[((NI)0)]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)76));
LA57_: ;
			if (!T55_) goto LA58_;
			params_1 = NIM_NIL;
			nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_43, dollar___nodekinds_u168((*n_p0).kind)); goto LA60_;
			}
			if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto LA60_;
			}
			eqcopy___ast_u3264(&params_1, (*n_p0)._kind_6.sons.p->data[((NI)0)]);
			if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
			nimlf_(70, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			{
				NI T63_;
				T63_ = (NI)0;
				T63_ = len__ast_u3197(params_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
				if (!!((((NI)0) < T63_))) goto LA64_;
				failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_45);
				if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
			}
LA64_: ;
			nimln_(71);			result = TM__SgHDIVcSir4dkKoe0Xsi0A_47;
			{
				NI i_1;
				NI colontmp_;
				NI i_2;
				i_1 = (NI)0;
				colontmp_ = (NI)0;
				nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");				nimlf_(72, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");				colontmp_ = len__ast_u3197(params_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
				nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");				i_2 = ((NI)1);
				{
					nimln_(129);					while (1) {
						NimStringV2 colontmpD__4;
						NimStringV2 colontmpD__5;
						NimStringV2 T70_;
						NI TM__SgHDIVcSir4dkKoe0Xsi0A_50;
						if (!(i_2 < colontmp_)) goto LA68;
						colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						nimlf_(72, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");						i_1 = i_2;
						T70_.len = 0; T70_.p = NIM_NIL;
						if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*params_1).kind))>>3] &(1U<<((NU)(((*params_1).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_48, dollar___nodekinds_u168((*params_1).kind)); goto LA69_;
						}
						if (i_1 < 0 || i_1 >= (*params_1)._kind_6.sons.len){ raiseIndexError2(i_1,(*params_1)._kind_6.sons.len-1); goto LA69_;
						}
						colontmpD__4 = renderType__typesrenderer_u12((*params_1)._kind_6.sons.p->data[i_1], toNormalize_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						T70_ = rawNewString(colontmpD__4.len + 1);
appendString((&T70_), colontmpD__4);
appendChar((&T70_), 44);
						colontmpD__5 = T70_;
						prepareAdd((&result), colontmpD__5.len + 0);
appendString((&result), colontmpD__5);
						nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");						if (nimAddInt(i_2, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_50)) { raiseOverflow(); goto LA69_;
						};
						i_2 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_50);
						{
							LA69_:;
						}
						{
							nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");							eqdestroy___system_u2629(colontmpD__5);
							eqdestroy___system_u2629(colontmpD__4);
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
					} LA68: ;
				}
			}
			nimlf_(73, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			X5BX5Deq___system_u7919((&result), ((NI)1), 41);
			if (NIM_UNLIKELY(*nimErr_)) goto LA60_;
			{
				LA60_:;
			}
			{
				oldNimErrFin60_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimlf_(1023, "/Users/svacchanda/Dev/nimv2/compiler/ast.nim");				eqdestroy___ast_u3261(params_1);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				*nimErr_ = oldNimErrFin60_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA53_;
LA58_: ;
		{
			nimlf_(75, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			result = TM__SgHDIVcSir4dkKoe0Xsi0A_53;
		}
LA53_: ;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)35):
	{
		NimStringV2 typeStr_1;
		NI typePos_1;
		NI T83_;
		NI TM__SgHDIVcSir4dkKoe0Xsi0A_56;
		typeStr_1.len = 0; typeStr_1.p = NIM_NIL;
		nimln_(77);		{
			NI T80_;
			T80_ = (NI)0;
			T80_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
			if (!!((((NI)3) <= T80_))) goto LA81_;
			failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_55);
			if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
		}
LA81_: ;
		nimln_(78);		T83_ = (NI)0;
		T83_ = len__ast_u3197(n_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
		if (nimSubInt(T83_, ((NI)2), &TM__SgHDIVcSir4dkKoe0Xsi0A_56)) { raiseOverflow(); goto LA77_;
		};
		typePos_1 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_56);
		nimln_(79);		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_57, dollar___nodekinds_u168((*n_p0).kind)); goto LA77_;
		}
		if (typePos_1 < 0 || typePos_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(typePos_1,(*n_p0)._kind_6.sons.len-1); goto LA77_;
		}
		typeStr_1 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[typePos_1], toNormalize_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		eqcopy___system_u2632((&result), typeStr_1);
		{
			NI i_3;
			NI i_4;
			i_3 = (NI)0;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_4 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NimStringV2 colontmpD__6;
					NimStringV2 T91_;
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_61;
					if (!(i_4 < typePos_1)) goto LA86;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimlf_(81, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_3 = i_4;
					nimln_(82);					{
						if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_58, dollar___nodekinds_u168((*n_p0).kind)); goto LA77_;
						}
						if (i_3 < 0 || i_3 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_3,(*n_p0)._kind_6.sons.len-1); goto LA77_;
						}
						if (!!(((*(*n_p0)._kind_6.sons.p->data[i_3]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)3) || (*(*n_p0)._kind_6.sons.p->data[i_3]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)2)))) goto LA89_;
						failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_60);
						if (NIM_UNLIKELY(*nimErr_)) goto LA77_;
					}
LA89_: ;
					nimln_(83);					T91_.len = 0; T91_.p = NIM_NIL;
					T91_ = rawNewString(typeStr_1.len + 1);
appendChar((&T91_), 44);
appendString((&T91_), typeStr_1);
					colontmpD__6 = T91_;
					prepareAdd((&result), colontmpD__6.len + 0);
appendString((&result), colontmpD__6);
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_4, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_61)) { raiseOverflow(); goto LA77_;
					};
					i_4 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_61);
					nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");					eqdestroy___system_u2629(colontmpD__6);
				} LA86: ;
			}
		}
		{
			LA77_:;
		}
		{
			eqdestroy___system_u2629(typeStr_1);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)134):
	{
		nimlf_(85, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		result = TM__SgHDIVcSir4dkKoe0Xsi0A_63;
		{
			NI i_5;
			NI colontmp__2;
			NI i_6;
			i_5 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(86, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			colontmp__2 = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_6 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NimStringV2 colontmpD__7;
					NimStringV2 colontmpD__8;
					NimStringV2 T99_;
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_65;
					if (!(i_6 < colontmp__2)) goto LA97;
					colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
					colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
					nimlf_(86, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_5 = i_6;
					T99_.len = 0; T99_.p = NIM_NIL;
					if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_64, dollar___nodekinds_u168((*n_p0).kind)); goto LA98_;
					}
					if (i_5 < 0 || i_5 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_5,(*n_p0)._kind_6.sons.len-1); goto LA98_;
					}
					colontmpD__7 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[i_5], toNormalize_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA98_;
					T99_ = rawNewString(colontmpD__7.len + 1);
appendString((&T99_), colontmpD__7);
appendChar((&T99_), 44);
					colontmpD__8 = T99_;
					prepareAdd((&result), colontmpD__8.len + 0);
appendString((&result), colontmpD__8);
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_6, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_65)) { raiseOverflow(); goto LA98_;
					};
					i_6 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_65);
					{
						LA98_:;
					}
					{
						nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");						eqdestroy___system_u2629(colontmpD__8);
						eqdestroy___system_u2629(colontmpD__7);
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA97: ;
			}
		}
		nimlf_(87, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		X5BX5Deq___system_u7919((&result), ((NI)1), 93);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)42):
	{
		NimStringV2 colontmpD__9;
		NimStringV2 T109_;
		colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
		nimln_(89);		{
			NI T106_;
			T106_ = (NI)0;
			T106_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
			if (!!((((NI)2) <= T106_))) goto LA107_;
			failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_67);
			if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
		}
LA107_: ;
		nimln_(90);		T109_.len = 0; T109_.p = NIM_NIL;
		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_68, dollar___nodekinds_u168((*n_p0).kind)); goto LA103_;
		}
		if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto LA103_;
		}
		colontmpD__9 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
		T109_ = rawNewString(colontmpD__9.len + 1);
appendString((&T109_), colontmpD__9);
appendChar((&T109_), 91);
		result = T109_;
		{
			NI i_7;
			NI colontmp__3;
			NI i_8;
			i_7 = (NI)0;
			colontmp__3 = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(91, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			colontmp__3 = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_8 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NimStringV2 colontmpD__10;
					NimStringV2 colontmpD__11;
					NimStringV2 T114_;
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_70;
					if (!(i_8 < colontmp__3)) goto LA112;
					colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
					colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
					nimlf_(91, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_7 = i_8;
					T114_.len = 0; T114_.p = NIM_NIL;
					if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_69, dollar___nodekinds_u168((*n_p0).kind)); goto LA113_;
					}
					if (i_7 < 0 || i_7 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_7,(*n_p0)._kind_6.sons.len-1); goto LA113_;
					}
					colontmpD__10 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[i_7], toNormalize_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA113_;
					T114_ = rawNewString(colontmpD__10.len + 1);
appendString((&T114_), colontmpD__10);
appendChar((&T114_), 44);
					colontmpD__11 = T114_;
					prepareAdd((&result), colontmpD__11.len + 0);
appendString((&result), colontmpD__11);
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_8, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_70)) { raiseOverflow(); goto LA113_;
					};
					i_8 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_70);
					{
						LA113_:;
					}
					{
						nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");						eqdestroy___system_u2629(colontmpD__11);
						eqdestroy___system_u2629(colontmpD__10);
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
				} LA112: ;
			}
		}
		nimlf_(92, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		X5BX5Deq___system_u7919((&result), ((NI)1), 93);
		if (NIM_UNLIKELY(*nimErr_)) goto LA103_;
		{
			LA103_:;
		}
		{
			nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___system_u2629(colontmpD__9);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)26):
	{
		nimlf_(94, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_71, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
		}
		if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
		}
		result = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			NI i_9;
			NI colontmp__4;
			NI i_10;
			i_9 = (NI)0;
			colontmp__4 = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(95, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			colontmp__4 = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_10 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NimStringV2 colontmpD__12;
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_75;
					if (!(i_10 < colontmp__4)) goto LA122;
					colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
					nimlf_(95, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_9 = i_10;
					nimln_(96);					{
						if (!(((NI)1) < i_9)) goto LA126_;
						prepareAdd((&result), 2);
appendString((&result), TM__SgHDIVcSir4dkKoe0Xsi0A_73);
					}
LA126_: ;
					nimln_(97);					if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_74, dollar___nodekinds_u168((*n_p0).kind)); goto LA123_;
					}
					if (i_9 < 0 || i_9 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_9,(*n_p0)._kind_6.sons.len-1); goto LA123_;
					}
					colontmpD__12 = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[i_9], toNormalize_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA123_;
					prepareAdd((&result), colontmpD__12.len + 0);
appendString((&result), colontmpD__12);
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_10, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_75)) { raiseOverflow(); goto LA123_;
					};
					i_10 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_75);
					{
						LA123_:;
					}
					{
						nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");						eqdestroy___system_u2629(colontmpD__12);
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA122: ;
			}
		}
	}
	break;
	default:
	{
		nimlf_(98, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		result = TM__SgHDIVcSir4dkKoe0Xsi0A_76;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, renderParamTypes__typesrenderer_u121)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* found_p0, tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p1, NIM_BOOL toNormalize_p2) {
NIM_BOOL oldNimErrFin18_;
NIM_BOOL* nimErr_;
	nimfr_("renderParamTypes", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	nimln_(125);	switch ((*n_p1).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)76):
	{
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(127, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			colontmp_ = len__ast_u3197(n_p1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_2 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_18;
					if (!(i_2 < colontmp_)) goto LA4;
					nimlf_(127, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_1 = i_2;
					if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 					{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_17, dollar___nodekinds_u168((*n_p1).kind)); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p1)._kind_6.sons.len-1); goto BeforeRet_;
					}
					renderParamTypes__typesrenderer_u121(found_p0, (*n_p1)._kind_6.sons.p->data[i_1], toNormalize_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_2, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_18)) { raiseOverflow(); goto BeforeRet_;
					};
					i_2 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_18);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)35):
	{
		NimStringV2 typeStr_1;
		NI typePos_1;
		NI T7_;
		NI TM__SgHDIVcSir4dkKoe0Xsi0A_19;
		typeStr_1.len = 0; typeStr_1.p = NIM_NIL;
		nimlf_(130, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		T7_ = (NI)0;
		T7_ = len__ast_u3197(n_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		if (nimSubInt(T7_, ((NI)2), &TM__SgHDIVcSir4dkKoe0Xsi0A_19)) { raiseOverflow(); goto LA6_;
		};
		typePos_1 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_19);
		nimln_(131);		{
			if (!!((((NI)0) < typePos_1))) goto LA10_;
			failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_21);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		}
LA10_: ;
		nimln_(132);		if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 		{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_77, dollar___nodekinds_u168((*n_p1).kind)); goto LA6_;
		}
		if (typePos_1 < 0 || typePos_1 >= (*n_p1)._kind_6.sons.len){ raiseIndexError2(typePos_1,(*n_p1)._kind_6.sons.len-1); goto LA6_;
		}
		typeStr_1 = renderType__typesrenderer_u12((*n_p1)._kind_6.sons.p->data[typePos_1], toNormalize_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimln_(133);		{
			NIM_BOOL T14_;
			NI TM__SgHDIVcSir4dkKoe0Xsi0A_79;
			tyObject_TType__iJdztaLTgKBTz6Ri4YrIlg* typ_1;
			NI TM__SgHDIVcSir4dkKoe0Xsi0A_81;
			T14_ = (NIM_BOOL)0;
			T14_ = (typeStr_1.len < ((NI)1));
			if (!(T14_)) goto LA15_;
			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_78, dollar___nodekinds_u168((*n_p1).kind)); goto LA6_;
			}
			if (nimAddInt(typePos_1, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_79)) { raiseOverflow(); goto LA6_;
			};
			if ((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_79) < 0 || (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_79) >= (*n_p1)._kind_6.sons.len){ raiseIndexError2((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_79),(*n_p1)._kind_6.sons.len-1); goto LA6_;
			}
			T14_ = !(((*(*n_p1)._kind_6.sons.p->data[(NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_79)]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)1)));
LA15_: ;
			if (!T14_) goto LA16_;
			typ_1 = NIM_NIL;
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p1).kind))>>3] &(1U<<((NU)(((*n_p1).kind))&7U)))!=0)) 			{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_80, dollar___nodekinds_u168((*n_p1).kind)); goto LA18_;
			}
			nimlf_(135, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			if (nimAddInt(typePos_1, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_81)) { raiseOverflow(); goto LA18_;
			};
			if ((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_81) < 0 || (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_81) >= (*n_p1)._kind_6.sons.len){ raiseIndexError2((NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_81),(*n_p1)._kind_6.sons.len-1); goto LA18_;
			}
			nimlf_(934, "/opt/local/lib/nim/lib/system.nim");			eqcopy___ast_u3390(&typ_1, (*(*n_p1)._kind_6.sons.p->data[(NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_81)]).typField);
			if (NIM_UNLIKELY(*nimErr_)) goto LA18_;
			nimlf_(136, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			{
				NimStringV2 T23_;
				if (!!((typ_1 == 0))) goto LA21_;
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				nimlf_(136, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");				T23_.len = 0; T23_.p = NIM_NIL;
				T23_ = typeToString__types_u54(typ_1, ((tyEnum_TPreferedDesc__ZPp9cjDDLuuf5JrmkQzA5gQ)2));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u2629(T23_); goto LA18_;}
				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				eqsink___system_u2638((&typeStr_1), T23_);
			}
LA21_: ;
			nimlf_(137, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			{
				if (!(typeStr_1.len < ((NI)1))) goto LA26_;
				nimlf_(934, "/opt/local/lib/nim/lib/system.nim");				eqdestroy___ast_u3387(typ_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
				nimln_(1699);				eqdestroy___system_u2629(typeStr_1);
				goto BeforeRet_;
			}
LA26_: ;
			{
				LA18_:;
			}
			{
				oldNimErrFin18_ = *nimErr_; *nimErr_ = NIM_FALSE;
				nimln_(934);				eqdestroy___ast_u3387(typ_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
				*nimErr_ = oldNimErrFin18_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		}
LA16_: ;
		{
			NI i_3;
			NI i_4;
			i_3 = (NI)0;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_4 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NimStringV2 colontmpD_;
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_82;
					if (!(i_4 < typePos_1)) goto LA32;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimlf_(138, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_3 = i_4;
					nimln_(139);					nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");					colontmpD_ = eqdup___system_u2635(typeStr_1);
					nimlf_(139, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					add__stdZenumutils_u71((&(*found_p0)), colontmpD_);
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_4, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_82)) { raiseOverflow(); goto LA6_;
					};
					i_4 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_82);
				} LA32: ;
			}
		}
		{
			LA6_:;
		}
		{
			nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");			eqdestroy___system_u2629(typeStr_1);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		NimStringV2 T36_;
		nimlf_(141, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		T36_.len = 0; T36_.p = NIM_NIL;
		T36_ = dollar___renderer_u2165(n_p1);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u2629(T36_); goto BeforeRet_;}
		add__stdZenumutils_u71((&(*found_p0)), T36_);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderParamTypes__typesrenderer_u158)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, NimStringV2 sep_p1, NIM_BOOL toNormalize_p2) {
	NimStringV2 result;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ found_1;
NIM_BOOL* nimErr_;
	nimfr_("renderParamTypes", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	found_1.len = 0; found_1.p = NIM_NIL;
	nimln_(152);	result = TM__SgHDIVcSir4dkKoe0Xsi0A_16;
	nimln_(153);	found_1.len = 0; found_1.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(154);	renderParamTypes__typesrenderer_u121((&found_1), n_p0, toNormalize_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(155);	{
		NI T4_;
		NimStringV2 T7_;
		T4_ = found_1.len;
		if (!(((NI)0) < T4_)) goto LA5_;
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		nimlf_(156, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = nsuJoinSep(((found_1).p) ? (found_1.p->data) : NIM_NIL, found_1.len, sep_p1);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u2629(T7_); goto LA1_;}
		nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");		eqsink___system_u2638((&result), T7_);
	}
LA5_: ;
	{
		LA1_:;
	}
	{
		nimln_(2128);		eqdestroy___system_u3755(found_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, renderParamNames__typesrenderer_u77)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, NIM_BOOL toNormalize_p1) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
	nimfr_("renderParamNames", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(103, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	nimln_(104);	{
		if (!!(((*n_p0).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)76)))) goto LA3_;
		failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_84);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(105);	switch ((*n_p0).kind) {
	case ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)76):
	{
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/opt/local/lib/nim/lib/system/iterators_1.nim");			nimlf_(107, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");			colontmp_ = len__ast_u3197(n_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");			i_2 = ((NI)1);
			{
				nimln_(129);				while (1) {
					NI TM__SgHDIVcSir4dkKoe0Xsi0A_94;
					if (!(i_2 < colontmp_)) goto LA8;
					nimlf_(107, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");					i_1 = i_2;
					nimln_(108);					{
						NI typePos_1;
						NI T13_;
						NI TM__SgHDIVcSir4dkKoe0Xsi0A_87;
						if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_85, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
						}
						if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
						}
						if (!((*(*n_p0)._kind_6.sons.p->data[i_1]).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)35))) goto LA11_;
						nimln_(110);						if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_86, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
						}
						if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
						}
						T13_ = (NI)0;
						T13_ = len__ast_u3197((*n_p0)._kind_6.sons.p->data[i_1]);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (nimSubInt(T13_, ((NI)2), &TM__SgHDIVcSir4dkKoe0Xsi0A_87)) { raiseOverflow(); goto BeforeRet_;
						};
						typePos_1 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_87);
						{
							NI j_1;
							NI i_3;
							j_1 = (NI)0;
							nimlf_(128, "/opt/local/lib/nim/lib/system/iterators_1.nim");							i_3 = ((NI)0);
							{
								nimln_(129);								while (1) {
									NimStringV2 colontmpD_;
									NimStringV2 colontmpD__2;
									NimStringV2 T18_;
									NI TM__SgHDIVcSir4dkKoe0Xsi0A_92;
									if (!(i_3 < typePos_1)) goto LA16;
									colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
									colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
									nimlf_(111, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");									j_1 = i_3;
									nimln_(112);									T18_.len = 0; T18_.p = NIM_NIL;
									{
										NimStringV2 colontmpD__3;
										NimStringV2 blitTmp_1;
										if (!toNormalize_p1) goto LA21_;
										colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
										nimln_(21);										nimln_(112);										if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 										{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_88, dollar___nodekinds_u168((*n_p0).kind)); goto LA23_;
										}
										if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto LA23_;
										}
										if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*(*n_p0)._kind_6.sons.p->data[i_1]).kind))>>3] &(1U<<((NU)(((*(*n_p0)._kind_6.sons.p->data[i_1]).kind))&7U)))!=0)) 										{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_89, dollar___nodekinds_u168((*(*n_p0)._kind_6.sons.p->data[i_1]).kind)); goto LA23_;
										}
										if (j_1 < 0 || j_1 >= (*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.len){ raiseIndexError2(j_1,(*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.len-1); goto LA23_;
										}
										colontmpD__3 = dollar___renderer_u2165((*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.p->data[j_1]);
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
										nimln_(21);										colontmpD_ = nimIdentNormalize__pureZstrutils_u124(colontmpD__3);
										if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
										blitTmp_1 = colontmpD_;
										nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");										eqwasMoved___system_u2626((&colontmpD_));
										T18_ = blitTmp_1;
										{
											LA23_:;
										}
										{
											eqdestroy___system_u2629(colontmpD__3);
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
									}
									goto LA19_;
LA21_: ;
									{
										NimStringV2 blitTmp_2;
										nimlf_(112, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");										if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 										{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_90, dollar___nodekinds_u168((*n_p0).kind)); goto LA27_;
										}
										if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto LA27_;
										}
										if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*(*n_p0)._kind_6.sons.p->data[i_1]).kind))>>3] &(1U<<((NU)(((*(*n_p0)._kind_6.sons.p->data[i_1]).kind))&7U)))!=0)) 										{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_91, dollar___nodekinds_u168((*(*n_p0)._kind_6.sons.p->data[i_1]).kind)); goto LA27_;
										}
										if (j_1 < 0 || j_1 >= (*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.len){ raiseIndexError2(j_1,(*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.len-1); goto LA27_;
										}
										colontmpD__2 = dollar___renderer_u2165((*(*n_p0)._kind_6.sons.p->data[i_1])._kind_6.sons.p->data[j_1]);
										if (NIM_UNLIKELY(*nimErr_)) goto LA27_;
										blitTmp_2 = colontmpD__2;
										nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");										eqwasMoved___system_u2626((&colontmpD__2));
										T18_ = blitTmp_2;
										{
											LA27_:;
										}
										{
										}
										if (NIM_UNLIKELY(*nimErr_)) goto LA17_;
									}
LA19_: ;
									nimlf_(112, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");									add__stdZenumutils_u71((&result), T18_);
									nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");									if (nimAddInt(i_3, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_92)) { raiseOverflow(); goto LA17_;
									};
									i_3 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_92);
									{
										LA17_:;
									}
									{
										nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");										eqdestroy___system_u2629(colontmpD__2);
										eqdestroy___system_u2629(colontmpD_);
									}
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								} LA16: ;
							}
						}
					}
					goto LA9_;
LA11_: ;
					{
						NimStringV2 T33_;
						nimlf_(114, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");						if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 						{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_93, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
						}
						if (i_1 < 0 || i_1 >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(i_1,(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
						}
						T33_.len = 0; T33_.p = NIM_NIL;
						T33_ = dollar___renderer_u2165((*n_p0)._kind_6.sons.p->data[i_1]);
						if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u2629(T33_); goto BeforeRet_;}
						add__stdZenumutils_u71((&result), T33_);
					}
LA9_: ;
					nimlf_(131, "/opt/local/lib/nim/lib/system/iterators_1.nim");					if (nimAddInt(i_2, ((NI)1), &TM__SgHDIVcSir4dkKoe0Xsi0A_94)) { raiseOverflow(); goto BeforeRet_;
					};
					i_2 = (NI)(TM__SgHDIVcSir4dkKoe0Xsi0A_94);
				} LA8: ;
			}
		}
	}
	break;
	default:
	{
		NimStringV2 T35_;
		nimlf_(116, "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");		T35_.len = 0; T35_.p = NIM_NIL;
		T35_ = dollar___renderer_u2165(n_p0);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u2629(T35_); goto BeforeRet_;}
		add__stdZenumutils_u71((&result), T35_);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, renderOutType__typesrenderer_u171)(tyObject_TNode__ICIckkJXnoKwBNT189aT0Pg* n_p0, NIM_BOOL toNormalize_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("renderOutType", "/Users/svacchanda/Dev/nimv2/compiler/typesrenderer.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(159);	{
		if (!!(((*n_p0).kind == ((tyEnum_TNodeKind__xcskcX9cZxwBFut4336mj9cQ)76)))) goto LA3_;
		failedAssertImpl__stdZassertions_u242(TM__SgHDIVcSir4dkKoe0Xsi0A_96);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(160);	if (((TM__SgHDIVcSir4dkKoe0Xsi0A_2[(NU)(((*n_p0).kind))>>3] &(1U<<((NU)(((*n_p0).kind))&7U)))!=0)) 	{ raiseFieldErrorStr(TM__SgHDIVcSir4dkKoe0Xsi0A_97, dollar___nodekinds_u168((*n_p0).kind)); goto BeforeRet_;
	}
	if (((NI)0) < 0 || ((NI)0) >= (*n_p0)._kind_6.sons.len){ raiseIndexError2(((NI)0),(*n_p0)._kind_6.sons.len-1); goto BeforeRet_;
	}
	result = renderType__typesrenderer_u12((*n_p0)._kind_6.sons.p->data[((NI)0)], toNormalize_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
