/* Generated by Nim Compiler v2.2.6 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__qR8bNeEbuarzZRmZMZKW4A tyTuple__qR8bNeEbuarzZRmZMZKW4A;
typedef struct tyTuple__8oAH9aeHj9c09bf5gorQWcAwA tyTuple__8oAH9aeHj9c09bf5gorQWcAwA;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef NU8 tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw;
typedef NU8 tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og {
	tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA targetCPU;
	tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA hostCPU;
	tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw targetOS;
	tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw hostOS;
	NI intSize;
	NI floatSize;
	NI ptrSize;
	NimStringV2 tnl;
};
typedef NU8 tySet_tyEnum_TInfoOSProp__Mh9amd1l0iSsr8bzVEbVXpA;
struct tyTuple__qR8bNeEbuarzZRmZMZKW4A {
	NimStringV2 Field0;
	NimStringV2 Field1;
	NimStringV2 Field2;
	NimStringV2 Field3;
	NimStringV2 Field4;
	NimStringV2 Field5;
	NimStringV2 Field6;
	NimStringV2 Field7;
	NimStringV2 Field8;
	NimStringV2 Field9;
	NimStringV2 Field10;
	NimStringV2 Field11;
	tySet_tyEnum_TInfoOSProp__Mh9amd1l0iSsr8bzVEbVXpA Field12;
};
typedef tyTuple__qR8bNeEbuarzZRmZMZKW4A tyArray__QtmJy0ypYNZgjoouQCg8rg[34];
typedef NU8 tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA;
struct tyTuple__8oAH9aeHj9c09bf5gorQWcAwA {
	NimStringV2 Field0;
	NI Field1;
	tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA Field2;
	NI Field3;
	NI Field4;
};
typedef tyTuple__8oAH9aeHj9c09bf5gorQWcAwA tyArray__egO9aXu9cYeNOlmFDj3yK9c9bw[29];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw, nameToOS__platform_u850)(NimStringV2 name_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError3)(NI i_p0, NI a_p1, NI b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4480)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA, nameToCPU__platform_u898)(NimStringV2 name_p0);
N_LIB_PRIVATE N_NIMCALL(void, setTarget__platform_u750)(tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og* t_p0, tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw o_p1, tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA c_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u242)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2632)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u71)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2635)(NimStringV2 src_p0);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_2 = { 3 | NIM_STRLIT_FLAG, "DOS" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_3 = { 2 | NIM_STRLIT_FLAG, ".." };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_4 = { 6 | NIM_STRLIT_FLAG, "$1.dll" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_5 = { 1 | NIM_STRLIT_FLAG, "/" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_6 = { 4 | NIM_STRLIT_FLAG, ".obj" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_7 = { 2 | NIM_STRLIT_FLAG, "\015\012" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_8 = { 1 | NIM_STRLIT_FLAG, ";" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_9 = { 1 | NIM_STRLIT_FLAG, "\\" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_10 = { 4 | NIM_STRLIT_FLAG, ".bat" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_11 = { 1 | NIM_STRLIT_FLAG, "." };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_12 = { 4 | NIM_STRLIT_FLAG, ".exe" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_13 = { 7 | NIM_STRLIT_FLAG, "Windows" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_14 = { 3 | NIM_STRLIT_FLAG, "OS2" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_15 = { 5 | NIM_STRLIT_FLAG, "Linux" };
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_16 = { 8 | NIM_STRLIT_FLAG, "lib$1.so" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_17 = { 2 | NIM_STRLIT_FLAG, ".o" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_18 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_19 = { 1 | NIM_STRLIT_FLAG, ":" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_20 = { 3 | NIM_STRLIT_FLAG, ".sh" };
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_21 = { 0 | NIM_STRLIT_FLAG, "" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_22 = { 7 | NIM_STRLIT_FLAG, "MorphOS" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_23 = { 5 | NIM_STRLIT_FLAG, "SkyOS" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_24 = { 7 | NIM_STRLIT_FLAG, "Solaris" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_25 = { 4 | NIM_STRLIT_FLAG, "Irix" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_26 = { 6 | NIM_STRLIT_FLAG, "NetBSD" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_27 = { 7 | NIM_STRLIT_FLAG, "FreeBSD" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_28 = { 7 | NIM_STRLIT_FLAG, "OpenBSD" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_29 = { 9 | NIM_STRLIT_FLAG, "DragonFly" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_30 = { 7 | NIM_STRLIT_FLAG, "CROSSOS" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_31 = { 3 | NIM_STRLIT_FLAG, "AIX" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_32 = { 6 | NIM_STRLIT_FLAG, "PalmOS" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_33 = { 3 | NIM_STRLIT_FLAG, "QNX" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_34 = { 5 | NIM_STRLIT_FLAG, "Amiga" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_35 = { 10 | NIM_STRLIT_FLAG, "$1.library" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_36 = { 5 | NIM_STRLIT_FLAG, "Atari" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_37 = { 4 | NIM_STRLIT_FLAG, ".tpp" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_38 = { 7 | NIM_STRLIT_FLAG, "Netware" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_39 = { 6 | NIM_STRLIT_FLAG, "$1.nlm" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_40 = { 4 | NIM_STRLIT_FLAG, ".nlm" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_41 = { 5 | NIM_STRLIT_FLAG, "MacOS" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_42 = { 2 | NIM_STRLIT_FLAG, "::" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_43 = { 5 | NIM_STRLIT_FLAG, "$1Lib" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_44 = { 1 | NIM_STRLIT_FLAG, "\015" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_45 = { 1 | NIM_STRLIT_FLAG, "," };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_46 = { 6 | NIM_STRLIT_FLAG, "MacOSX" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_47 = { 11 | NIM_STRLIT_FLAG, "lib$1.dylib" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_48 = { 3 | NIM_STRLIT_FLAG, "iOS" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_49 = { 5 | NIM_STRLIT_FLAG, "Haiku" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_50 = { 7 | NIM_STRLIT_FLAG, "Android" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_51 = { 7 | NIM_STRLIT_FLAG, "VxWorks" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_52 = { 4 | NIM_STRLIT_FLAG, ".vxe" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_53 = { 6 | NIM_STRLIT_FLAG, "Genode" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_54 = { 9 | NIM_STRLIT_FLAG, "$1.lib.so" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_55 = { 2 | NIM_STRLIT_FLAG, "JS" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_56 = { 5 | NIM_STRLIT_FLAG, "NimVM" };
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_57 = { 10 | NIM_STRLIT_FLAG, "Standalone" };
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_58 = { 14 | NIM_STRLIT_FLAG, "NintendoSwitch" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_59 = { 4 | NIM_STRLIT_FLAG, ".elf" };
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_60 = { 8 | NIM_STRLIT_FLAG, "FreeRTOS" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_61 = { 6 | NIM_STRLIT_FLAG, "Zephyr" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_62 = { 5 | NIM_STRLIT_FLAG, "NuttX" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_63 = { 3 | NIM_STRLIT_FLAG, "Any" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_65 = { 7 | NIM_STRLIT_FLAG, "freebsd" };
static const NimStringV2 TM__LEa0rTUoGHqcCT74IoUuTg_66 = {7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_65};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_67 = { 4 | NIM_STRLIT_FLAG, "i386" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_68 = { 4 | NIM_STRLIT_FLAG, "m68k" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_69 = { 5 | NIM_STRLIT_FLAG, "alpha" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_70 = { 7 | NIM_STRLIT_FLAG, "powerpc" };
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_71 = { 9 | NIM_STRLIT_FLAG, "powerpc64" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_72 = { 11 | NIM_STRLIT_FLAG, "powerpc64el" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_73 = { 5 | NIM_STRLIT_FLAG, "sparc" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_74 = { 2 | NIM_STRLIT_FLAG, "vm" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_75 = { 4 | NIM_STRLIT_FLAG, "hppa" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_76 = { 4 | NIM_STRLIT_FLAG, "ia64" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_77 = { 5 | NIM_STRLIT_FLAG, "amd64" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_78 = { 4 | NIM_STRLIT_FLAG, "mips" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_79 = { 6 | NIM_STRLIT_FLAG, "mipsel" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_80 = { 3 | NIM_STRLIT_FLAG, "arm" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_81 = { 5 | NIM_STRLIT_FLAG, "arm64" };
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_82 = { 2 | NIM_STRLIT_FLAG, "js" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_83 = { 5 | NIM_STRLIT_FLAG, "nimvm" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_84 = { 3 | NIM_STRLIT_FLAG, "avr" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_85 = { 6 | NIM_STRLIT_FLAG, "msp430" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_86 = { 7 | NIM_STRLIT_FLAG, "sparc64" };
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_87 = { 5 | NIM_STRLIT_FLAG, "s390x" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_88 = { 6 | NIM_STRLIT_FLAG, "mips64" };
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_89 = { 8 | NIM_STRLIT_FLAG, "mips64el" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_90 = { 7 | NIM_STRLIT_FLAG, "riscv32" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_91 = { 7 | NIM_STRLIT_FLAG, "riscv64" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_92 = { 3 | NIM_STRLIT_FLAG, "esp" };
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_93 = { 6 | NIM_STRLIT_FLAG, "wasm32" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_94 = { 3 | NIM_STRLIT_FLAG, "e2k" };
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_95 = { 11 | NIM_STRLIT_FLAG, "loongarch64" };
static const NimStringV2 TM__LEa0rTUoGHqcCT74IoUuTg_97 = {4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_78};
static const struct {
  NI cap; NIM_CHAR data[77+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_98 = { 77 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim(264, 9) `c != cpuNone` " };
static const NimStringV2 TM__LEa0rTUoGHqcCT74IoUuTg_99 = {77, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_98};
static const struct {
  NI cap; NIM_CHAR data[76+1];
} TM__LEa0rTUoGHqcCT74IoUuTg_100 = { 76 | NIM_STRLIT_FLAG, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim(265, 9) `o != osNone` " };
static const NimStringV2 TM__LEa0rTUoGHqcCT74IoUuTg_101 = {76, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_100};
N_LIB_PRIVATE NIM_CONST tyArray__QtmJy0ypYNZgjoouQCg8rg OS__platform_u534 = {{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_2},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_4},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_6},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_7},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_8},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_9},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_10},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_12},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
2}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_13},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_4},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_6},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_7},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_8},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_9},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_10},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_12},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
2}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_14},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_4},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_6},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_7},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_8},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_9},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_10},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_12},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
2}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_15},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_22},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_23},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_24},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_25},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_26},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_27},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_28},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{9, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_29},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_30},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_31},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_32},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
1}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_33},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_34},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{10, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_35},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
1}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_36},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_4},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_37},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
1}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_38},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_39},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_7},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_40},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
2}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_41},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_42},
{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_43},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_44},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_45},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
2}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_46},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{11, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_47},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
13}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_48},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_49},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
13}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_50},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_51},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_8},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_9},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_52},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
13}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_53},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{9, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_54},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
9}
,
{{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_55},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
0}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_56},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
0}
,
{{10, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_57},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
0}
,
{{14, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_58},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_59},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
5}
,
{{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_60},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
4}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_61},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
4}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_62},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
4}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_63},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_3},
{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_16},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_17},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_18},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_19},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_5},
{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_20},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
{0, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_21},
{1, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_11},
0}
}
;
N_LIB_PRIVATE NIM_CONST tyArray__egO9aXu9cYeNOlmFDj3yK9c9bw CPU__platform_u740 = {{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_67},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_68},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_69},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_70},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{9, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_71},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)64)}
,
{{11, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_72},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_73},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_74},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_75},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_76},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_77},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{4, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_78},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_79},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_80},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_81},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{2, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_82},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_83},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)32)}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_84},
((NI)16),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)32),
((NI)16)}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_85},
((NI)16),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)32),
((NI)16)}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_86},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)64)}
,
{{5, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_87},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)64)}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_88},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)1),
((NI)64),
((NI)64)}
,
{{8, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_89},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_90},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{7, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_91},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_92},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{6, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_93},
((NI)32),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)32)}
,
{{3, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_94},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
,
{{11, (NimStrPayload*)&TM__LEa0rTUoGHqcCT74IoUuTg_95},
((NI)64),
((tyEnum_Endianness__2E0yigCYXLLKcbirEgDEwA)0),
((NI)64),
((NI)64)}
}
;
extern NIM_BOOL nimInErrorMode__system_u4262;
extern TFrame* framePtr__system_u2667;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4262);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2667 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2667).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2667;
	framePtr__system_u2667 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4480();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2667 = (*framePtr__system_u2667).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw, nameToOS__platform_u850)(NimStringV2 name_p0) {
	tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw result;
NIM_BOOL* nimErr_;
	nimfr_("nameToOS", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{nimErr_ = nimErrorFlag();
	{
		tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw i_1;
		NI res_1;
		i_1 = (tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NI TM__LEa0rTUoGHqcCT74IoUuTg_64;
				if (!(res_1 <= ((NI)34))) goto LA3;
				nimlf_(275, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				i_1 = ((tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw) (res_1));
				nimln_(276);				{
					NI T6_;
					if (i_1 < 1 || i_1 > 34){ raiseIndexError3(i_1, 1, 34); goto BeforeRet_;
					}
					T6_ = (NI)0;
					T6_ = nsuCmpIgnoreStyle(name_p0, OS__platform_u534[(i_1)- 1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!(T6_ == ((NI)0))) goto LA7_;
					nimln_(277);					nimln_(274);					nimln_(277);					result = i_1;
					goto BeforeRet_;
				}
LA7_: ;
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__LEa0rTUoGHqcCT74IoUuTg_64)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__LEa0rTUoGHqcCT74IoUuTg_64);
			} LA3: ;
		}
	}
	nimlf_(278, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");	result = ((tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw)0);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA, nameToCPU__platform_u898)(NimStringV2 name_p0) {
	tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA result;
NIM_BOOL* nimErr_;
	nimfr_("nameToCPU", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{nimErr_ = nimErrorFlag();
	{
		tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA i_1;
		NI res_1;
		i_1 = (tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NI TM__LEa0rTUoGHqcCT74IoUuTg_96;
				if (!(res_1 <= ((NI)29))) goto LA3;
				nimlf_(286, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				i_1 = ((tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA) (res_1));
				nimln_(287);				{
					NI T6_;
					if (i_1 < 1 || i_1 > 29){ raiseIndexError3(i_1, 1, 29); goto BeforeRet_;
					}
					T6_ = (NI)0;
					T6_ = nsuCmpIgnoreStyle(name_p0, CPU__platform_u740[(i_1)- 1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!(T6_ == ((NI)0))) goto LA7_;
					nimln_(288);					nimln_(285);					nimln_(288);					result = i_1;
					goto BeforeRet_;
				}
LA7_: ;
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__LEa0rTUoGHqcCT74IoUuTg_96)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__LEa0rTUoGHqcCT74IoUuTg_96);
			} LA3: ;
		}
	}
	nimlf_(289, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");	result = ((tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA)0);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setTarget__platform_u750)(tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og* t_p0, tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw o_p1, tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA c_p2) {
NIM_BOOL* nimErr_;
	nimfr_("setTarget", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{nimErr_ = nimErrorFlag();
	nimln_(264);	{
		if (!!(!((c_p2 == ((tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA)0))))) goto LA3_;
		failedAssertImpl__stdZassertions_u242(TM__LEa0rTUoGHqcCT74IoUuTg_99);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(265);	{
		if (!!(!((o_p1 == ((tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw)0))))) goto LA7_;
		failedAssertImpl__stdZassertions_u242(TM__LEa0rTUoGHqcCT74IoUuTg_101);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA7_: ;
	nimln_(267);	(*t_p0).targetCPU = c_p2;
	nimln_(268);	(*t_p0).targetOS = o_p1;
	nimln_(269);	if (c_p2 < 1 || c_p2 > 29){ raiseIndexError3(c_p2, 1, 29); goto BeforeRet_;
	}
	(*t_p0).intSize = (NI)((CPU__platform_u740[(c_p2)- 1].Field1) / (((NI)8)));
	nimln_(270);	if (c_p2 < 1 || c_p2 > 29){ raiseIndexError3(c_p2, 1, 29); goto BeforeRet_;
	}
	(*t_p0).floatSize = (NI)((CPU__platform_u740[(c_p2)- 1].Field3) / (((NI)8)));
	nimln_(271);	if (c_p2 < 1 || c_p2 > 29){ raiseIndexError3(c_p2, 1, 29); goto BeforeRet_;
	}
	(*t_p0).ptrSize = (NI)((CPU__platform_u740[(c_p2)- 1].Field4) / (((NI)8)));
	nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");	if (o_p1 < 1 || o_p1 > 34){ raiseIndexError3(o_p1, 1, 34); goto BeforeRet_;
	}
	eqcopy___system_u2632((&(*t_p0).tnl), OS__platform_u534[(o_p1)- 1].Field5);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setTargetFromSystem__platform_u946)(tyObject_Target__bwH9a9bMaD8ygLVgxiU7P0Og* t_p0) {
	tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw T1_;
	tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA T2_;
NIM_BOOL* nimErr_;
	nimfr_("setTargetFromSystem", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(297, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");	T1_ = (tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw)0;
	T1_ = nameToOS__platform_u850(TM__LEa0rTUoGHqcCT74IoUuTg_66);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*t_p0).hostOS = T1_;
	nimln_(298);	T2_ = (tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA)0;
	T2_ = nameToCPU__platform_u898(TM__LEa0rTUoGHqcCT74IoUuTg_97);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*t_p0).hostCPU = T2_;
	nimln_(299);	setTarget__platform_u750(t_p0, (*t_p0).hostOS, (*t_p0).hostCPU);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, listOSnames__platform_u874)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	nimfr_("listOSnames", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{	nimln_(281);	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw i_1;
		NI res_1;
		i_1 = (tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NimStringV2 colontmpD_;
				NI TM__LEa0rTUoGHqcCT74IoUuTg_102;
				if (!(res_1 <= ((NI)34))) goto LA3;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(282, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				i_1 = ((tyEnum_TSystemOS__9a8p0DU9cUCtAY9aNCCrAf8tw) (res_1));
				nimln_(283);				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				if (i_1 < 1 || i_1 > 34){ raiseIndexError3(i_1, 1, 34); goto BeforeRet_;
				}
				colontmpD_ = eqdup___system_u2635(OS__platform_u534[(i_1)- 1].Field0);
				nimlf_(283, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				add__stdZenumutils_u71((&result), colontmpD_);
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__LEa0rTUoGHqcCT74IoUuTg_102)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__LEa0rTUoGHqcCT74IoUuTg_102);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, listCPUnames__platform_u922)(void) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
	nimfr_("listCPUnames", "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");
{	nimlf_(292, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA i_1;
		NI res_1;
		i_1 = (tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA)0;
		nimlf_(96, "/opt/local/lib/nim/lib/system/iterators_1.nim");		res_1 = ((NI)1);
		{
			nimln_(97);			while (1) {
				NimStringV2 colontmpD_;
				NI TM__LEa0rTUoGHqcCT74IoUuTg_103;
				if (!(res_1 <= ((NI)29))) goto LA3;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(293, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				i_1 = ((tyEnum_TSystemCPU__dnR41TFgLnVcgth4tVlU9bA) (res_1));
				nimln_(294);				nimlf_(1699, "/opt/local/lib/nim/lib/system.nim");				if (i_1 < 1 || i_1 > 29){ raiseIndexError3(i_1, 1, 29); goto BeforeRet_;
				}
				colontmpD_ = eqdup___system_u2635(CPU__platform_u740[(i_1)- 1].Field0);
				nimlf_(294, "/Users/svacchanda/Dev/nim-2.2.6/compiler/platform.nim");				add__stdZenumutils_u71((&result), colontmpD_);
				nimlf_(102, "/opt/local/lib/nim/lib/system/iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__LEa0rTUoGHqcCT74IoUuTg_103)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__LEa0rTUoGHqcCT74IoUuTg_103);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
